// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:06:24 2003]
// 
// File        : api_config.cpp
// Class       : api_config
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include <precomp.h>
#include "api_config.h"


