// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:06:25 2003]
// 
// File        : api_configx.cpp
// Class       : api_config
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------
#include <precomp.h>

#include "api_configx.h"
#include "api_configi.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS api_configX
START_DISPATCH;
  VCB(API_CONFIG_CONFIG_REGISTERCFGITEM, config_registerCfgItem);
  VCB(API_CONFIG_CONFIG_DEREGISTERCFGITEM, config_deregisterCfgItem);
  CB(API_CONFIG_CONFIG_GETNUMCFGITEMS, config_getNumCfgItems);
  CB(API_CONFIG_CONFIG_ENUMCFGITEM, config_enumCfgItem);
  CB(API_CONFIG_CONFIG_GETCFGITEMBYGUID, config_getCfgItemByGuid);
  VCB(API_CONFIG_SETINTPRIVATE, setIntPrivate);
  CB(API_CONFIG_GETINTPRIVATE, getIntPrivate);
  VCB(API_CONFIG_SETINTARRAYPRIVATE, setIntArrayPrivate);
  CB(API_CONFIG_GETINTARRAYPRIVATE, getIntArrayPrivate);
  VCB(API_CONFIG_SETSTRINGPRIVATE, setStringPrivate);
  CB(API_CONFIG_GETSTRINGPRIVATE, getStringPrivate);
  CB(API_CONFIG_GETSTRINGPRIVATELEN, getStringPrivateLen);
  VCB(API_CONFIG_SETINTPUBLIC, setIntPublic);
  CB(API_CONFIG_GETINTPUBLIC, getIntPublic);
  VCB(API_CONFIG_SETSTRINGPUBLIC, setStringPublic);
  CB(API_CONFIG_GETSTRINGPUBLIC, getStringPublic);
END_DISPATCH;
#undef CBCLASS

