#ifndef _SKINBMPS_H
#define _SKINBMPS_H
/*
typedef enum {
  SKIN_BITMAP_UNKNOWN,
	
	// Base texture
	SKIN_BITMAP_BASE_TEXTURE,

	// Framewnd
	SKIN_BITMAP_FRAME_VERTICAL_DIVIDER,
	SKIN_BITMAP_FRAME_HORIZONTAL_DIVIDER,

	// Listwnd/Treewnd
	SKIN_BITMAP_LIST_BACKGROUND,
	SKIN_BITMAP_TREE_BACKGROUND,

	// Appctrl
	SKIN_BITMAP_APPCTRL_LEFTARROW_NONPRESSED,
	SKIN_BITMAP_APPCTRL_LEFTARROW_PRESSED,
	SKIN_BITMAP_APPCTRL_RIGHTARROW_NONPRESSED,
	SKIN_BITMAP_APPCTRL_RIGHTARROW_PRESSED,
	SKIN_BITMAP_APPCTRL_WINDOWSIZER,
	SKIN_BITMAP_APPCTRL_PLAYERMODE_NONPRESSED,
	SKIN_BITMAP_APPCTRL_PLAYERMODE_PRESSED,
	SKIN_BITMAP_APPCTRL_MINIMIZE_NONPRESSED,
	SKIN_BITMAP_APPCTRL_MINIMIZE_PRESSED,
	SKIN_BITMAP_APPCTRL_MAXIMIZE_NONPRESSED,
	SKIN_BITMAP_APPCTRL_MAXIMIZE_PRESSED,
	SKIN_BITMAP_APPCTRL_CLOSE_NONPRESSED,
	SKIN_BITMAP_APPCTRL_CLOSE_PRESSED,
	SKIN_BITMAP_APPCTRL_SYSTEMICON,
	SKIN_BITMAP_APPCTRL_PLACEHOLDER_LEFT,
	SKIN_BITMAP_APPCTRL_PLACEHOLDER_MIDDLE,
	SKIN_BITMAP_APPCTRL_PLACEHOLDER_RIGHT,
	SKIN_BITMAP_APPCTRL_TITLEBAR,

	// Controls
	SKIN_BITMAP_PLAYBACKCONTROLS_PREVIOUS_NONPRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_PREVIOUS_PRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_PLAY_NONPRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_PLAY_PRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_PAUSE_NONPRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_PAUSE_PRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_STOP_NONPRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_STOP_PRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_NEXT_NONPRESSED,
	SKIN_BITMAP_PLAYBACKCONTROLS_NEXT_PRESSED,

	// Paintset
	SKIN_BITMAP_LABEL_UPPERLEFT,
	SKIN_BITMAP_LABEL_TOP,
	SKIN_BITMAP_LABEL_UPPERRIGHT,
	SKIN_BITMAP_LABEL_LEFT,
	SKIN_BITMAP_LABEL_MIDDLE,
	SKIN_BITMAP_LABEL_RIGHT,
	SKIN_BITMAP_LABEL_LOWERLEF,
	SKIN_BITMAP_LABEL_BOTTOM,
	SKIN_BITMAP_LABEL_LOWERRIGHT,
	SKIN_BITMAP_APPBORDER_UPPERLEFT,
	SKIN_BITMAP_APPBORDER_TOP,
	SKIN_BITMAP_APPBORDER_UPPERRIGHT,
	SKIN_BITMAP_APPBORDER_LEFT,
	SKIN_BITMAP_APPBORDER_RIGHT,
	SKIN_BITMAP_APPBORDER_LOWERLEFT,
	SKIN_BITMAP_APPBORDER_BOTTOM,
	SKIN_BITMAP_APPBORDER_LOWERRIGHT,

	// Seeker
	SKIN_BITMAP_SEEKBAR_LEFT,
	SKIN_BITMAP_SEEKBAR_MIDDLE,
	SKIN_BITMAP_SEEKBAR_RIGHT,
	SKIN_BITMAP_SEEKBAR_BUTTON_NONPRESSED,
	SKIN_BITMAP_BUTTON_PRESSED,

	// Status
	SKIN_BITMAP_STATUSBAR_LEFT,
	SKIN_BITMAP_STATUSBAR_MIDDLE,
	SKIN_BITMAP_STATUSBAR_RIGHT,

	// Volbar
	SKIN_BITMAP_VOLBAR_LEFT,
	SKIN_BITMAP_VOLBAR_MIDDLE,
	SKIN_BITMAP_VOLBAR_RIGHT,
	SKIN_BITMAP_VOLBAR_BUTTON_NONPRESSED,
	SKIN_BITMAP_VOLBAR_BUTTON_PRESSED,
	
	// Titlewnd
	SKIN_BITMAP_COMPONENT_PROP_TOP,
	SKIN_BITMAP_COMPONENT_PROP,
	SKIN_BITMAP_COMPONENT_PROP_MIDDLE,
	SKIN_BITMAP_COMPONENT_PROP_BOTTOM,

	// Videownd
	SKIN_BITMAP_MOVIE_BACKGROUND,

	// Seditwnd
	SKIN_BITMAP_AVS_SCRIPT_MARKER,
	SKIN_BITMAP_AVS_SCRIPT_PLAY_NONPRESSED,
	SKIN_BITMAP_AVS_SCRIPT_PLAY_PRESSED,
	SKIN_BITMAP_AVS_SCRIPT_PAUSE_NONPRESSED,
	SKIN_BITMAP_AVS_SCRIPT_PAUSE_PRESSED,
	SKIN_BITMAP_AVS_SCRIPT_STOP_NONPRESSED,
	SKIN_BITMAP_AVS_SCRIPT_STOP_PRESSED,
	SKIN_BITMAP_AVS_SCRIPT_TIMEARROW,
	SKIN_BITMAP_AVS_SCRIPT_BACKGROUND,
	SKIN_BITMAP_AVS_SCRIPT_ZOOMER_TOP,
	SKIN_BITMAP_AVS_SCRIPT_ZOOMER_MIDDLE,
	SKIN_BITMAP_AVS_SCRIPT_ZOOMER_BOTTOM,
	SKIN_BITMAP_AVS_SCRIPT_ZOOMER_BUTTON_NONPRESSED,
	SKIN_BITMAP_AVS_SCRIPT_ZOOMER_BUTTON_PRESSED,

// ComponentAPI1 ends here
  NUM_SKIN_BITMAP_ELEMENT_IDS
} SkinBitmapElementId;

typedef struct {
	SkinBitmapElementId id;
	char *fn;
	} SkinBitmapTableElement;
*/
#endif
