// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri Oct 01 02:49:41 1999]
// 
// File        : api_makix.cpp
// Class       : api_maki
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------
#include <precomp.h>

#include "api_makix.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS api_makiX
START_DISPATCH;
  VCB(API_MAKI_MAKI_PUSHOBJECT, maki_pushObject);
  VCB(API_MAKI_MAKI_PUSHINT, maki_pushInt);
  VCB(API_MAKI_MAKI_PUSHBOOLEAN, maki_pushBoolean);
  VCB(API_MAKI_MAKI_PUSHFLOAT, maki_pushFloat);
  VCB(API_MAKI_MAKI_PUSHDOUBLE, maki_pushDouble);
  VCB(API_MAKI_MAKI_PUSHSTRING, maki_pushString);
  VCB(API_MAKI_MAKI_PUSHVOID, maki_pushVoid);
  VCB(API_MAKI_MAKI_PUSHANY, maki_pushAny);
  CB(API_MAKI_MAKI_POPOBJECT, maki_popObject);
  CB(API_MAKI_MAKI_POPINT, maki_popInt);
  CB(API_MAKI_MAKI_POPBOOLEAN, maki_popBoolean);
  CB(API_MAKI_MAKI_POPFLOAT, maki_popFloat);
  CB(API_MAKI_MAKI_POPDOUBLE, maki_popDouble);
  CB(API_MAKI_MAKI_POPSTRING, maki_popString);
  CB(API_MAKI_MAKI_POPANY, maki_popAny);
  VCB(API_MAKI_MAKI_POPDISCARD, maki_popDiscard);
  CB(API_MAKI_MAKI_GETFUNCTION, maki_getFunction);
  CB(API_MAKI_MAKI_ADDDLFREF, maki_addDlfRef);
  VCB(API_MAKI_MAKI_ADDDLFCLASSREF, maki_addDlfClassRef);
  VCB(API_MAKI_MAKI_REMDLFREF, maki_remDlfRef);
  CB(API_MAKI_MAKI_CALLFUNCTION, maki_callFunction);
  CB(API_MAKI_MAKI_TRIGGEREVENT, maki_triggerEvent);
  CB(API_MAKI_MAKI_GETSCRIPTINT, maki_getScriptInt);
  CB(API_MAKI_MAKI_GETSCRIPTBOOLEAN, maki_getScriptBoolean);
  CB(API_MAKI_MAKI_GETSCRIPTFLOAT, maki_getScriptFloat);
  CB(API_MAKI_MAKI_GETSCRIPTDOUBLE, maki_getScriptDouble);
  CB(API_MAKI_MAKI_GETSCRIPTSTRING, maki_getScriptString);
  CB(API_MAKI_MAKI_GETSCRIPTOBJECT, maki_getScriptObject);
  CB(API_MAKI_MAKI_UPDATEDLF, maki_updateDlf);
  CB(API_MAKI_MAKI_INSTANTIATE, maki_instantiate);
  VCB(API_MAKI_MAKI_DESTROY, maki_destroy);
  CB(API_MAKI_MAKI_ENCAPSULATE, maki_encapsulate);
  VCB(API_MAKI_MAKI_DEENCAPSULATE, maki_deencapsulate);
  CB(API_MAKI_MAKI_GETCONTROLLER, maki_getController);
  CB(API_MAKI_MAKI_CREATEORPHAN, maki_createOrphan);
  VCB(API_MAKI_MAKI_KILLORPHAN, maki_killOrphan);
  VCB(API_MAKI_MAKI_SETOBJECTATOM, maki_setObjectAtom);
  CB(API_MAKI_MAKI_GETOBJECTATOM, maki_getObjectAtom);
  #ifdef WASABI_COMPILE_WND
  CB(API_MAKI_MAKI_FINDOBJECT, maki_findObject);
  #endif
  VCB(API_MAKI_VCPU_ADDSCRIPTOBJECT, vcpu_addScriptObject);
  VCB(API_MAKI_VCPU_REMOVESCRIPTOBJECT, vcpu_removeScriptObject);
  CB(API_MAKI_VCPU_GETCACHECOUNT, vcpu_getCacheCount);
  CB(API_MAKI_VCPU_ISVALIDSCRIPTID, vcpu_isValidScriptId);
  CB(API_MAKI_VCPU_MAPVARID, vcpu_mapVarId);
  CB(API_MAKI_VCPU_GETUSERANCESTORID, vcpu_getUserAncestorId);
  CB(API_MAKI_VCPU_GETNUMEVENTS, vcpu_getNumEvents);
  CB(API_MAKI_VCPU_GETEVENT, vcpu_getEvent);
  CB(API_MAKI_VCPU_GETCOMPLETE, vcpu_getComplete);
  VCB(API_MAKI_VCPU_SETCOMPLETE, vcpu_setComplete);
  VCB(API_MAKI_VCPU_RESETCOMPLETE, vcpu_resetComplete);
  CB(API_MAKI_VCPU_GETCLASSNAME, vcpu_getClassName);
END_DISPATCH;
#undef CBCLASS
