// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:09:18 2003]
// 
// File        : scriptobjx.cpp
// Class       : ScriptObject
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------
#include "scriptobjx.h"
#include "scriptobji.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS ScriptObjectX
START_DISPATCH;
  CB(SCRIPTOBJECT_VCPU_GETINTERFACE, vcpu_getInterface);
  CB(SCRIPTOBJECT_VCPU_GETINTERFACEOBJECT, vcpu_getInterfaceObject);
  CB(SCRIPTOBJECT_VCPU_GETASSIGNEDVARIABLE, vcpu_getAssignedVariable);
  VCB(SCRIPTOBJECT_VCPU_REMOVEASSIGNEDVARIABLE, vcpu_removeAssignedVariable);
  VCB(SCRIPTOBJECT_VCPU_ADDASSIGNEDVARIABLE, vcpu_addAssignedVariable);
  CB(SCRIPTOBJECT_VCPU_GETCLASSNAME, vcpu_getClassName);
  CB(SCRIPTOBJECT_VCPU_GETCONTROLLER, vcpu_getController);
  CB(SCRIPTOBJECT_VCPU_GETSCRIPTID, vcpu_getScriptId);
  VCB(SCRIPTOBJECT_VCPU_SETSCRIPTID, vcpu_setScriptId);
  CB(SCRIPTOBJECT_VCPU_GETMEMBER, vcpu_getMember);
  VCB(SCRIPTOBJECT_VCPU_DELMEMBERS, vcpu_delMembers);
  VCB(SCRIPTOBJECT_VCPU_SETINTERFACE, vcpu_setInterface);
  VCB(SCRIPTOBJECT_VCPU_SETCLASSNAME, vcpu_setClassName);
  VCB(SCRIPTOBJECT_VCPU_SETCONTROLLER, vcpu_setController);
  VCB(SCRIPTOBJECT_VCPU_INIT, vcpu_init);
END_DISPATCH;
#undef CBCLASS

