//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ogg.rc
//
#define IDS_NULLSOFT_VORBIS_DECODER_OLD 0
#define IDS_PLEASE_ENTER_TAG_NAME       1
#define IDS_TAG_NAME_CONTAINS_INVALID_CHARS 2
#define IDOKAUTH                        3
#define IDS_ERASE_ALL_FIELDS_ON_LIST    3
#define IDCANCELAUTH                    4
#define IDS_WARNING                     4
#define IDS_FILE_ERROR                  5
#define IDS_LENGTH                      6
#define IDS_AVERAGE_BITRATE             7
#define IDS_FILE_SIZE                   8
#define IDS_NOMINAL_BITRATE             9
#define IDS_MIN_BITRATE                 10
#define IDS_MAX_BITRATE                 11
#define IDS_CHANNELS                    12
#define IDS_SAMPLING_RATE               13
#define IDS_SERIAL_NUMBER               14
#define IDS_VERSION                     15
#define IDS_Vendor                      16
#define IDS_VENDOR                      16
#define IDS_TO_SIMPLE_MODE              17
#define IDS_TO_ADVANCED_MODE            18
#define IDS_OGG_VORBIS_INFO             19
#define IDS_WRITE_ERROR                 20
#define IDS_BEST_RPM                    21
#define IDS_ABOUT                       22
#define IDS_LEAVE_AS_IS                 24
#define IDS_REMAP_6_CHANNELS            25
#define IDS_DOWNMIX_TO_4_CHANNELS       26
#define IDS_DOWNMIX_TO_2_CHANNELS_DS    27
#define IDS_DOWNMIX_TO_2_CHANNELS_DS2   28
#define IDS_DOWNMIX_TO_MONO             29
#define IDS_CORRECT_FL_FC_FR_BL_BR_LFE  30
#define IDS_BROKEN_FL_FR_FC_BL_BR_LFE   31
#define IDS_IDLE                        32
#define IDS_ABOUT_TEXT                  32
#define IDS_LOWEST                      33
#define IDS_BELOW_NORMAL                34
#define IDS_NORMAL                      35
#define IDS_ABOVE_NORMAL                36
#define IDS_HIGHEST                     37
#define IDS_TIME_CRITICAL               38
#define IDS_TITLE_PREFERENCES           39
#define IDS_DO_NOT_ENABLE_24_BIT_OUTPUT 40
#define IDS_ONE_TIME_FAQ_REMINDER       41
#define IDS_RUNNING_ON_NT_OS            42
#define IDS_RUNNING_ON_WIN9X            43
#define IDS_NEVER                       44
#define IDS_PORT_80_ONLY                45
#define IDS_ALWAYS                      46
#define IDS_SELECT_OUTPUT_DIRECTORY     47
#define IDS_DECODING                    48
#define IDS_DISPLAY                     49
#define IDS_STREAMING                   50
#define IDS_CONNECTING                  51
#define IDS_PREBUFFERING                52
#define IDS_AUTH_REQUIRED               53
#define IDS_OGG_FILES                   54
#define IDS_NAME                        55
#define IDS_VALUE                       56
#define IDS_KBPS                        57
#define IDS_STRING2                     58
#define IDS_HZ                          58
#define IDS_GAME_SPEED                  59
#define IDS_STRING1                     60
#define IDS_BYTES                       60
#define IDS_FAMILY_STRING               61
#define IDC_CONFIG_TAB1                 101
#define IDD_INFO_DLG                    102
#define IDC_CONFIG_TAB2                 102
#define IDC_CONFIG_TAB3                 103
#define IDD_INFO_DLG1                   104
#define IDC_CONFIG_TAB4                 104
#define IDD_ABOUT                       112
#define IDB_BITMAP1                     115
#define IDB_BITMAP2                     116
#define IDB_BITMAP3                     117
#define IDB_BITMAP4                     118
#define IDB_BITMAP5                     119
#define IDB_BITMAP6                     120
#define IDB_BITMAP7                     121
#define IDB_BITMAP8                     122
#define IDB_BITMAP9                     123
#define IDB_BITMAP10                    124
#define IDB_BITMAP11                    125
#define IDB_BITMAP12                    126
#define IDD_HTTPAUTH                    128
#define IDD_INFO                        131
#define IDD_DIALOG1                     132
#define IDD_CONFIG                      132
#define IDD_INFO_DLG_NEW                133
#define IDD_INFO_PANEL_ADVANCED         134
#define IDD_INFO_PANEL_SIMPLE           135
#define IDB_PNG1                        136
#define IDB_PNG2                        137
#define IDB_PNG3                        138
#define IDB_PNG4                        139
#define IDB_PNG5                        140
#define IDB_PNG6                        141
#define IDB_PNG7                        142
#define IDB_PNG8                        143
#define IDB_PNG9                        144
#define IDB_PNG10                       145
#define IDB_PNG11                       146
#define IDB_PNG12                       147
#define IDC_LIST                        1001
#define IDC_NAME                        1002
#define IDC_TITLE                       1002
#define IDC_VALUE                       1003
#define IDC_ARTIST                      1003
#define IDC_HTTP_BSIZE                  1004
#define IDC_ALBUM                       1004
#define IDC_STREAM_SAVE                 1005
#define IDC_GENRE                       1005
#define IDC_FSAVE                       1006
#define IDC_YEAR                        1006
#define IDC_DATE                        1006
#define IDC_CUSTOM1                     1007
#define IDC_MISC                        1007
#define IDC_AVG_BR                      1008
#define IDC_FIX0R                       1009
#define IDC_PROXY                       1012
#define IDC_URL                         1012
#define IDC_SLIDER1                     1013
#define IDC_SLIDER2                     1014
#define IDC_BUTTON_ADD                  1015
#define IDC_BUTTON_DEL                  1016
#define IDC_BUTTON_DELALL               1017
#define IDC_RPM                         1018
#define IDC_RPM2                        1019
#define IDC_MC6_DM                      1020
#define IDC_MC6_MAP                     1021
#define IDC_SSAVE_FMT                   1022
#define IDC_SSAVE_FMT_DEF               1023
#define IDC_FULLBUF                     1025
#define IDC_EDITAUTH                    1026
#define IDC_REALM                       1027
#define IDC_TRACK                       1028
#define IDC_STATIC_MISC                 1034
#define IDC_STATIC_TAGS                 1035
#define IDC_STATIC_STD                  1036
#define IDC_STATIC_TRACK                1037
#define IDC_SEPARATE                    1038
#define IDC_DELETE_ALL                  1039
#define IDC_RG                          1040
#define IDC_RG_MODE                     1041
#define IDC_NOCLIP                      1042
#define IDC_HARDLIMIT                   1043
#define IDC_PREAMP_STAT                 1044
#define IDC_TAB                         1045
#define IDC_MODE_TOGGLE                 1053
#define IDC_NEXT_STREAM                 1054
#define IDC_PREV_STREAM                 1055
#define IDC_STATIC_CS                   1056
#define IDC_HIDE_SPEC                   1058
#define IDC_COMMENT                     1060
#define IDC_ABOUT_TEXT                  1061
#define IDC_OS_BLAH                     1062
#define IDC_REMEMBER_INFOSIZE           1063
#define IDC_FONTNAME                    1064
#define IDC_PREAMP_RG                   1065
#define IDS_NULLSOFT_VORBIS_DECODER     65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
