// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:56:11 2003]
// 
// File        : api_servicex.cpp
// Class       : api_service
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------
#include <precomp.h>
#ifndef NOSVCMGR
#include "api_servicex.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS api_serviceX
START_DISPATCH;
  CB(API_SERVICE_SERVICE_REGISTER, service_register);
  CB(API_SERVICE_SERVICE_DEREGISTER, service_deregister);
  CB(API_SERVICE_SERVICE_GETNUMSERVICES, service_getNumServices);
  CB(API_SERVICE_SERVICE_ENUMSERVICE, service_enumService);
  CB(API_SERVICE_SERVICE_GETSERVICEBYGUID, service_getServiceByGuid);
  CB(API_SERVICE_SERVICE_LOCK, service_lock);
  CB(API_SERVICE_SERVICE_CLIENTLOCK, service_clientLock);
  CB(API_SERVICE_SERVICE_RELEASE, service_release);
  CB(API_SERVICE_SERVICE_GETTYPENAME, service_getTypeName);
  #ifdef WASABI_COMPILE_COMPONENTS
  CB(API_SERVICE_SERVICE_GETOWNINGCOMPONENT, service_getOwningComponent);
  CB(API_SERVICE_SERVICE_GETLOCKINGCOMPONENT, service_getLockingComponent);
  #endif // WASABI_COMPILE_COMPONENTS
  CB(API_SERVICE_SERVICE_UNLOCK, service_unlock);
  CB(API_SERVICE_ISVALID, service_isvalid);
END_DISPATCH;
#undef CBCLASS
#endif