// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:57:16 2003]
// 
// File        : waservicefactoryx.h
// Class       : waServiceFactory
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#ifndef __WASERVICEFACTORYX_H
#define __WASERVICEFACTORYX_H

#include "waservicefactory.h"

// ----------------------------------------------------------------------------

class NOVTABLE waServiceFactoryX : public waServiceFactory {
  protected:
    waServiceFactoryX() {}
  protected:
  
 public:

    virtual FOURCC x_getServiceType()=0;
    virtual const char *x_getServiceName()=0;
    virtual GUID getGuid()=0;
    virtual void *getInterface(int global_lock = TRUE)=0;
    virtual void *_RETIRED_getInterface()=0;
    virtual int supportNonLockingGetInterface()=0;
    virtual int releaseInterface(void *ifc)=0;
    virtual const wchar_t *getTestString()=0;
    virtual int serviceNotify(int msg, int param1 = 0, int param2 = 0)=0;
  
  protected:
    RECVS_DISPATCH;
};

#endif // __WASERVICEFACTORYX_H
