!ifndef NULLSOFT_WINAMP_UNINSTALLER_SECTION_DESCRIPTION_TABLE_HEADER
!define NULLSOFT_WINAMP_UNINSTALLER_SECTION_DESCRIPTION_TABLE_HEADER

!include ".\utils\sectionDescription.nsh"

${UNINSTALL_DESCRIPTION_TABLE_BEGIN}
	${DESCRIPTION} IDX_UNINSTALL_COMPONENTS_GROUP $(IDS_UNINSTALL_COMPONENTS_GROUP_DESC)
	${DESCRIPTION} IDX_UNINSTALL_MEDIA_PLAYER $(IDS_UNINSTALL_MEDIA_PLAYER_DESC)
	${DESCRIPTION} IDX_UNINSTALL_USER_PREFERENCES $(IDS_UNINSTALL_USER_PREFERENCES_DESC)
${DESCRIPTION_TABLE_END}

!endif ;NULLSOFT_WINAMP_UNINSTALLER_SECTION_DESCRIPTION_TABLE_HEADER