// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:58:36 2003]
// 
// File        : syscbx.h
// Class       : SysCallback
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#ifndef __SYSCALLBACKX_H
#define __SYSCALLBACKX_H

#include "syscb.h"




// ----------------------------------------------------------------------------

class SysCallbackX : public SysCallback {
  protected:
    SysCallbackX() {}
  public:
    virtual FOURCC getEventType()=0;
    virtual int notify(int msg, intptr_t param1 = 0, intptr_t param2 = 0)=0;
  
  protected:
    RECVS_DISPATCH;
};

#endif // __SYSCALLBACKX_H
