// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:58:36 2003]
// 
// File        : syscbx.cpp
// Class       : SysCallback
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------
#include "precomp.h"

#include "syscbx.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS SysCallbackX
START_DISPATCH;
  CB(SYSCALLBACK_GETEVENTTYPE, getEventType);
  CB(SYSCALLBACK_NOTIFY, notify);
END_DISPATCH;
#undef CBCLASS
