#ifndef NULLSOFT_WASABICFG_H
#define NULLSOFT_WASABICFG_H

#define WASABI_COMPILE_WNDMGR
#define WASABI_COMPILE_CONFIG
#define WASABI_COMPILE_SCRIPT
#define WASABI_COMPILE_SKIN
#define WASABI_COMPILE_WND
#define WASABI_COMPILE_TIMERS
#define WASABI_COMPILE_FONTS
#define WASABI_COMPILE_IMGLDR
#define WASABI_COMPILE_SYSCB
#define WASABI_COMPILE_FILEREADER

#define WASABINOMAINAPI

#endif