// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:58:14 2003]
// 
// File        : api_syscb.cpp
// Class       : api_syscb
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include <precomp.h>
#include "api_syscb.h"

api_syscb *sysCallbackApi=NULL;


