//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDS_PLUGIN_NAME                 1
#define IDS_MODULE_NAME                 2
#define IDS_LAMEDLL_ISSUE               4
#define IDS_CURRENT_BITRATE             5
#define IDS_ENCODER_SETTINGS            6
#define IDS_OUTPUT_X                    7
#define IDS_NONE                        8
#define IDS_MP3_ENCODER                 9
#define IDS_AACP_ENCODER                10
#define IDS_AAC_LC_ENCODER              11
#define IDS_NO_ENCODER_SELECTED         12
#define IDS_PANEL_CONNECTION            13
#define IDS_PANEL_LOGIN                 13
#define IDS_PANEL_YELLOWPAGES           14
#define IDS_PANEL_DIRECTORY             14
#define IDS_PANEL_ENCODERS              15
#define IDS_TAB_MAIN                    16
#define IDS_TAB_OUTPUT                  17
#define IDS_TAB_INPUT                   18
#define IDS_COL_OUTPUT_NAME             20
#define IDS_COL_STATUS                  21
#define IDS_INPUT_WINAMP                22
#define IDS_INPUT_SOUNDCARD             23
#define IDS_X_DB                        24
#define IDS_INF_DB                      25
#define IDS_NOT_CONNECTED               26
#define IDS_ERROR                       27
#define IDS_CONNECTING                  28
#define IDS_SEND_CIPHER_REQUEST         29
#define IDS_CIPHER_RESPONSE_RECEIVED    30
#define IDS_SENDING_AUTH                31
#define IDS_RECEIVING_AUTH_RESPONSE     32
#define IDS_SENDING_CONTENT_TYPE        33
#define IDS_RESPONSE_RECEIVED           34
#define IDS_SENDING_BITRATE             35
#define IDS_SEND_BUF_SIZE               37
#define IDS_SEND_MAX_PAYLOAD_SIZE       38
#define IDS_SEND_YP_INFO                39
#define IDS_SEND_FLUSH                  40
#define IDS_SEND_STANDBY                41
#define IDS_SEND_INTRO_FILE             42
#define IDS_SEND_BACKUP_FILE            43
#define IDS_DISCONNECTING               44
#define IDS_SENT_X_BYTES                45
#define IDS_RECONNECTING_X              46
#define IDS_SEND_TITLE_UPDATE           47
#define IDS_CONNECT                     48
#define IDS_KILL                        49
#define IDS_ABORT                       50
#define IDS_DISCONNECT                  51
#define IDS_X_HZ_X                      53
#define IDS_MONO                        54
#define IDS_STEREO                      55
#define IDS_X_MS                        56
#define IDS_AAC_LC_CONFIG_TITLE         58
#define IDS_STRING59                    59
#define IDS_PLUGIN_UNINSTALL            59
#define IDS_PASS_ERROR                  62
#define IDS_OGG_ENCODER                 63
#define IDS_OGG_CONFIG_TITLE            64
#define IDS_XP_SOUND                    65
#define IDS_STRING65                    65
#define IDS_DEVICE_STRING               65
#define IDS_MIC_LEGACY_MODE             66
#define IDS_LINEIN_LEGACY_MODE          67
#define IDS_PTT_ON_STARTUP              68
#define IDS_PANEL_LOGGING               69
#define IDS_CIPHER_ERROR                70
#define IDS_STRING36                    71
#define IDS_NO_DEVICES_FOUND            71
#define IDS_NO_CAPTURE_DEVICES          72
#define IDS_ABOUT_MESSAGE               73
#define IDS_CIPHER_ERROR_ENABLE_V1_MODE 74
#define IDS_PANEL_ART                   75
#define IDS_JPEG_FILE                   76
#define IDS_PNG_FILE                    77
#define IDS_BMP_FILE                    78
#define IDS_GIF_FILE                    79
#define IDS_FHGAAC_ENCODER              80
#define IDS_PANEL_TITLES                81
#define IDS_PUBLIC                      82
#define IDS_PRIVATE                     83
#define IDS_FOLLOW_WA                   84
#define IDS_MANUAL                      85
#define IDS_DISABLED                    86
#define IDS_NOT_SET                     87
#define IDS_SUMMARY                     88
#define IDS_LAME_ENCODER_VER            89
#define IDS_SUMMARY_KBPS                90
#define IDS_X_DB_PEAK                   91
#define IDS_CHANGE_NAME                 92
#define IDS_SET_PASSWORD                93
#define IDS_SET_ENCODER                 94
#define IDS_STREAMID_ERROR              95
#define IDS_PARSE_ERROR                 96
#define IDS_VERSION_ERROR               97
#define IDS_IN_USE_ERROR                98
#define IDS_YES                         99
#define IDS_YES2                        100
#define IDS_NO                          100
#define IDD_DIALOG                      101
#define IDS_NOT_CONFIGURED              101
#define IDS_ALL_FILES                   102
#define IDD_MAIN                        103
#define IDS_MPEG_AUDIO_FILES            103
#define IDD_CONNECTION                  104
#define IDS_BITRATE_ERROR               104
#define IDD_ENCODER                     105
#define IDS_SET_SERVER                  105
#define IDD_INPUT                       106
#define IDS_NOT_SET_SUMMARY             106
#define IDD_PANEL_LINEIN                107
#define IDS_SENT_X                      107
#define IDI_ICY                         108
#define IDS_B                           108
#define IDS_KIB                         109
#define IDD_PANEL_DIRECTORY             110
#define IDS_MiB                         110
#define IDS_MIB                         110
#define IDS_GiB                         111
#define IDS_GIB                         111
#define IDS_TIB                         112
#define IDD_NSVCONFIG                   113
#define IDS_BLOCKED_ERROR               113
#define IDS_V2_ARTWORK                  114
#define IDB_BITMAP1                     115
#define IDS_ENABLED_SIZE                115
#define IDS_EMPTY_ART                   116
#define IDS_STREAM_MOVED_ERROR          117
#define IDS_ARTWORK_SIZES               120
#define IDS_FILEPATH                    121
#define IDI_DOWNARROW                   122
#define IDS_TITLE                       122
#define IDD_LOGGING                     123
#define IDS_ARTIST                      123
#define IDI_REFRESH                     124
#define IDD_ARTWORK                     124
#define IDS_ALBUM                       124
#define IDD_PANEL_TITLE                 125
#define IDS_GENRE                       125
#define IDS_YEAR                        126
#define IDI_PLAY                        127
#define IDS_COMMENT                     127
#define IDI_STOP                        128
#define IDS_FAILED_LOAD_LAMEDLL         128
#define IDI_KILL                        129
#define IDS_MP3_ENCODING_NOT_AVAILABLE  129
#define IDS_SWITCHING_PROTOCOL          130
#define IDS_AUTOMATIC                   131
#define IDD_PANEL_WINAMP                132
#define IDS_V2_MODE                     132
#define IDD_PANEL_LOGIN                 133
#define IDS_V1_MODE                     133
#define IDD_ABOUT                       134
#define IDS_ENABLE_OTHER_MODE           134
#define IDS_24BIT_MODE_DETECTED         135
#define IDS_UPDATE_HEADER               136
#define IDS_UPDATE_TITLE                137
#define IDS_TAB_ABOUT                   138
#define IDS_UPDATE                      139
#define IDS_UPDATE_CHECK_ERROR          140
#define IDS_CHECK_FOR_UPDATES           141
#define IDS_CHECKING_FOR_UPDATES        142
#define IDS_NO_NEW_UPDATE               143
#define IDS_STRING144                   144
#define IDS_HAS_NEW_UPDATE              144
#define IDS_CHECK_UPDATE_FAIL           145
#define IDC_ABOUT_ICON                  666
#define IDC_TAB                         1000
#define IDC_RECT                        1001
#define IDC_OUTPUTSTATUS                1002
#define IDC_ADDRESS                     1003
#define IDC_PORT                        1004
#define IDC_PASSWORD                    1005
#define IDC_CONNECT                     1006
#define IDC_STATUS                      1007
#define IDC_OUTPUTLIST                  1008
#define IDC_ENCODERLIST                 1009
#define IDC_ENCSETTINGS                 1010
#define IDC_ENCTYPE                     1012
#define IDC_STATIONID                   1014
#define IDC_AUTOTITLE4                  1015
#define IDC_AUTOTITLE5                  1016
#define IDC_DESCRIPTION                 1017
#define IDC_PUBLIC                      1019
#define IDC_URL                         1020
#define IDC_GENRE                       1021
#define IDC_AIM                         1022
#define IDC_ICQ                         1023
#define IDC_IRC                         1024
#define IDC_SENDNEXTTITLES              1025
#define IDC_TITLE                       1027
#define IDC_NEXT                        1028
#define IDC_INPUTDEVICE                 1031
#define IDC_MUS2SLIDER                  1032
#define IDC_VOLUMETEXT_L                1033
#define IDC_VOLUMEGRAPH_L               1034
#define IDC_VOLUMETEXT_R                1035
#define IDC_VOLUMEGRAPH_R               1036
#define IDC_VOLUMETEXT_LP               1037
#define IDC_VOLUMETEXT_RP               1038
#define IDC_MUSSLIDER                   1039
#define IDC_MICSLIDER                   1040
#define IDC_MICLEV_TEXT                 1041
#define IDC_FADESLIDER                  1042
#define IDC_FADETIME_TEXT               1043
#define IDC_MIXER                       1044
#define IDC_PTT                         1045
#define IDC_LOCK                        1046
#define IDC_MICFADESLIDER               1047
#define IDC_MICFADETIME_TEXT            1048
#define IDC_INPUTDEVICESTATIC           1049
#define IDC_INPUTSETUP                  1050
#define IDC_SNDCARDSTATIC               1051
#define IDC_MICINPUTSTATIC              1052
#define IDC_SNDCARDSTATIC2              1052
#define IDC_MUSSTATIC                   1053
#define IDC_BGMUSSTATIC                 1054
#define IDC_MICSTATIC                   1055
#define IDC_FADESTATIC                  1056
#define IDC_INPUTSETUPSTATIC            1057
#define IDC_MICFADESTATIC               1057
#define IDC_PANEL_RECT                  1058
#define IDC_RECONNECT                   1060
#define IDC_TIMEOUT                     1061
#define IDC_PANELRECT_C                 1062
#define IDC_CONTAB                      1063
#define IDC_CHECK_MINTOSYSTRAY          1064
#define IDC_MINTOSYSTRAY                1065
#define IDC_ENCSETTINGS_BUTTON          1066
#define IDC_ENCSETTINGS_LABEL           1067
#define IDC_ENCSETTINGS_LAME_VER        1068
#define IDC_USERID                      1069
#define IDC_LOCK_MODE                   1070
#define IDC_REFRESH_DEVICES             1071
#define IDC_ABOUTLINK                   1072
#define IDC_SEND                        1073
#define IDC_INPUTMODE                   1074
#define IDC_SUMMARY                     1075
#define IDC_DEVBOX                      1076
#define IDC_CURDEVICE                   1077
#define IDC_INFO_FRAME                  1079
#define IDC_INFO_TEXT                   1080
#define IDC_INFO_FRAME2                 1081
#define IDC_LOGGING                     1081
#define IDC_INFO_TEXT2                  1082
#define IDC_CLEAR_LOG                   1082
#define IDC_VIEW_LOG                    1083
#define IDC_INFO_TEXT3                  1083
#define IDC_CLEAR_ON_STARTUP            1084
#define IDC_INFO_TEXT4                  1084
#define IDC_IGNORE_SENT_MESSAGE         1085
#define IDC_NEXT_TRACK_LOG              1086
#define IDC_NEXT_TRACK_EDIT             1087
#define IDC_NEXT_TRACK_XML              1088
#define IDC_NEXT_TRACK_BROWSE           1089
#define IDC_USE_ART                     1090
#define IDC_USE_ART_PLAYING             1091
#define IDC_USE_ART_STREAM              1092
#define IDC_ART_BROWSE                  1093
#define IDC_ART_EDIT                    1094
#define IDC_ART_V1_NOTE                 1095
#define IDC_ART_V1_NOTE2                1096
#define IDC_SPIN1                       1097
#define IDC_ART_V2_NOTE                 1097
#define IDC_SPIN2                       1098
#define IDC_GENRES                      1099
#define IDC_NOTITLES                    1100
#define IDC_AUTOTITLE                   1101
#define IDC_EXTERNALTITLE               1102
#define IDC_MANUALTITLE                 1103
#define IDC_INPUT_METERS                1104
#define IDC_STREAM_1                    1105
#define IDC_STREAM_2                    1106
#define IDC_STREAM_3                    1107
#define IDC_STREAM_4                    1108
#define IDC_STREAM_5                    1109
#define IDC_FORUMLINK                   1110
#define IDC_HELPLINK                    1111
#define IDC_GO_HERE                     1112
#define IDC_FORUMLINK2                  1112
#define IDC_GET_UPDATE                  1112
#define IDC_TIMEOUT2                    1113
#define IDC_UPDATELINK                  1113
#define IDC_AUTOCONNECT                 1114
#define IDC_AUTOURL                     1115
#define IDC_PROGRAMNAME                 1116
#define IDC_SERVERURL                   1117
#define IDC_MUSLEV1_TEXT                1118
#define IDC_MUSLEV2_TEXT                1119
#define IDC_SAVE_ENCODED_AUDIO          1120
#define IDC_SAVE_ENCODED_AUDIO_EDIT     1121
#define IDC_SAVE_ENCODED_AUDIO_BROWSE   1122
#define IDC_INFO_FRAME3                 1123
#define IDC_INFO_FRAME4                 1124
#define IDC_INFO_FRAME5                 1125
#define IDC_ADDRESS_HEADER              1126
#define IDC_PASSWORD_HEADER             1127
#define IDC_NAME_HEADER                 1128
#define IDC_ENCODER_HEADER              1129
#define IDC_INPUT_WINAMP                1130
#define IDC_INPUT_SOUNDCARD             1131
#define IDC_ARTWORK_V1_FRAME            1132
#define IDC_ARTWORK_V1_FRAME2           1133
#define IDC_ARTWORK_V2_FRAME            1133
#define IDC_ARTWORK                     1133
#define IDC_ARTWORK2                    1134
#define IDC_ARTWORK3                    1135
#define IDC_METALIST                    1136
#define IDC_PROTOCOL                    1137
#define IDC_STATIC_UPDATE               1138
#define IDC_UPDATE_HEADER               1139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
