//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SCRIPT1.RC
//
#define IDS_PREVIOUS_TRACK              0
#define IDS_PLAY_PAUSE                  1
#define IDS_STOP                        2
#define IDC_APPLY                       3
#define IDS_NEXT_TRACK                  3
#define IDS_OPEN_FILE                   4
#define IDS_COMPACT_MODE                5
#define IDS_DECREASE_VOLUME             6
#define IDS_INCREASE_VOLUME             7
#define IDS_HOLD_CTRL                   8
#define IDS_HOLD_SHIFT                  9
// #define IDS_WIN2K_PLUS               10
#define IDS_CTRL_TO_DECREASE            11
#define IDS_CTRL_TO_INCREASE            12
#define IDS_STOPPED_STR                 13
#define IDS_PAUSED_STR                  14
#define IDS_DEFAULT_ICONS               15
#define IDS_CUSTOM_ICON_PACK            16
#define IDS_CONFIG_INFO                 17
#define IDS_OFD_FILTER_STR              18
#define IDS_OFD_TITLE_STR               19
#define IDS_STRING22                    20
#define IDS_GET_ICON_PACKS              21
#define IDS_DO_YOU_ALSO_WANT_TO_REMOVE_SETTINGS 22
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     102
#define IDI_ICON1                       103
#define IDI_ICON2                       104
#define IDI_ICON3                       105
#define IDI_ICON4                       106
#define IDI_ICON5                       107
#define IDI_ICON6                       108
#define IDI_ICON7                       109
#define IDI_ICON8                       110
#define IDB_BITMAP1                     111
#define IDC_ONOFF                       1000
#define IDC_PREV                        1001
#define IDC_PREV2                       1002
#define IDC_PREV3                       1003
#define IDC_PREV4                       1004
#define IDC_PREV5                       1005
#define IDC_PREV6                       1006
#define IDC_PREV7                       1007
#define IDC_PREV8                       1008
#define IDC_COMBO1                      1009
#define IDC_EDIT1                       1010
#define IDC_BUTTON1                     1011
#define ID_INFO                         1012
#define IDC_COMBO2                      1013
#define IDC_LINK                        1014
#define IDS_NULLSOFT_TRAY_CONTROL       65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
