// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:06:33 2003]
// 
// File        : rootobjcb.h
// Class       : RootObjectCallback
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#ifndef __ROOTOBJECTCALLBACK_H
#define __ROOTOBJECTCALLBACK_H

#include <bfc/dispatch.h>
#include <bfc/common.h>



// ----------------------------------------------------------------------------

class RootObjectCallback: public Dispatchable {
  protected:
    RootObjectCallback() {}
    ~RootObjectCallback() {}
  public:
    void rootobjectcb_onNotify(const wchar_t *a, const wchar_t *b, int c, int d);
  
  protected:
    enum {
      ROOTOBJECTCALLBACK_ROOTOBJECTCB_ONNOTIFY = 10,
    };
};

// ----------------------------------------------------------------------------

inline void RootObjectCallback::rootobjectcb_onNotify(const wchar_t *a, const wchar_t *b, int c, int d) {
  _voidcall(ROOTOBJECTCALLBACK_ROOTOBJECTCB_ONNOTIFY, a, b, c, d);
}

// ----------------------------------------------------------------------------

#endif // __ROOTOBJECTCALLBACK_H
