// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri May 16 23:15:13 2003]
// 
// File        : rootobject.cpp
// Class       : RootObject
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include <precomp.h>
#include "rootobject.h"


