// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:06:33 2003]
// 
// File        : rootobjcb.cpp
// Class       : RootObjectCallback
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include <precomp.h>
#include "rootobjcb.h"


