// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:06:33 2003]
// 
// File        : rootobjcbx.cpp
// Class       : RootObjectCallback
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------
#include "rootobjcbx.h"
#include "rootobjcbi.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS RootObjectCallbackX
START_DISPATCH;
  VCB(ROOTOBJECTCALLBACK_ROOTOBJECTCB_ONNOTIFY, rootobjectcb_onNotify);
END_DISPATCH;
#undef CBCLASS

