// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri May 16 23:15:13 2003]
// 
// File        : rootobjectx.h
// Class       : RootObject
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#ifndef __ROOTOBJECTX_H
#define __ROOTOBJECTX_H

#include "rootobject.h"

class RootObjectCallback;
class ScriptObject;



// ----------------------------------------------------------------------------

class RootObjectX : public RootObject {
  protected:
    RootObjectX() {}
  public:
    virtual const wchar_t *rootobject_getClassName()=0;
    virtual void rootobject_notify(const wchar_t *s, const wchar_t *t, int u, int v)=0;
    virtual ScriptObject *rootobject_getScriptObject()=0;
    virtual void rootobject_setScriptObject(ScriptObject *obj)=0;
    virtual void rootobject_addCB(RootObjectCallback *cb)=0;
  
  protected:
    RECVS_DISPATCH;
};

#endif // __ROOTOBJECTX_H
