//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gen_ml.rc
//
#define IDS_ENQUEUE_IN_WINAMP           0
#define IDS_LIBRARY_OPTIONS             1
#define IDS_ONLINE_MEDIA                2
#define IDC_ITV_CHANGEPASS              3
#define IDS_RATINGS_PASSWORD_MISSING    3
#define IDS_SERCURITY_ALERT             4
#define IDS_MUST_ENTER_PASSWORD         5
#define IDS_INTERNET_ACCESS             6
#define IDS_PASSWORD_NO_MATCH           7
#define IDS_INVALID_PASSWORD            8
#define IDS_PLAY_SELECTED               9
#define IDS_ENQUEUE_SELECTED            10
#define IDS_NO_CONFIG_PRESENT           11
#define IDS_ML_PLUGIN_INFO              12
#define IDS_BAD_ITEM                    13
#define IDS_ML_GHK_STR                  15
#define IDS_MEDIA_LIBRARY               16
#define IDS_ML_ALT_L_SHORTCUT           17
#define IDS_WINAMP_LIBRARY              18
#define IDS_ONLINE_SERVICES_NOT_PRESENT 19
#define IDS_ERROR_SWITCHING_TO_VIEW     20
#define IDS_CDDB_CONNECTING             22
#define IDS_CDDB_SENDING                23
#define IDS_CDDB_RECEIVING              24
#define IDS_CDDB_COMPLETE               25
#define IDS_TOGGLE_LIBRARY              26
#define IDS_UNINSTALL_PROMPT            27
#define IDS_UINSTALL_CONFIRMATION       28
#define IDS_DOWNLOADING                 29
#define IDS_WEBINFO_NAVIGATE_ERROR      30
#define IDS_WEBINFO_MESSAGEBOX_TITLE    31
#define IDS_LOADING_IN_PROGRESS         32
#define IDS_UNABLE_TO_APPLY_NEW_STYLE   33
#define IDS_TWEAK_ERROR                 34
#define IDS_ALWAYS                      35
#define IDS_PROCESS_ACTIVE              36
#define IDS_ANCESTOR_ACTIVE             37
#define IDS_WINDOW_FOCUSED              38
#define IDS_NEVER                       39
#define IDS_ALL                         40
#define IDS_SELECTED                    41
#define IDS_FOCUSED                     42
#define IDS_LEFT                        43
#define IDS_CENTER                      44
#define IDS_RIGHT                       45
#define IDS_DO_YOU_WANT_TO_SAVE_CHANGES_FIRST 46
#define IDS_CONFIRM_CLOSE               47
#define IDS_TREE_OPTIONS                48
#define IDS_FILE_ATTRIBUTES             49
#define IDS_FILETYPE_AUDIO              50
#define IDS_FVFT_VIDEO                  51
#define IDS_FILETYPE_VIDEO              51
#define IDS_FILETYPE_PLAYLIST           52
#define IDS_FILETYPE_UNKNOWN            53
#define IDS_FILEVIEW_COL_NAME           54
#define IDS_FILEVIEW_COL_TYPE           55
#define IDS_FILEVIEW_COL_SIZE           56
#define IDS_FILEVIEW_COL_MODIFIED       57
#define IDS_FILEVIEW_COL_CREATED        58
#define IDS_FILEVIEW_COL_EXTENSION      59
#define IDS_FILEVIEW_COL_ATTRIBUTES     60
#define IDS_FILEVIEW_COL_ARTIST         61
#define IDS_FILEVIEW_COL_ALBUM          62
#define IDS_FILEVIEW_COL_TITLE          63
#define IDS_FILEVIEW_COL_INMLDB         64
#define IDS_FILEVIEW_COL_GENRE          65
#define IDS_FILEVIEW_COL_YEAR           66
#define IDS_FILEVIEW_COL_LENGTH         67
#define IDS_FILEVIEW_COL_BITRATE        68
#define IDS_FILEVIEW_COL_TRACK          69
#define IDS_FILEVIEW_COL_DISC           70
#define IDS_FILEVIEW_COL_COMMENT        71
#define IDS_FILEVIEW_COL_PUBLISHER      72
#define IDS_FILEVIEW_COL_COMPOSER       73
#define IDS_FILEVIEW_COL_ALBUMARTIST    74
#define IDS_FILEVIEW_COL_ENTRYCOUNT     75
#define IDS_FILEVIEW_COL_TOTALLENGTH    76
#define IDS_KBPS                        80
#define IDS_APPEARANCE                  81
#define IDD_MAIN                        101
#define IDR_CONTEXTMENUS                103
#define IDR_MENU_FILEVIEW               104
#define ML_IDC_DRAGDROP                 107
#define IDB_TREEITEM_COLLAPSED          135
#define IDB_TREEITEM_NOCHILD            136
#define IDB_TREEITEM_EXPANDED           137
#define IDB_TREEITEM_DEFAULT            138
#define IDB_BITMAP1                     145
#define IDB_RATING                      145
#define IDB_SORTARROW                   146
#define IDB_SPLITARROW                  147
#define IDB_SPLITARROW_PRESSED          148
#define IDB_MENU_CHECKMARK              149
#define IDB_MENU_RADIOMARK              150
#define IDD_RATINGTWEAK                 151
#define IDB_MENU_EXPANDARROW            152
#define IDB_MENU_SCROLLARROW            153
#define IDB_MENU_SCROLLARROW_DISABLED   154
#define IDD_PREFS3                      157
#define IDD_FILEVIEW                    161
#define IDD_DIALOG2                     162
#define IDD_FILEVIEW_TOOLBAR            162
#define IDS_YES                         163
#define IDS_NO                          164
#define IDS_FILEVIEW_EMPTYFOLDER        165
#define IDS_FILEVIEWSTATUS_GROUPTEMPLATE 167
#define IDR_ACCELERATOR_GLOBAL          167
#define IDS_FILEVIEWSTATUS_SELECTEDGROUPTEMPLATE 168
#define IDR_ACCELERATOR_MAIN            168
#define IDR_ACCELERATOR_FILEVIEW        169
#define IDS_RESTART                     169
#define IDS_RESTART_MESSAGE             170
#define IDR_MENU1                       171
#define IDS_COL_NORMAL                  171
#define IDB_CLOUD_IS_IN                 172
#define IDS_COL_SELONLY                 172
#define IDB_CLOUD_PARTIAL               173
#define IDS_COL_PROP                    173
#define IDB_CLOUD_UNAVAIL               174
#define IDS_PLAY                        174
#define IDB_CLOUD_UPLOAD                175
#define IDS_ENQUEUE                     175
#define IDB_CLOUD_UPLOADING             176
#define IDS_NOT_LOADED                  176
#define IDB_TREEITEM_LABS               177
#define IDD_VIEW_EMPTY                  224
#define IDD_PREFSFR                     228
#define IDD_PREFS2                      229
#define IDD_MLPLUGINS                   254
#define IDD_PREFS_ITV_ASSIGNPASS        266
#define IDD_PREFS_ITV_GETPASS           267
#define IDD_PREFS4                      268
#define IDD_PREFS1                      269
#define IDC_LIST1                       1000
#define IDC_LIST2                       1001
#define IDC_BTN_LIB                     1003
#define IDC_VDELIM                      1014
#define IDC_COMBO1                      1032
#define IDC_CMB_TRACKWHEN               1033
#define IDC_COMBO2                      1033
#define IDC_CMB_TRACKWHAT               1034
#define IDC_CMB_CLICKWHAT               1036
#define IDC_CHECK1                      1052
#define IDC_CHK_SHOWEMPTY_HOT           1053
#define IDC_CHECK2                      1053
#define IDC_FF_SCROLLBARS               1053
#define IDC_WRITE_RATINGS               1053
#define IDC_CHK_SHOWEMPTY_ANIMATION     1054
#define IDC_FF_ALTERNATEITEMS           1054
#define IDC_ALTERNATEITEMS              1054
#define IDC_GROUP_BUTTONS               1054
#define IDC_CHK_SIZEDECREASE            1055
#define IDC_SKINNED_MENUS               1055
#define IDC_CHK_SIZEINCREASE            1056
#define IDC_GENO                        1056
#define IDC_BUTTON1                     1062
#define IDC_RATING_COLUMN               1062
#define IDC_BUTTON3                     1063
#define IDC_BUTTON4                     1064
#define IDC_BUTTON5                     1065
#define IDC_BUTTON2                     1066
#define IDC_PLPLAYLIST                  1069
#define IDC_VIEWPLAYMODE                1070
#define IDC_TAB1                        1079
#define IDC_GENLIB                      1121
#define IDC_GENCONF                     1122
#define IDB_FILETYPE_AUDIO_SMALL        1126
#define IDB_FILETYPE_AUDIO_LARGE        1127
#define IDB_FILETYPE_VIDEO_SMALL        1128
#define IDB_FILETYPE_VIDEO_LARGE        1129
#define IDB_FILETYPE_UNKNOWN_SMALL      1130
#define IDB_FILETYPE_UNKNOWN_LARGE      1131
#define IDB_FILETYPE_PLAYLIST_SMALL     1132
#define IDB_FILETYPE_PLAYLIST_LARGE     1133
#define IDB_FILEVIEW_LIST               1134
#define IDB_FILEVIEW_ICON               1135
#define IDB_FILEVIEW_DETAIL             1136
#define IDC_DEFS                        1210
#define IDC_CHECK_USEPLFONT             1211
#define IDC_PLUGINVERS                  1229
#define IDC_UNINST                      1252
#define IDC_CHECK_RATING0               1280
#define IDC_CHECK_RATING1               1281
#define IDC_CHECK_RATING2               1282
#define IDC_CHECK_RATING3               1283
#define IDC_CHECK_RATING4               1284
#define IDC_CHECK_PASSPROMPT            1285
#define IDC_EDIT_PASSWORD               1304
#define IDC_EDIT_PASSWORD_VERIFY        1305
#define IDC_GPASS                       1307
#define IDC_PL_SEND_TO                  1309
#define IDC_PMP_SEND_TO                 1310
#define IDC_CMB_ALIGNMENT               1311
#define IDC_CHK_SHOWEMPTY_NORMAL        1312
#define IDC_CHK_BLOCKCLICK              1313
#define IDC_CHK_BLOCKUNRATE             1314
#define IDC_SHOW_ICONS                  1314
#define IDC_CHK_BLOCKDRAG               1315
#define IDC_HIGHLIGHT_FULL_TREE_ITEM    1315
#define IDC_RCLICK_TO_SELECT            1316
#define IDC_CHK_SHOWINACTIVE_HOT        1316
#define IDC_SHOW_EJECT_ICONS            1317
#define IDC_ITEM_HEIGHT                 1318
#define IDC_GROUP_DRIVES                1319
#define IDC_PARENT_PODCASTS             1320
#define IDC_CD_DVD_ITEMS                1321
#define IDC_ML_TREE_OPTS                1322
#define IDC_STATIC_INFO                 1323
#define IDC_DOWNLOADS_ITEMS             1323
#define IDC_EDT_PATH                    1324
#define IDC_GROUP_DRIVES2               1324
#define IDC_TRANSFERS_ITEMS             1324
#define IDC_FOLDER_BROWSER              1325
#define IDC_LBL_ADDRESS                 1326
#define IDC_HDELIM                      1327
#define IDC_TRANSFERS_COMBO             1327
#define IDC_BTN_VIEW_ICON               1328
#define IDC_NO_VIEW                     1328
#define IDC_BTN_VIEW_LIST               1329
#define IDC_BTN_VIEW_DETAIL             1330
#define IDC_BTN_ARRANGEBY               1331
#define IDC_BTN_OPTIONS                 1332
#define IDM_LIBRARY_CONFIG              40050
#define ID_WINDOW_CLOSE                 40155
#define ID_GO_TO_VIEW_SEARCHBAR         40157
#define ID_SHOW_HELP                    40158
#define ID_DOSHITMENU_HELP              40159
#define IDM_LIBRARY_HELP                40161
#define ID_REFRESH_SEARCH               40165
#define ID_FILEVIEW_PLAYSELECTION       42001
#define ID_FILEVIEW_PLAYSELECTION_SHIFT 42002
#define ID_FILEVIEW_SELECT_ALL          42003
#define ID_FILEVIEW_SETMODE_ICON        42004
#define ID_FILEVIEW_SETMODE_LIST        42005
#define ID_FILEVIEW_SETMODE_DETAIL      42006
#define ID_FILEVIEW_REFRESH             42007
#define IDM_FILEVIEW_HIDEEXTENSION      42008
#define IDM_FILEVIEW_IGNOREHIDDEN       42009
#define IDM_FILEVIEW_SHOWAUDIO          42010
#define IDM_FILEVIEW_SHOWVIDEO          42011
#define IDM_FILEVIEW_SHOWPLAYLIST       42012
#define IDM_FILEVIEW_SHOWUNKNOWN        42013
#define IDM_FILEVIEW_SORTASCENDING      42014
#define ID_SELECTCOLUMNS_CUSTOMIZE      42015
#define ID_SHOW_RATINGTWEAK             42016
#define ID_TOGGLE_LIBRARY               42017
#define ID_NEW_PLAYLIST                 42018
#define IDS_NULLSOFT_ML_STR             65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         40167
#define _APS_NEXT_CONTROL_VALUE         1329
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
