//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gen_ff.rc
//
#define IDS_SEND_TO                     1
#define IDS_NO_THEME_AVAILABLE          2
#define IDS_COLOR_THEMES                3
#define IDS_CURRENT_SKIN                4
#define IDS_NO_SKIN_LOADED              5
#define IDS_MODERN_SKIN_SUPPORT_CLASSIC 6
#define IDS_MODERN_SKIN_SUPPORT         7
#define IDS_CUSTOM_X_PERCENT            8
#define IDS_CUSTOM                      9
#define IDS_WINDOW_SETTINGS             10
#define IDS_SCALE_X_PERCENT             11
#define IDS_OPACITY_X_PERCENT           12
#define IDS_GHK_SHOW_NOTIFICATION       13
#define IDS_MODERN_SKINS                14
#define IDS_GENERAL                     15
#define IDS_ALPHA_BLENDING              16
#define IDS_FONT_RENDERING              17
#define IDS_ERROR_WHILE_LOADING_SKIN_WINDOW 18
#define IDS_NO_OPTIONS_AVAILABLE_FOR_THIS_SKIN 19
#define IDS_AUTO_UNICODE_LATIN1_ASCII   20
#define IDS_FONT                        21
#define IDS_MAPPING                     22
#define IDS_SCALE                       23
#define IDS_TYPE                        24
#define IDS_THIS_SKIN                   25
#define IDS_ALL_SKINS                   26
#define IDS_FASTER                      27
#define IDS_FAST                        28
#define IDS_AVERAGE                     29
#define IDS_SLOW                        30
#define IDS_SLOWER                      31
#define IDS_FAILED_TO_DETECT_OPTIMAL_RESOLUTION 32
#define IDS_AUTO_DETECTING              33
#define IDS_PREPARING_AUTO_DETECTION    34
#define IDS_AUTO_DETECTION_SUCCESSFUL   35
#define IDS_ACCEPT                      36
#define IDS_N_A                         37
#define IDS_TIMERS_RESOLUTION           38
#define IDS_TEXT_SCROLL_SPEED           39
#define IDS_CROSSFADER_ONLY_UNDER_OUT_DS 40
#define IDS_NOT_SUPPORTED               41
#define IDS_PLAYLIST_EDITOR             42
#define IDS_VIDEO                       43
#define IDS_MONO                        44
#define IDS_STEREO                      45
#define IDS_X_CHANNELS                  46
#define IDS_BY_SPACE                    47
#define IDS_COULD_NOT_FIND_WINAMP       48
#define IDS_ERROR                       49
#define IDS_WINAMP_NOT_FOUND            50
#define IDS_VISUALIZATIONS              51
#define IDS_STRING52                    52
#define IDS_MEDIA_LIBRARY               52
#define IDS_NO_SET                      53
#define IDS_SLOT_X_X                    54
#define IDS_COLOR_EDITOR                55
#define IDS_SKIN_SETTINGS               56
#define IDS_WEB_BROWSER                 57
#define IDS_STRING58                    58
#define IDS_ALBUM_ART                   58
#define IDS_NO_VISUALISATION            59
#define IDS_SPECTRUM_ANALYZER           60
#define IDS_STRING61                    61
#define IDS_OSCILLOSCOPE                61
#define IDS_SKIN_LOAD_FORMAT_OLD        62
#define IDS_SKIN_LOAD_FORMAT_TOO_RECENT 63
#define IDS_SKIN_LOAD_WARNING           64
#define IDS_SKIN_LOAD_NOT_SUPPORTED     65
#define IDS_NO_SKIN_LOADED_             66
#define IDS_XUITHEME_LOAD               67
#define IDS_XUITHEME_SAVE               68
#define IDS_MS                          69
#define IDS_KHZ                         70
#define IDS_STRING71                    71
#define IDS_KBPS                        71
#define IDS_USELOCK                     72
#define IDS_ALLLOCKED                   73
#define IDS_OPAQUE_FOCUS                74
#define IDS_OPAQUE_HOVER                75
#define IDS_NO_OPACITY                  76
#define IDS_LOADING                     77
#define IDB_PLEDIT_TAB_NORMAL           110
#define IDB_PLEDIT_TAB_HILITED          111
#define IDB_PLEDIT_TAB_SELECTED         112
#define IDB_VIDEO_TAB_NORMAL            120
#define IDB_VIDEO_TAB_HILITED           121
#define IDB_VIDEO_TAB_SELECTED          122
#define IDD_ABOUT                       124
#define IDR_SONGINFO                    128
#define IDB_MB_TAB_NORMAL               130
#define IDB_MB_TAB_HILITED              131
#define IDB_MB_TAB_SELECTED             132
#define IDB_ML_TAB_NORMAL               133
#define IDD_DIALOG1                     133
#define IDB_ML_TAB_HILITED              134
#define IDD_FONTMAPPER                  134
#define IDB_ML_TAB_SELECTED             135
#define IDB_VIS_TAB_NORMAL              136
#define IDB_VIS_TAB_HILITED             137
#define IDB_VIS_TAB_SELECTED            138
#define IDD_MEDIA_DOWNLOADER            141
#define IDD_PREFS_WINDOWS               142
#define IDC_CHECK_DESKTOPALPHA          1002
#define IDC_STATIC_DA1                  1003
#define IDC_STATIC_DA3                  1005
#define IDC_TAB1                        1006
#define IDC_LIST1                       1007
#define IDC_BUTTON_SETTHEME             1008
#define IDC_VERSTR                      1009
#define IDC_CHECK_LINKALPHA             1011
#define IDC_CHECK_LINKRATIO             1012
#define IDC_SLIDER_TIMERRESOLUTION      1013
#define IDC_STATIC_TIMERRES             1014
#define IDC_CHECK_TOOLTIPS              1015
#define IDC_CHECK_DOCKING               1016
#define IDC_EDIT_DOCKDISTANCE           1017
#define IDC_BUTTON_SKINSPECIFIC         1018
#define IDC_CHECK_DOCKING2              1018
#define IDC_SLIDER_TICKERSPEED          1019
#define IDC_STATIC_TICKER               1020
#define IDC_BUTTON_AUTOTIMERRES         1021
#define IDC_EDIT_DOCKDISTANCE2          1022
#define IDC_TXT                         1023
#define IDC_EDIT_INCREMENT              1023
#define IDC_SLIDER_CUSTOMSCALE          1025
#define IDC_STATIC_SCALE                1026
#define IDC_EDIT_SHOWTIME               1027
#define IDC_EDIT_HIDETIME               1028
#define IDC_RECT                        1186
#define IDR_CONTROLMENU                 1281
#define IDD_PREFS_THEMES                1282
#define IDC_CHECK_ALLOWBITMAPFONTS      1283
#define IDD_PREFS                       1284
#define IDC_CHECK_ALTFONTS              1284
#define IDD_AUTOTIMERRES                1285
#define IDD_CUSTOMSCALE                 1286
#define IDC_COMBO_TTFOVERRIDE           1286
#define IDD_PREFS_FONTS                 1287
#define IDC_STATIC_TTFOVERRIDE          1287
#define IDC_SLIDER_SCALETTFOVERRIDE     1288
#define IDC_STATIC_TTFSCALE             1289
#define IDD_CUSTOMALPHA                 1289
#define IDC_CHECK_FREETYPETTF           1290
#define IDD_PREFS_SKIN                  1290
#define IDC_COMBO_CHARMAP               1291
#define IDC_STATIC_FREETYPE             1292
#define IDC_STATIC_DECREASESIZE         1293
#define IDC_STATIC_INCREASESIZE         1294
#define IDC_NO_7BIT_OVERRIDE            1295
#define IDC_CHECK_NO_ALT_7BIT_OVERRIDE  1296
#define IDC_STATIC_CHARMAP              1297
#define IDC_STATIC_ALTFONTS             1298
#define IDC_COMBO_DEFAULTFONT           1299
#define IDC_SLIDER_SCALEDEFAULTFONT     1300
#define IDC_CHECK_LINKALLALPHA          1301
#define IDC_STATIC_DECREASESIZE2        1301
#define IDC_CHECK_LINKALLRATIO          1302
#define IDC_STATIC_SCALEDEFAULTFONT     1302
#define IDC_STATIC_INCREASESIZE2        1303
#define IDC_STATIC_SCALEDEFAULTFONT2    1305
#define IDC_RADIO_USELOCK               1306
#define IDC_RADIO_ALLLOCKED             1307
#define IDC_SLIDER_CUSTOMALPHA          1309
#define IDC_STATIC_ALPHA                1311
#define IDC_SLIDER_HOLD                 1313
#define IDC_STATIC_TRANSP               1314
#define IDC_STATIC_OPAQUE               1315
#define IDC_SLIDER_FADEIN               1316
#define IDC_SLIDER_FADEOUT              1317
#define IDC_STATIC_SCALE11              1318
#define IDC_STATIC_HOLD                 1319
#define IDC_STATIC_FADEIN               1320
#define IDC_STATIC_FADEOUT              1321
#define IDC_STATIC_SCALE301             1322
#define IDC_EDIT_EXTEND                 1323
#define IDC_STATIC_EXTEND               1324
#define IDC_STATIC_GROUP                1326
#define IDC_CHECK_USEFONTMAPPER         1330
#define IDC_BUTTON_FONTMAPPER           1331
#define IDC_LIST_MAPPINGS               1332
#define IDC_RADIO_THISSKIN              1333
#define IDC_RADIO_ALLSKINS              1334
#define IDC_BUTTON_NEW                  1335
#define IDC_BUTTON_DEL                  1336
#define IDC_COMBO_SKINFONTS             1337
#define IDC_COMBO_FONTS                 1338
#define IDC_SLIDER_SCALE                1339
#define IDC_BUTTON_SET                  1340
#define IDC_STATIC_EMPTY                1344
#define IDC_STATIC_OPACITY              1345
#define IDC_STATIC_AUTOON               1346
#define IDC_STATIC_AUTOONTXT            1347
#define IDC_STATIC_FADEIN2              1348
#define IDC_STATIC_FADEOUT2             1349
#define IDC_STATIC_HOLD2                1350
#define IDC_STATIC_EXTENDBOX            1351
#define IDC_URL                         1352
#define IDC_PROGRESS                    1353
#define IDC_DOWNLOADTO                  1354
#define IDC_SPIN_EXTEND                 1356
#define IDC_SPIN_DOCKDISTANCE           1357
#define IDC_SPIN_DOCKDISTANCE2          1358
#define IDC_COMBO_SCALE                 1358
#define IDC_SPIN_INCREMENT              1359
#define IDC_COMBO_OPACITY               1359
#define IDC_SPIN_SHOWTIME               1360
#define IDC_SPIN_HIDETIME               1361
#define IDD_PREFS_GENERAL               1362
#define WINAMP_EDIT_ID3                 40188
#define WINAMP_JUMP                     40193
#define WINAMP_JUMPFILE                 40194
#define ID_CONTROLMENU_OPACITY_10       42202
#define ID_CONTROLMENU_OPACITY_20       42203
#define ID_CONTROLMENU_OPACITY_30       42204
#define ID_CONTROLMENU_OPACITY_40       42205
#define ID_CONTROLMENU_OPACITY_50       42206
#define ID_CONTROLMENU_OPACITY_60       42207
#define ID_CONTROLMENU_OPACITY_70       42208
#define ID_CONTROLMENU_OPACITY_80       42209
#define ID_CONTROLMENU_OPACITY_90       42210
#define ID_CONTROLMENU_OPACITY_100      42211
#define ID_CONTROLMENU_SCALING_25       42213
#define ID_CONTROLMENU_SCALING_50       42214
#define ID_CONTROLMENU_SCALING_75       42215
#define ID_CONTROLMENU_SCALING_100      42216
#define ID_CONTROLMENU_SCALING_200      42217
#define ID_CONTROLMENU_SCALING_250      42218
#define ID_CONTROLMENU_SCALING_300      42219
#define ID_CONTROLMENU_SCALING_150      42222
#define ID_CONTROLMENU_SCALING_LOCKED   42223
#define ID_CONTROLMENU_SCALING_CUSTOM   42224
#define ID_CONTROLMENU_SCALING_FOLLOWDOUBLESIZE 42225
#define ID_CONTROLMENU_OPACITY_AUTO100  42226
#define ID_CONTROLMENU_OPACITY_AUTO100_HOVER 42226
#define ID_CONTROLMENU_OPACITY_CUSTOM   42227
#define ID_CONTROLMENU_OPACITY_AUTO100_FOCUS 42228
#define ID_CONTROLMENU_TOOLBAR_TOP      42229
#define ID_CONTROLMENU_TOOLBAR_RIGHT    42231
#define ID_CONTROLMENU_TOOLBAR_BOTTOM   42232
#define ID_CONTROLMENU_TOOLBAR_DISABLED 42233
#define ID_CONTROLMENU_TOOLBAR_ALWAYSONTOP 42234
#define ID_CONTROLMENU_TOOLBAR_AUTOHIDE 42235
#define ID_CONTROLMENU_TOOLBAR_LEFT     42236
#define ID_CONTROLMENU_TOOLBAR_AUTODOCKONDRAG 42237
#define ID_CONTROLMENU_SCALING_125      42238
#define IDS_NULLSOFT_MODERN_SKINS       65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         42238
#define _APS_NEXT_CONTROL_VALUE         1359
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
