//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gen_hotkeys.rc
//
#define IDS_GHK_TITLE_STR               0
#define IDS_GHK_HOTKEY_REG_FAILED       1
#define IDC_CANCEL                      2
#define IDS_GHK_HOTKEY_REG_FAILED_MORE  2
#define IDS_GHK_ABOUT_TEXT              3
#define IDS_GHK_HOTKEY_COLUMN           4
#define IDS_GHK_ACTION_COLUMN           5
#define IDS_GHK_ACTION_NOT_FOUND        6
#define IDS_GHK_WINKEY_STR              7
#define IDS_BROWSER_BACK                8
#define IDS_BROWSER_FORWARD             9
#define IDS_BROWSER_REFRESH             10
#define IDS_BROWSER_STOP                11
#define IDS_BROWSER_SEARCH              12
#define IDS_BROWSER_FAVOURITES          13
#define IDS_BROWSER_HOME                14
#define IDS_VOLUME_MUTE                 15
#define IDS_VOLUME_DOWN                 16
#define IDS_VOLUME_UP                   17
#define IDS_NEXT_TRACK                  18
#define IDS_PREVIOUS_TRACK              19
#define IDS_STOP                        20
#define IDS_PLAY_PAUSE                  21
#define IDS_LAUNCH_MAIL                 22
#define IDS_LAUNCH_MEDIA_SELECT         23
#define IDS_LAUCH_APP1                  24
#define IDS_LAUCH_APP2                  25
#define IDS_SLEEP                       26
#define IDS_PLAYBACK__PLAY              32
#define IDS_PLAYBACK__PAUSE             33
#define IDS_PLAYBACK__STOP              34
#define IDS_PLAYBACK__PREVIOUS_IN_PLAYLIST 35
#define IDS_PLAYBACK__NEXT_IN_PLAYLIST  36
#define IDS_PLAYBACK__VOLUME_UP         37
#define IDS_PLAYBACK__VOLUME_DOWN       38
#define IDS_PLAYBACK__FORWARD           39
#define IDS_PLAYBACK__REWIND            40
#define IDS_PLAYBACK__REPEAT_ON         41
#define IDS_PLAYBACK__REPEAT_OFF        42
#define IDS_UI__TOGGLE_EQ               43
#define IDS_UI__TOGGLE_PLAYLIST         44
#define IDS_UI__TOGGLE_AOT              45
#define IDS_UI__ABOUT                   46
#define IDS_PLAYBACK__JUMP_TO_BOX       47
#define IDS_PLAYBACK__OPEN_FILE_DIALOG  48
#define IDS_PLAYBACK__OPEN_LOC_DIALOG   49
#define IDS_PLAYBACK__OPEN_FOLDER_DIALOG 50
#define IDS_GENERAL__QUIT               51
#define IDS_UI__PREFERENCES             52
#define IDS_GENERAL__COPY_TITLE         53
#define IDS_GENERAL__COPY_FILE_PATH     54
#define IDS_PLAYBACK__PLAY_PAUSE        55
#define IDS_PLAYBACK__TOGGLE_REPEAT     56
#define IDS_PLAYBACK__TOGGLE_SHUFFLE    57
#define IDS_UI__TOGGLE_WINSHADE         58
#define IDS_UI__TOGGLE_PLAYLIST_WINSHADE 59
#define IDS_UI__TOGGLE_DOUBLESIZE       60
#define IDS_UI__TOGGLE_MAIN_WINDOW      61
#define IDS_UI__TOGGLE_MINIBROWSER      62
#define IDS_VIS__PREFERENCES            63
#define IDS_VIS__PLUGIN_PREFERENCES     64
#define IDS_VIS_TOGGLE_VIS_ON_OFF       65
#define IDS_UI__SELECT_SKIN             66
#define IDS_PLAYBACK__STOP_WITH_FADEOUT 67
#define IDS_PLAYBACK__STOP_AFTER_CURRENT 68
#define IDS_PLAYBACK__START_OF_LIST     69
#define IDS_PLAYBACK__END_OF_LIST       70
#define IDS_UI__BRING_TO_FRONT_OR_HIDE  71
#define IDS_RATING__5_STARS             72
#define IDS_RATING__4_STARS             73
#define IDS_RATING__3_STARS             74
#define IDS_RATING__2_STARS             75
#define IDS_RATING__1_STAR              76
#define IDS_RATING__NO_RATING           77
#define IDS_GENERAL__COPY_TITLEW        78
#define IDS_GENERAL__COPY_FILE_PATHW    79
#define IDS_RATING__INC                 80
#define IDS_RATING__DEC                 81
#define IDS_PAUSE                       82
#define IDS_VIS_NEXT_PRESET             83
#define IDS_VIS_PREV_PRESET             84
#define IDS_VIS_RAND_PRESET             85
#define IDS_VIS_FULL_SCREEN             86
#define IDS_VIS_CONFIG                  87
#define IDS_PLAYBACK__MANUAL_ADVANCE    87
#define IDS_VIS_MENU                    88
#define IDS_GENERAL_FFOD                89
#define IDS_PLAYBACK_EDIT_ID3           90
#define IDD_CONFIG                      101
#define IDB_LOGO                        103
#define IDB_LVSTATE                     104
#define IDC_ENABLED                     1006
#define IDC_ENABLED_WM_APPCOMMAND       1007
#define IDC_HOTKEY                      1012
#define IDC_HKLIST                      1017
#define IDC_COMBO                       1018
#define IDC_SAVE                        1019
#define IDC_ADD                         1020
#define IDC_REMOVE                      1021
#define IDC_DEFAULT                     1022
#define IDS_NULLSOFT_GLOBAL_HOTKEYS     65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        91
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
