//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by script1.rc
//
#define IDS_NULLSOFT_MPEG_AUDIO_DECODER_OLD 0
#define IDS_CANNOT_WRITE_STREAMS_TO_DISK 1
#define IDS_BUFFER_X                    2
#define IDC_ID3_REMOVE                  3
#define IDC_ID3V1_REMOVE                3
#define IDC_REVERTTAG                   3
#define IDS_ERROR_SYNCING_TO_STREAM     3
#define IDC_ID3V2_REMOVE                4
#define IDS_CONNECTING                  4
#define IDC_ID3V1_SAVE                  5
#define IDS_NO_VALID_MULTICONNECT_URL   5
#define IDC_ID3_REMOVE_ALL              6
#define IDS_REDIRECT_LIMIT_EXCEEDED     6
#define IDC_ID3V1_TO_V2                 7
#define IDS_READING_ID3                 7
#define IDC_ID3V2_SAVE                  8
#define IDS_STREAM_TERMINATED           8
#define IDC_ID3V2_TO_V1                 9
#define IDS_STREAM_TEMPORARILY_INTERRUPTED 9
#define IDC_ID3V2_STOP                  10
#define IDS_NETWORK_RECEIVED_X_BYTES    16
#define IDS_SERVER                      17
#define IDS_CONTENT_TYPE                18
#define IDS_ULTRAVOX_SYNC               19
#define IDS_ULTRAVOX_DATA_MESSAGE       20
#define IDS_ULTRAVOX_SID_AVGBR_MAXBR    21
#define IDS_METADATA_RECEIVED           22
#define IDS_METADATA_INTERVAL           23
#define IDS_ID3v2_TAG                   24
#define IDS_VBR_LEADING_FRAME           25
#define IDS_STREAM_NAME                 26
#define IDS_CURRENT_TITLE               27
#define IDS_CONTENT_LENGTH              28
#define IDS_SAVING_TO                   29
#define IDS_CUSTOM                      32
#define IDS_MONO                        33
#define IDS_STEREO                      34
#define IDS_3_CHANNEL                   35
#define IDS_4_CHANNEL                   36
#define IDS_SURROUND                    37
#define IDS_5_1                         38
#define IDS_7_1                         39
#define IDS_ERROR                       40
#define IDS_NONE                        41
#define IDS_50_15_MICROSEC              42
#define IDS_INVALID                     43
#define IDS_JOINT_STEREO                44
#define IDS_2_CHANNEL                   45
#define IDS_PAYLOAD_SIZE                46
#define IDS_FORMAT_AAC                  47
#define IDS_MPEG2_HE_AAC_IS             48
#define IDS_MPEG4_HE_AAC_IS             49
#define IDS_SAMPLE_RATE_OUTPUT          50
#define IDS_SAMPLE_RATE                 51
#define IDS_SBR_PRESENT                 52
#define IDS_SBR_NOT_PRESENT             53
#define IDS_CHANNELS_OUTPUT             54
#define IDS_CHANNELS                    55
#define IDS_MODE_MONO                   56
#define IDS_MODE_STEREO                 57
#define IDS_MODE_PARAMETRIC_STEREO      58
#define IDS_MODE_DUAL_CHANNEL           59
#define IDS_MODE_4_CHANNEL_2_CPE        60
#define IDS_MODE_4_CHANNEL_MPEG         61
#define IDS_MODE_5_CHANNEL              62
#define IDS_MODE_5_1                    63
#define IDS_MODE_6_1                    64
#define IDS_MODE_7_1                    65
#define IDS_BITRATE                     66
#define IDS_AVERAGE_BITRATE             67
#define IDS_HEADER_FOUND_AT_X_BYTES     68
#define IDS_LENGTH_X_SECONDS            69
#define IDS_PROFILE                     70
#define IDS_YES                         71
#define IDS_NO                          72
#define IDS_ENC_DELAY_ZERO_PADDING      73
#define IDS_S_LAYER_X                   74
#define IDS_X_KBIT                      75
#define IDS_X_KBIT_APPROX               76
#define IDS_X_KBIT_VBR                  77
#define IDS_X_HZ_S                      78
#define IDS_COPYRIGHTED                 79
#define IDS_ORIGINAL                    80
#define IDS_EMPHASIS                    81
#define IDS_EXT_MP3_SURROUND            82
#define IDS_MP3_HAS_BEEN_MODIFIED_NOT_ALL_MAY_BE_CORRECT 83
#define IDS_UPDATING_FILE               84
#define IDS_CANNOT_MODIFY_TAG_READ_ONLY 85
#define IDS_CANNOT_INSERT_ID3v2_TAG_DRIVE_FULL 86
#define IDS_CANNOT_INSERT_ID3v2_TAG_STOP_PLAYBACK 87
#define IDS_CANNOT_INSERT_ID3v2_TAG_READ_ONLY 88
#define IDS_UPDATING_FILE_REMOVING_TAG  89
#define IDS_CANNOT_REMOVE_ID3v2_TAG_DRIVE_FULL 90
#define IDS_CANNOT_REMOVE_ID3v2_TAG_STOP_TRY_AGAIN 91
#define IDS_CANNOT_REMOVE_ID3v2_TAG_READ_ONLY 92
#define IDS_CANNOT_WRITE_ID3v1_TAG      93
#define IDS_CANNOT_REMOVE_ID3v1_TAG     94
#define IDS_MPEG_AUDIO_FILES            95
#define IDS_MPEG_AUDIO_DECODER_SETTINGS 96
#define IDS_LATIN_1                     97
#define IDS_SYSTEM_LANGUAGE             98
#define IDS_UNICODE_UTF_16              99
#define IDS_SELECT_DIRECTORY_TO_SAVE_TO 100
#define ID_YES                          101
#define IDD_PREFS                       103
#define IDD_OUTPUT                      104
#define IDD_STREAM                      115
#define IDD_HTTP                        177
#define IDD_TAGOPTS                     179
#define IDD_HTTPAUTH                    182
#define IDD_INFO_ID3V1                  186
#define IDD_INFO_ID3V2                  187
#define IDD_INFO_LYRICS3                188
#define IDS_X_KBIT_ABR                  189
#define IDD_INFO_APEV2                  189
#define IDD_ADVANCED_TAGGING            190
#define IDS_NAME                        191
#define IDS_VALUE                       192
#define IDS_APEV2_RETAIN_HEADER         193
#define IDS_APEV2_ADD_HEADER            194
#define IDS_APEV2_REMOVE_HEADER         195
#define IDS_ERROR_SAVING_METADATA       196
#define IDS_METADATA_ERROR_READONLY     197
#define IDS_METADATA_ERROR_OPENING_FILE 198
#define IDS_METADATA_ERROR_APEV2        199
#define IDS_METADATA_ERROR_LYRICS3      200
#define IDS_METADATA_ERROR_ID3V1        201
#define IDS_METADATA_ERROR_ID3V2        202
#define IDS_METADATA_ERROR_UNSPECIFIED  203
#define IDS_TIMED_OUT                   204
#define IDS_FAMILY_STRING_MP3           205
#define IDS_FAMILY_STRING_MP2           206
#define IDS_FAMILY_STRING_MP1           207
#define IDS_FAMILY_STRING_MPEG2_AAC     208
#define IDS_FAMILY_STRING_DOLBY         209
#define IDS_ABOUT_STRING                210
#define IDS_ABOUT_TEXT                  210
#define IDS_LENGTH_X_PART_SECONDS       211
#define IDC_FASTL3EQ                    1000
#define IDC_BUFFERS_NUMBUFS             1001
#define IDC_FASTL12EQ                   1002
#define IDC_ID3V1                       1003
#define IDC_ID3V2                       1004
#define IDC_16BIT                       1005
#define IDC_PREBUFSLIDER                1011
#define IDC_PREBUFSLIDER2               1012
#define IDC_STEREO                      1046
#define IDC_REVSTEREO                   1048
#define IDC_FULLRATE                    1049
#define IDC_HALFRATE                    1050
#define IDC_QRATE                       1051
#define IDC_PREFS_PRIORITY_DECODE       1076
#define IDC_ID3_TITLE                   1078
#define IDC_ID3_ARTIST                  1079
#define IDC_ID3_ALBUM                   1080
#define IDC_ID3_COMMENT                 1081
#define IDC_ID3_YEAR                    1082
#define IDC_ID3_GENRE                   1083
#define IDC_ID3V2_TITLE                 1086
#define IDC_ID3V2_ARTIST                1087
#define IDC_ID3V2_ALBUM                 1088
#define IDC_ID3V2_YEAR                  1089
#define IDC_ID3V2_GENRE                 1090
#define IDC_ID3V2_COMMENT               1091
#define IDC_ID3V2_COMPOSER              1092
#define IDC_ID3V2_MARTIST               1093
#define IDC_ID3V2_RECORD                1094
#define IDC_ID3V2_URL                   1095
#define IDC_ID3V2_ENCODER               1096
#define IDC_ID3V2_TRACK                 1097
#define IDC_ID3V11_TRACK                1098
#define IDC_BPM                         1098
#define IDC_ID3V2_BPM                   1098
#define IDC_ID3V2_ALBUM_ARTIST          1099
#define IDC_ID3V2_ENCODER2              1100
#define IDC_ID3V2_DISC                  1100
#define IDC_ID3V2_ENCODER3              1101
#define IDC_ID3V2_PUBLISHER             1101
#define IDC_RADIO1                      1106
#define IDC_RADIO2                      1107
#define IDC_CHECK1                      1108
#define IDC_STATUS                      1109
#define IDC_SC_ARTWORK                  1109
#define IDC_CHECK2                      1110
#define IDC_URL                         1111
#define IDC_BUTTON2                     1112
#define IDC_ID3FORMAT                   1127
#define IDC_NORMFORMAT                  1128
#define IDC_BUFMAX                      1136
#define IDC_CHECK3                      1138
#define IDC_ID3V2_STATUS_TEXT           1139
#define IDC_EASTER                      1143
#define IDC_USEID3                      1145
#define IDC_EDIT1                       1146
#define IDC_BUTTON1                     1147
#define IDC_TRACK_GAIN                  1147
#define IDC_REALM                       1148
#define IDC_CHECK5                      1150
#define IDC_READ_LYRICS3                1150
#define IDC_WRITE_LOCAL                 1151
#define IDC_READ_APEV2                  1151
#define IDC_WRITE_UTF16                 1152
#define IDC_WRITE_LATIN                 1153
#define IDC_READ_LATIN                  1154
#define IDC_READ_LOCAL                  1155
#define IDC_WRITE_ID3V1                 1156
#define IDC_CHECK7                      1157
#define IDC_WRITE_ID3V2                 1157
#define IDC_READ_ID3V1                  1158
#define IDC_READ_ID3V2                  1159
#define IDC_24BIT                       1160
#define IDC_WRITE_APEV2                 1160
#define IDC_CREATE_ID3V1                1160
#define IDC_SURROUND                    1161
#define IDC_EDIT_REPLAYGAIN             1162
#define IDC_CREATE_ID3V2                1162
#define IDC_ALBUM_GAIN                  1165
#define IDC_COMBO1                      1168
#define IDC_COMBO2                      1169
#define IDC_LYRICS3_TITLE               1169
#define IDC_LYRICS3_ARTIST              1170
#define IDC_LYRICS3_ALBUM               1171
#define IDC_LYRICS3V2                   1172
#define IDC_LYRICS3                     1172
#define IDC_APEV2                       1173
#define IDC_APELIST                     1177
#define IDC_APE_LIST                    1177
#define IDC_APE_KEY                     1178
#define IDC_DELETE_ALL                  1179
#define IDC_APE_VALUE                   1180
#define IDC_APE_ADD                     1181
#define IDC_APE_DELETE                  1182
#define IDC_CREATE_APEV2                1183
#define IDC_STATIC_APEV2_HEADER         1184
#define IDC_APEV2_HEADER_OPTIONS        1185
#define IDC_RATING_EMAIL                1186
#define IDC_RATING_EMAIL_RESET          1187
#define IDS_NULLSOFT_MPEG_AUDIO_DECODER 65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1188
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
