//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by setup.rc
//
#define IDD_SETUP                       101
#define IDB_CHECKBOX                    101
#define IDD_SETUP_PAGE_LANG1            102
#define IDD_SETUP_PAGE_ASSOC            102
#define IDD_SETUP_PAGE_CONNECT          103
#define IDD_SETUP_PAGE_SKIN             104
#define IDD_ABOUT                       105
#define IDB_HEADERSTRIP                 106
#define IDB_HEADER_STRIP                106
#define IDD_SETUP_PAGE_LANG             106
#define IDD_SETUP_PAGE_FEEDBACK         107
#define IDB_ABOUT                       108
#define IDD_SETUP_PAGE_ERROR            108
#define IDD_SETUPSTATUS                 109
#define IDB_NAVIGATION_STRIP            110
#define IDB_NAVITEM_STRIP               111
#define IDB_PREVIEW_CLASSIC             112
#define IDR_ACCEL_SETUP                 112
#define IDB_PREVIEW_NO                  113
#define IDD_SETUP_PAGE_ASSOC_WIN8       114
#define IDR_SETUPMENU                   191
#define IDC_CB_CONNECT                  1000
#define IDC_LBL_MESSAGE                 1000
#define IDC_BTN_NEXT                    1001
#define IDC_EDT_SERVER                  1001
#define IDC_VER_TEXT                    1001
#define IDC_BTN_BACK                    1002
#define IDC_CHK_PORT80                  1002
#define IDC_LB_NAVIGATION               1003
#define IDC_EDT_EMAIL                   1003
#define IDC_FRAME                       1004
#define IDC_GRP_PROXY                   1004
#define IDC_CHK_ANNOUNCEMENTS           1004
#define IDC_EDT_TEST                    1005
#define IDC_LBL_SERVER                  1005
#define IDC_BTN_TEST_ME                 1006
#define IDC_TREE_TYPES                  1006
#define IDC_LBL_COUNTRY                 1006
#define IDC_HEADER                      1007
#define IDC_LBL_HEADER                  1007
#define IDC_LBL_GENDER                  1008
#define IDC_LBL_EMAIL                   1011
#define IDC_EDT_COUNTRY                 1012
#define IDC_CHK_STATISTICS              1013
#define IDC_CHK_FEEDBACK                1014
#define IDC_GRP_FEEDBACK                1015
#define IDC_LB_LANG                     1016
#define IDC_CB_GENDER                   1016
#define IDC_LB_SKIN                     1017
#define IDC_LBL_STATUS                  1017
#define IDC_EDT_INFO                    1018
#define IDC_PROGRESS                    1018
#define IDC_PIC_PREVIEW                 1020
#define IDC_LBL_CAPTION                 1021
#define IDC_CHK_AGENT                   1021
#define IDC_EDT_NAME                    1022
#define IDC_LBL_AGENT_DESC              1022
#define IDC_EDT_TYPE                    1023
#define IDC_CHK_EXPLORER_MENU           1023
#define IDC_LBL_NAME                    1024
#define IDC_BTN_SKIP                    1024
#define IDC_LBL_TYPE                    1025
#define IDC_GRP_PREVIEW                 1026
#define IDC_LBL_VERSION                 1027
#define IDC_EDT_VERSION                 1028
#define IDC_LBL_TYPE3                   1029
#define IDC_LBL_AUTHOR                  1029
#define IDC_EDT_AUTHOR                  1030
#define IDC_PIC_ABOUT                   1032
#define IDC_BTN_MOREINFO                1033
#define IDC_CHK_CD                      1034
#define IDS_SKIN_CURRENT                2000
#define IDS_SKIN_PROMO1                 2001
#define IDS_SKIN_PROMO2                 2002
#define IDS_PAGE_SKIN                   2003
#define IDS_PAGE_LANGUAGE               2004
#define IDS_PAGE_CONNECTIVITY           2005
#define IDS_SAVE_CHANGES_BEFORE_EXIT    2006
#define IDS_UNKNOWN                     2007
#define IDS_CHANGES_NOT_SAVED           2008
#define IDS_MODERN                      2009
#define IDS_CLASSIC                     2010
#define IDS_QUIT_OK                     2011
#define IDS_PAGE_ASSOCIATIONS           2012
#define IDS_FILETYPE_VIDEO              2013
#define IDS_FILETYPE_AUDIO              2014
#define IDS_FILETYPE_UNKNOWN            2015
#define IDS_FILETYPE_PLAYLIST           2016
#define IDS_PAGE_FEEDBACK               2017
#define IDS_GENDER_MALE                 2018
#define IDS_GENDER_FEMALE               2019
#define IDS_GENDER_UNKNOWN              2020
#define IDS_REGISTER_CDPLAYER           2021
#define IDS_STATUS_SAVING               2022
#define IDS_STATUS_JOBS                 2023
#define IDS_STATUS_RUNWA                2024
#define IDS_PAGE_SKIN_LONG              2025
#define IDS_REGISTER_AGENT              2026
#define IDS_PAGE_ASSOCIATIONS_LONG      2027
#define IDS_PAGE_FEEDBACK_LONG          2028
#define IDS_INCORRECT_EMAIL_ADDRESS     2029
#define IDS_PAGE_INCORRECT_EMAIL_ADDRESS 2029
#define IDS_FILETYPE_AUXILIARY          2030
#define IDS_WINAMP_SKIN_MODERN          2031
#define IDS_WINAMP_SKIN_CLASSIC         2032
#define IDS_WINAMP_LANG_PACK            2033
#define IDS_DOWNLOADSTATUS_INITIALIZING 2034
#define IDS_DOWNLOADSTATUS_CONNECTING   2035
#define IDS_DOWNLOADSTATUS_CONNECTED    2036
#define IDS_DOWNLOADSTATUS_RECEIVING    2037
#define IDS_DOWNLOADSTATUS_RECEIVINGPERCENT 2038
#define IDS_DOWNLOADSTATUS_SUCCESS      2039
#define IDS_DOWNLOADSTATUS_FAILED       2040
#define IDS_DOWNLOADSTATUS_ABORTING     2041
#define IDS_DOWNLOADSTATUS_ABORTED      2042
#define IDS_SETUP_WND_TITLE             2043
#define ID_CMD_SAVE                     40003
#define IDM_HELP_ABOUT                  40008
#define IDM_TOOLS_MIGRATE               40009
#define IDM_TOOLS_REGISTERWINAMP        40010
#define IDM_NAVIGATE_BACK               40011
#define IDM_NAVIGATE_NEXT               40012
#define IDM_FILE_SAVECHANGES            40013
#define IDM_FILE_EXIT                   40016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
