/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_CHECKBOX_H
#define __C_CHECKBOX_H

#include "c_guiobject.h"

#define C_CHECKBOX_PARENT C_GuiObject

class C_CheckBox : public C_CHECKBOX_PARENT {
  public:

  C_CheckBox(ScriptObject *object);
  C_CheckBox();
  virtual ~C_CheckBox();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void onToggle(int newstate);
  virtual void setChecked(int checked);
  virtual int isChecked();
  virtual void setText(const wchar_t *txt);
  virtual const wchar_t *getText();

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int ontoggle_id;
  static int setchecked_id;
  static int ischecked_id;
  static int settext_id;
  static int gettext_id;
};

#endif
