/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_CONTAINER_H
#define __C_CONTAINER_H

#include "c_rootobj.h"

#define C_CONTAINER_PARENT C_RootObject

class C_Container : public C_CONTAINER_PARENT {
  public:

  C_Container(ScriptObject *object);
  C_Container();
  virtual ~C_Container();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void onSwitchToLayout(ScriptObject *newlayout);
  virtual void onBeforeSwitchToLayout(ScriptObject *oldlayout, ScriptObject *newlayout);
  virtual void setXmlParam(const wchar_t *param, const wchar_t *value);
  virtual void onHideLayout(ScriptObject *_layout);
  virtual void onShowLayout(ScriptObject *_layout);
  virtual ScriptObject *getLayout(const wchar_t *layout_id);
  virtual int getNumLayouts();
  virtual ScriptObject *enumLayout(int num);
  virtual void switchToLayout(const wchar_t *layout_id);
  virtual void show();
  virtual void hide();
  virtual void close();
  virtual void toggle();
  virtual int isDynamic();
  virtual void setName(const wchar_t *name);
  virtual ScriptObject *getCurLayout();

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onswitchtolayout_id;
  static int onbeforeswitchtolayout_id;
  static int setxmlparam_id;
  static int onhidelayout_id;
  static int onshowlayout_id;
  static int getlayout_id;
  static int getnumlayouts_id;
  static int enumlayout_id;
  static int switchtolayout_id;
  static int show_id;
  static int hide_id;
  static int close_id;
  static int toggle_id;
  static int isdynamic_id;
  static int setname_id;
  static int getcurlayout_id;
};

#endif
