/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_GROUPLIST_H
#define __C_GROUPLIST_H

#include "c_guiobject.h"

#define C_GROUPLIST_PARENT C_GuiObject

class C_GroupList : public C_GROUPLIST_PARENT {
  public:

  C_GroupList(ScriptObject *object);
  C_GroupList();
  virtual ~C_GroupList();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual ScriptObject *instantiate(const char *group_id, int num_groups);
  virtual int getNumItems();
  virtual ScriptObject *enumItem(int num);
  virtual void removeAll();
  virtual void scrollToPercent(int percent);

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int instantiate_id;
  static int getnumitems_id;
  static int enumitem_id;
  static int removeall_id;
  static int scrolltopercent_id;
};

#endif
