/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __C_LAYOUT_H
#define __C_LAYOUT_H

#include "c_group.h"

#define C_LAYOUT_PARENT C_Group

class C_Layout : public C_LAYOUT_PARENT {
  public:

  C_Layout(ScriptObject *object);
  C_Layout();
  virtual ~C_Layout();

  virtual void C_hook(ScriptObject *o);

  ScriptObject *getScriptObject();

  virtual void onDock();
  virtual void onUndock();
  virtual void onScale(double newscalevalue);
  virtual double getScale();
  virtual void setScale(double scalevalue);
  virtual void setDesktopAlpha(int onoff);
  virtual int getDesktopAlpha();
  virtual ScriptObject *getContainer();
  virtual void center();
  virtual void onMove();
  virtual void onEndMove();
  virtual void onUserResize(int x, int y, int w, int h);
  virtual void snapAdjust(int left, int top, int right, int bottom);
  virtual int getSnapAdjustTop();
  virtual int getSnapAdjustRight();
  virtual int getSnapAdjustLeft();
  virtual int getSnapAdjustBottom();
  virtual void setRedrawOnResize(int wantredrawonresize);
  virtual void beforeRedock();
  virtual void redock();
  virtual int isTransparencySafe();
  virtual int isLayoutAnimationSafe();
  virtual void onMouseEnterLayout();
  virtual void onMouseLeaveLayout();
  virtual void onSnapAdjustChanged();

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int ondock_id;
  static int onundock_id;
  static int onscale_id;
  static int getscale_id;
  static int setscale_id;
  static int setdesktopalpha_id;
  static int getdesktopalpha_id;
  static int getcontainer_id;
  static int center_id;
  static int onmove_id;
  static int onendmove_id;
  static int onuserresize_id;
  static int snapadjust_id;
  static int getsnapadjusttop_id;
  static int getsnapadjustright_id;
  static int getsnapadjustleft_id;
  static int getsnapadjustbottom_id;
  static int setredrawonresize_id;
  static int beforeredock_id;
  static int redock_id;
  static int istransparencysafe_id;
  static int islayoutanimationsafe_id;
  static int onmouseenterlayout_id;
  static int onmouseleavelayout_id;
  static int onsnapadjustchanged_id;
};

#endif
