/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_BROWSER_H
#define __HOOK_BROWSER_H

#include "h_guiobject.h"

#define H_BROWSER_PARENT H_GuiObject

class H_Browser : public H_BROWSER_PARENT {

public:

  H_Browser(ScriptObject *o);
  H_Browser();
  virtual ~H_Browser();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);
  virtual void hook_onBeforeNavigate(const wchar_t *url, int flags, const wchar_t *targetframename) {  }
  virtual void hook_onDocumentComplete(const wchar_t *url) {  }
	virtual void hook_onMediaLink(const wchar_t *url) {  }

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onbeforenavigate_id;
  static int ondocumentcomplete_id;
	static int onmedialink_id;
};

#endif
