/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_CONTAINER_H
#define __HOOK_CONTAINER_H

#include "h_rootobj.h"

#define H_CONTAINER_PARENT H_RootObject

class H_Container : public H_CONTAINER_PARENT {

public:

  H_Container(ScriptObject *o);
  H_Container();
  virtual ~H_Container();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);
  virtual void hook_onSwitchToLayout(ScriptObject *newlayout) {  }
  virtual void hook_onBeforeSwitchToLayout(ScriptObject *oldlayout, ScriptObject *newlayout) {  }
  virtual void hook_onHideLayout(ScriptObject *_layout) {  }
  virtual void hook_onShowLayout(ScriptObject *_layout) {  }

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onswitchtolayout_id;
  static int onbeforeswitchtolayout_id;
  static int onhidelayout_id;
  static int onshowlayout_id;
};

#endif
