/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_EDIT_H
#define __HOOK_EDIT_H

#include "h_guiobject.h"

#define H_EDIT_PARENT H_GuiObject

class H_Edit : public H_EDIT_PARENT {

public:

  H_Edit(ScriptObject *o);
  H_Edit();
  virtual ~H_Edit();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);
  virtual void hook_onEnter() {  }
  virtual void hook_onAbort() {  }
  virtual void hook_onIdleEditUpdate() {  }
  virtual void hook_onEditUpdate() {  }

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onenter_id;
  static int onabort_id;
  static int onidleeditupdate_id;
  static int oneditupdate_id;
};

#endif
