/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_GROUP_H
#define __HOOK_GROUP_H

#include "h_guiobject.h"

#define H_GROUP_PARENT H_GuiObject

class H_Group : public H_GROUP_PARENT {

public:

  H_Group(ScriptObject *o);
  H_Group();
  virtual ~H_Group();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);
  virtual void hook_onCreateObject(ScriptObject *newobj) {  }

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int oncreateobject_id;
};

#endif
