/* This file was generated by Maki Compiler, do not edit manually */

#include <precomp.h>

#include <api/script/objcontroller.h>
#include "h_group.h"

H_Group::H_Group(ScriptObject *o) : H_GuiObject(o) {
  inited = 0;
  obj = NULL;
  H_hook(o);
}

H_Group::H_Group() {
  inited = 0;
  obj = NULL;
}

void H_Group::H_hook(ScriptObject *o) {
  ASSERT(!inited);
  ScriptObjectController *controller = o->vcpu_getController();
  obj = controller->cast(o, groupGuid);
  if (obj != o && obj != NULL)
    o = obj;
  else
    obj = NULL;

  addMonitorObject(o, &groupGuid);

  int iter = WASABI_API_APP->app_getInitCount();
  if (!loaded || loaded != iter) {
    oncreateobject_id= WASABI_API_MAKI->maki_addDlfRef(o->vcpu_getController(), L"onCreateObject", this);
    loaded = 1;
  }
  inited=1;
}

H_Group::~H_Group() {
  if (!inited) return;
  WASABI_API_MAKI->maki_remDlfRef(this);
}

ScriptObject *H_Group::getHookedObject() {
  if (obj != NULL) return obj;
  return H_GROUP_PARENT::getHookedObject();
}

int H_Group::eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams) {
  if (object != getHookedObject()) return 0;
  if (H_GROUP_PARENT::eventCallback(object, dlfid, params, nparams)) return 1;
  if (dlfid == oncreateobject_id) { hook_onCreateObject(GET_SCRIPT_OBJECT(*params[0])); return 1; }
  return 0;
}

int H_Group::oncreateobject_id=0;
int H_Group::loaded=0;
