/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_GROUPLIST_H
#define __HOOK_GROUPLIST_H

#include "h_guiobject.h"

#define H_GROUPLIST_PARENT H_GuiObject

class H_GroupList : public H_GROUPLIST_PARENT {

public:

  H_GroupList(ScriptObject *o);
  H_GroupList();
  virtual ~H_GroupList();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
};

#endif
