/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_MENUBUTTON_H
#define __HOOK_MENUBUTTON_H

#include "h_guiobject.h"

#define H_MENUBUTTON_PARENT H_GuiObject

class H_MenuButton : public H_MENUBUTTON_PARENT {

public:

  H_MenuButton(ScriptObject *o);
  H_MenuButton();
  virtual ~H_MenuButton();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);
  virtual void hook_onOpenMenu() {  }
  virtual void hook_onCloseMenu() {  }
  virtual void hook_onSelectItem(const wchar_t *item) {  }

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onopenmenu_id;
  static int onclosemenu_id;
  static int onselectitem_id;
};

#endif
