/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_SLIDER_H
#define __HOOK_SLIDER_H

#include "h_guiobject.h"

#define H_SLIDER_PARENT H_GuiObject

class H_Slider : public H_SLIDER_PARENT {

public:

  H_Slider(ScriptObject *o);
  H_Slider();
  virtual ~H_Slider();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);
  virtual void hook_onSetPosition(int newpos) {  }
  virtual void hook_onPostedPosition(int newpos) {  }
  virtual void hook_onSetFinalPosition(int pos) {  }

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int onsetposition_id;
  static int onpostedposition_id;
  static int onsetfinalposition_id;
};

#endif
