/* This file was generated by Maki Compiler, do not edit manually */

#include <precomp.h>
#include <api/api.h>
#include <api/script/objcontroller.h>
#include "h_tabsheet.h"

H_TabSheet::H_TabSheet(ScriptObject *o) : H_GuiObject(o) {
  inited = 0;
  obj = NULL;
  H_hook(o);
}

H_TabSheet::H_TabSheet() {
  inited = 0;
  obj = NULL;
}

void H_TabSheet::H_hook(ScriptObject *o) {
  ASSERT(!inited);
  ScriptObjectController *controller = o->vcpu_getController();
  obj = controller->cast(o, tabSheetGuid);
  if (obj != o && obj != NULL)
    o = obj;
  else
    obj = NULL;

  addMonitorObject(o, &tabSheetGuid);

  int iter = WASABI_API_APP->app_getInitCount();
  if (!loaded || loaded != iter) {
    loaded = 1;
  }
  inited=1;
}

H_TabSheet::~H_TabSheet() {
  if (!inited) return;
  WASABI_API_MAKI->maki_remDlfRef(this);
}

ScriptObject *H_TabSheet::getHookedObject() {
  if (obj != NULL) return obj;
  return H_TABSHEET_PARENT::getHookedObject();
}

int H_TabSheet::eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams) {
  if (object != getHookedObject()) return 0;
  if (H_TABSHEET_PARENT::eventCallback(object, dlfid, params, nparams)) return 1;
  return 0;
}

int H_TabSheet::loaded=0;
