/* This file was generated by Maki Compiler, do not edit manually */

#ifndef __HOOK_TOGGLEBUTTON_H
#define __HOOK_TOGGLEBUTTON_H

#include "h_button.h"

#define H_TOGGLEBUTTON_PARENT H_Button

class H_ToggleButton : public H_TOGGLEBUTTON_PARENT {

public:

  H_ToggleButton(ScriptObject *o);
  H_ToggleButton();
  virtual ~H_ToggleButton();
  virtual void H_hook(ScriptObject *o);
  ScriptObject *getHookedObject();

  virtual int eventCallback(ScriptObject *object, int dlfid, scriptVar **params, int nparams);
  virtual void hook_onToggle(int (null)) {  }

  private:

  ScriptObject *obj;
  int inited;
  static int loaded;
  static int ontoggle_id;
};

#endif
