//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by fileinfo.rc
//
#define IDS_NULLSOFT_WINDOWS_MEDIA_DECODER_OLD          0
#define IDS_WMDRM_ABOUT                 1
#define IDS_ABOUT                       2
#define IDS_REALTIME                    3
#define IDS_CONNECTING                  4
#define IDS_LOCATING                    5
#define IDS_ACCESS_DENIED               6
#define IDS_STEREO                      7
#define IDS_QUADROPHONIC                8
#define IDS_SURROUND                    9
#define IDS_5_1                         10
#define IDS_7_1                         11
#define IDS_EXT                         12
#define IDS_DESCRIPTION                 13
#define IDS_PROTOCOL                    14
#define IDS_EXTENSION                   15
#define IDS_EDIT_FILE_TYPE              16
#define IDS_WMA_AUDIO_FILE              17
#define IDS_WMA_VIDEO_FILE              18
#define IDS_ASF_STREAM                  19
#define IDS_WINDOWS_MEDIA_STREAM        20
#define IDS_UNKNOWN_ERROR               21
#define IDS_ATTRIBUTE                   22
#define IDS_VALUE                       23
#define IDS_CLOSE                       24
#define IDS_UNABLE_TO_WRITE_TO_FILE_DOES_FILE_EXIST 25
#define IDS_UNABLE_TO_WRITE_TO_FILE     26
#define IDS_UNABLE_TO_WRITE_TO_FILE_MAY_NOT_HAVE_ACCESS 27
#define IDS_SAVE_FAILED                 28
#define IDS_TRUE                        29
#define IDS_FALSE                       30
#define IDS_UNKNOWN                     31
#define IDS_WINDOWS_MEDIA_XXX           32
#define IDS_WINDOWS_MEDIA_PROTECTED_CONTENT_NEED_LICENSE 33
#define IDS_LICENSE_REQUIRED            34
#define IDS_BEGINNING_UPDATE            35
#define IDS_UPDATE_FAILED               36
#define IDS_UPDATE_CANCELLED            37
#define IDS_IDLE                        38
#define IDS_REQUESTING                  39
#define IDS_RECEIVING_DATA              40
#define IDS_COMPLETED                   41
#define IDS_INSTALLING                  42
#define IDS_FILE_PROTECTED_CANNOT_PLAY_IN_WINAMP 43
#define IDS_LICENSE_ACQUIRED            44
#define IDS_WINDOWS_MEDIA_PROTECTED_CONTENT_UNTRUSTED_SOURCE 45
#define IDS_UNTRUSTED_LICENSE           46
#define IDS_WINDOWS_MEDIA_PROTECTED_CONTENT_TAMPERED_LICENSE 47
#define IDS_TAMPERED_LICENSE            48
#define IDS_WINDOWS_MEDIA_PROTECTED_CONTENT_SECURITY_UPDATE 49
#define IDS_SECURITY_UPDATE_REQUIRED    50
#define IDS_UPDATING                    51
#define IDS_ENCRYPTED_IN_OP_LEVEL_HIGHER_THAN_SUPPORTED 52
#define IDS_WINDOWS_MEDIA_PLAYBACK_FAILURE 53
#define IDS_UPDATE_REQUIRED             54
#define IDS_ACQUIRING_LICENSE           55
#define IDS_DRM_LICENSE_EXPIRED_VISIT_WINAMP_COM 56
#define IDS_ERROR                       57
#define IDS_STRING58                    58
#define IDS_BUFFERING                   58
#define IDS_STRING59                    59
#define IDS_UNKNOWN_ERROR_WAV           59
#define IDS_CODEC                       60
#define IDS_DURATION                    61
#define IDS_BITRATE                     62
#define IDS_FILESIZE                    63
#define IDS_YES                         64
#define IDS_NO                          65
#define IDS_WMVER                       66
#define IDS_SEEKABLE                    67
#define IDS_STRIDABLE                   68
#define IDS_BROADCAST                   69
#define IDS_PROTECTED                   70
#define IDS_TRUSTED                     71
#define IDS_CONTAINS                    72
#define IDS_NAME                        73
#define IDS_STRING74                    74
#define IDS_KBPS                        74
#define IDS_ABOUT_TEXT                  75
#define IDD_CONFIG                      105
#define IDD_CONFIG_STATUS               112
#define IDD_ADDTYPE                     113
#define IDD_ADVANCED                    114
#define IDS_AUDIO                       117
#define IDS_VIDEO                       118
#define IDS_IMAGE                       119
#define IDS_SCRIPT                      120
#define IDS_NONE                        121
#define IDS_WINDOWS_MEDIA_PLAYLIST      122
#define IDS_STRING124                   123
#define IDS_ASX_PLAYLIST                123
#define IDD_INFO                        131
#define IDC_EDIT                        1003
#define IDC_DEV                         1004
#define IDC_REVERT                      1006
#define IDC_BUTTON5                     1007
#define IDC_DELETE                      1007
#define IDC_REMOVETYPE                  1007
#define IDC_ADD                         1008
#define IDC_APPLY                       1009
#define IDC_TEMP                        1009
#define IDC_VOL_ENABLE                  1009
#define IDC_METADATALIST                1010
#define IDC_ALT_VOL                     1010
#define IDC_VOL_RESET                   1011
#define IDC_EDIT1                       1011
#define IDC_AUDIO_EARLY_PAD             1011
#define IDC_VIDEO_EARLYPAD              1011
#define IDC_BUFFER_TIME                 1011
#define IDC_VIDEO_EARLY_PAD             1012
#define IDC_EDIT2                       1012
#define IDC_AUDIO_EARLYPAD              1012
#define IDC_STATE                       1013
#define IDC_FILENAME                    1014
#define IDC_STATIC_TITLE                1015
#define IDC_STATIC_ARTIST               1016
#define IDC_STATIC_ALBUM                1017
#define IDC_STATIC_TRACK                1018
#define IDC_BLAH                        1018
#define IDC_STATIC_YEAR                 1019
#define IDC_STATIC_GENRE                1020
#define IDC_STATIC_COMMENTS             1021
#define IDC_EDIT_TITLE                  1022
#define IDC_EDIT_ARTIST                 1023
#define IDC_EDIT_ALBUM                  1024
#define IDC_EDIT_COMMENTS               1025
#define IDC_EDIT_GENRE                  1026
#define IDC_EDIT_YEAR                   1027
#define IDC_EDIT_TRACK                  1028
#define IDC_BUTTON_DELALL               1028
#define IDC_LOWMEMORY                   1029
#define IDC_EDIT_GENRE2                 1029
#define IDC_EDIT_PUBLISHER              1029
#define IDC_STATIC_GENRE2               1030
#define IDC_AUDIO_OUTOFORDER            1031
#define IDC_EDIT_GENRE3                 1031
#define IDC_EDIT_ALBUMARTIST            1031
#define IDC_AUDIO_DEDICATED_THREAD      1032
#define IDC_VIDEO_OUTOFORDER            1033
#define IDC_AUDIO_EARLY                 1034
#define IDC_VIDEO_DEDICATED_THREAD      1035
#define IDC_VIDEO_EARLY                 1036
#define IDC_VIDEO_JITTER                1039
#define IDC_VIDEO_CACHE_FRAMES          1040
#define IDC_VIDEO_CATCHUP               1042
#define IDC_VIDEO_NOTIFYLATE            1043
#define IDC_CHECK3                      1044
#define IDC_VIDEO_FRAMEDROPOFFSET       1044
#define IDC_SILENT                      1044
#define IDC_REALTIME                    1044
#define IDC_BROWSER                     1045
#define IDC_EDIT5                       1049
#define IDC_RESET                       1052
#define IDC_GLOBAL_FADES                1053
#define IDC_CUSTOM_FADE_SPIN            1054
#define IDC_LOGVOL_SPIN                 1055
#define IDC_REFRESH_SPIN                1056
#define IDC_FADE                        1057
#define IDC_FADE_SPIN                   1058
#define IDC_CREATE_PRIMARY              1059
#define IDC_PAUSEFADE2                  1060
#define IDC_DEVICE                      1061
#define IDC_WAITx                       1062
#define IDC_PREBUFFER_2                 1063
#define IDC_KILLSIL                     1064
#define IDC_DB                          1065
#define IDC_DB_DISPLAY                  1066
#define IDC_PREBUFFER_1                 1067
#define IDC_LIST                        1068
#define IDC_PREBUF_DISP_1               1069
#define IDC_CUSTOM_FADE                 1070
#define IDC_PREBUF_DISP_2               1071
#define IDC_USE_CUSTOM_FADE             1072
#define IDC_BUFFER                      1073
#define IDC_BUF_DISP                    1074
#define IDC_STATIC_MS                   1075
#define IDC_BUF_RESET                   1076
#define IDC_VOLUME                      1077
#define IDC_TAB1                        1078
#define IDC_TAB                         1079
#define IDC_DEVICE_INFO                 1080
#define IDC_PDS_FAQ                     1081
#define IDC_FADE_GROUP                  1082
#define IDC_FADE_ENABLED                1083
#define IDC_REFRESH                     1084
#define IDC_STAT_COPY                   1085
#define IDC_LOGVOL_MIN                  1086
#define IDC_LOGVOL_STATIC               1087
#define IDC_LOGVOL_STATIC2              1088
#define IDC_FADEVOL                     1089
#define IDC_PREBUF_AUTO                 1090
#define IDC_STATIC_BLEH                 1091
#define IDC_WAVE_GAPLESS                1092
#define IDC_WAVE_RESET                  1093
#define IDC_WAVE_BUF_SIZE               1093
#define IDC_WAVE_SPIN1                  1094
#define IDC_WAVE_PRIMARY                1095
#define IDC_WAVE_PREBUF_SIZE            1095
#define IDC_WAVE_DEV                    1096
#define IDC_WAVE_HACK                   1097
#define IDC_WAVE_EXCLUSIVE              1098
#define IDC_WAVE_PREBUFFER              1099
#define IDC_WAVE_SPIN2                  1100
#define IDC_WAVE_VOL_ENABLE             1101
#define IDC_WAVE_ALT_VOL                1102
#define IDC_WAVE_VOL_RESET              1103
#define IDC_WAVE_PREB_TEXT              1104
#define IDC_WAVE_STATE                  1105
#define IDC_WAVE_PREBUFFER_1            1106
#define IDC_WAVE_PREBUFFER_2            1107
#define IDC_WAVE_PREBUF_DISP_1          1108
#define IDC_WAVE_PREBUF_DISP_2          1109
#define IDC_WAVE_BLAH                   1110
#define IDC_WAVE_BUFFER                 1111
#define IDC_WAVE_BUF_DISP               1112
#define IDC_VOLMODE                     1113
#define IDC_LOGFADES                    1114
#define IDC_TEXT1                       1115
#define IDC_HW_MIX                      1116
#define IDC_VER                         1117
#define IDC_LIST2                       1119
#define IDC_FLIP                        1120
#define IDC_HTTPMETA                    1121
#define IDC_ADVANCED                    1122
#define IDC_DEFAULTTYPE                 1123
#define IDC_ADDTYPE                     1124
#define IDC_EDITTYPE                    1125
#define IDC_TYPELIST                    1126
#define IDC_UNTRUSTED                   1127
#define IDC_TYPE                        1129
#define IDC_DESCRIPTION                 1130
#define IDC_FILEEXTENSION               1131
#define IDC_PROTOCOL                    1132
#define IDC_VIDEO_THREAD                1135
#define IDC_AUDIO_DROP                  1138
#define IDC_CHECK8                      1139
#define IDC_VIDEO_NOTIFY                1139
#define IDC_AUDIO_THREAD                1140
#define IDC_EDIT4                       1145
#define IDC_EDIT7                       1146
#define IDC_AUDIO_CACHE_FRAMES          1146
#define IDC_EDIT6                       1148
#define IDC_VIDEO_DROP_THRESHOLD        1148
#define IDC_EDIT9                       1149
#define IDC_TYPE_AUDIO                  1151
#define IDC_TYPE_VIDEO                  1152
#define IDC_STATIC_TYPE                 1153
#define IDC_TYPE_AUDIO2                 1154
#define IDC_EXTRA_ASX                   1154
#define IDC_AUDIO_SPEAKER_COUNT         10000
#define IDS_NULLSOFT_WINDOWS_MEDIA_DECODER 65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
