//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SVIS.RC
//
#define IDS_NULLSOFT_TINY_FULLSCREEN    0
#define IDS_DIRECTDRAWCREATE_FAILED     1
#define IDS_COULD_NOT_SET_EXCLUSIVE_FULLSCREEN 2
#define IDS_COULD_NOT_SET_DISPLAY_MODE  3
#define IDS_COULD_NOT_CREATE_PRIMARY_SURFACE 4
#define IDS_COULD_NOT_CREATE_RENDER_SURFACE 5
#define IDS_COULD_NOT_CREATE_PALETTE    6
#define IDS_COULD_NOT_SET_PALETTE       7
#define IDS_MMX_NOT_FOUND               8
#define IDS_ERROR                       9
#define IDS_DIRECTDRAW_ERROR            10
#define IDS_SEXY_SCROLLING_VOICEPRINT   11
#define IDS_SPECTRUM_ANALYZER_VOICEPRINT 12
#define IDS_SPECTRUM_ANALYZER_OSCILLOSCOPE 13
#define IDS_RANDOM_INTELLIGENT_VISUALIZATION 14
#define IDS_CANNOT_GO_FULLSCREEN_WHEN_VIDEO_PLAYING 15
#define IDD_DIALOG1                     101
#define IDR_MENU1                       101
#define IDD_DIALOG2                     102
#define IDC_SVM                         1000
#define IDC_BPP                         1001
#define IDC_SPEED                       1002
#define IDC_AP1                         1003
#define IDC_AP2                         1004
#define IDC_AP3                         1005
#define IDC_AP4                         1006
#define IDC_AP5                         1007
#define IDC_AP6                         1008
#define IDC_VP1                         1009
#define IDC_VP2                         1010
#define IDC_VP3                         1011
#define IDC_VP4                         1012
#define IDC_VP5                         1013
#define IDC_VP6                         1014
#define IDC_DEFVP                       1015
#define IDC_FALLOFF                     1016
#define IDC_FALLOFF2                    1017
#define IDC_TCOL                        1018
#define IDC_BANDS                       1018
#define IDC_VUSE                        1019
#define IDC_DEFAP                       1020
#define IDC_SCSCALE                     1021
#define IDC_WIDTH                       1084
#define IDC_HEIGHT                      1085
#define IDC_DIZ                         1086
#define IDC_FN                          1087
#define IDC_BROWSSE                     1088
#define IDC_CRIGHT                      1089
#define IDC_CHECK1                      1090
#define IDC_MODELIST                    1091
#define IDC_SCOPE                       1092
#define IDC_EDIT1                       1092
#define IDC_EDIT2                       1093
#define IDC_SLIDER1                     1094
#define IDC_COPYRIGHT                   1095
#define IDM_WVIS                        40002
#define IDM_NOFADE                      40004
#define IDM_NORMALFADE                  40005
#define IDM_NORMALSCOPE                 40008
#define IDM_SOLIDSCOPE                  40009
#define IDM_QUIT                        40010
#define IDM_NORMALANALYZER              40012
#define IDM_SOLIDANALYZER               40013
#define IDM_AF_FAST                     40016
#define IDM_AF_FAST2                    40017
#define IDM_AF_FAST3                    40018
#define IDM_REFFAST                     40019
#define IDM_REFMED                      40020
#define IDM_REFSLOW                     40021
#define IDM_FLOWERS                     40022
#define IDM_CLEARFADE                   40030
#define IDM_NORMALSCOPE_COLOR           40031
#define IDM_SOLIDSCOPE_COLOR            40032
#define IDM_NORMALANALYZER_COLOR        40033
#define IDM_SOLIDANALYZER_COLOR         40034
#define IDM_FLOWERS_COLOR               40035
#define IDM_FLOWCOMP_VLOW               40036
#define IDM_FLOWCOMP_LOW                40037
#define IDM_FLOWCOMP_LOWER              40038
#define IDM_FLOWCOMP_MID                40039
#define IDM_FLOWCOMP_HIGH               40040
#define IDM_SLOWERFADE                  40041
#define IDM_SLOWFADE                    40042
#define IDM_FASTERFADE                  40043
#define IDM_FASTFADE                    40044
#define IDM_NORMALSCOPE_COLOR_R         40045
#define IDM_SOLIDSCOPE_COLOR_R          40047
#define IDM_NORMALANALYZER_COLOR_R      40049
#define IDM_SOLIDANALYZER_COLOR_R       40050
#define IDM_FLOWERS_COLOR_R             40051
#define IDM_DOCK_INWINDOW               40052
#define IDM_DOCK_BOTTOM                 40053
#define IDM_DOCK_TOP                    40054
#define IDM_DOCK_LEFT                   40055
#define IDM_DOCK_RIGHT                  40056
#define IDM_DOCK_LILVIS                 40057
#define IDM_DOCK_LILVIS_2               40058
#define IDM_FADE_BLUR                   40059
#define IDM_PRE_LOAD                    40061
#define IDM_PRE_SAVE                    40062
#define IDM_COL_BG                      40063
#define IDM_SPECRADAR                   40064
#define IDM_SPECRADAR_COLOR             40065
#define IDM_SPECRADAR_COLOR_R           40066
#define IDM_VUSPIN_COLOR                40067
#define IDM_VUSPIN_COLOR_R              40068
#define IDM_VUSPIN                      40069
#define IDM_FADE_NONE                   40070
#define IDM_FADE_BLIT                   40071
#define IDM_SPIN_LINE                   40072
#define IDM_SPIN_TRI                    40073
#define IDM_TIME                        40074
#define IDM_TIME_LEFT                   40076
#define IDM_TIME_CENTER                 40077
#define IDM_TIME_RIGHT                  40078
#define IDM_TIME_TOP                    40079
#define IDM_TIME_MIDDLE                 40080
#define IDM_TIME_BOTTOM                 40081
#define IDM_TIME_COLOR                  40082
#define IDM_FULLSCREEN                  40084
#define IDM_FULLSCREEN_320X200          40085
#define IDM_FULLSCREEN_320X240          40086
#define IDM_FULLSCREEN_512X384          40087
#define IDM_FULLSCREEN_640x400          40088
#define IDM_FULLSCREEN_640x480          40089
#define IDM_FULLSCREEN_800X600          40090
#define IDM_OSCSTAR                     40091
#define IDM_OSCSTAR_COLOR               40092
#define IDM_OSCSTAR_COLOR_R             40093
#define ID_BLEND_AVG                    40094
#define ID_BLEND_ADD                    40095
#define ID_BLEND_MAX                    40096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
