#pragma once
#include <ocidl.h>
#include "main.h"
#include "../nu/ns_wc.h"
#include "setup/setup.h"
#include "api.h"
#include "JSAPI.h"
#include "draw.h"
#include "WADrawDC.h"
#include "options.h"
#include "language.h"
#include "wa_ipc.h"
#include "playlist.h"
#include "videooutput.h"
