//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Winamp.rc
//
#define IDS_UNINST_1                    1
#define IDS_UNINST_CAP                  2
#define IDC_ID3_REMOVE                  3
#define IDS_UNINST_CANCEL               3
#define IDC_NEVER                       3
#define IDC_CANCELALL                   3
#define IDRESET                         3
#define IDS_UNINST_SURE                 4
#define IDS_ERROR                       4
#define IDS_ERRORINIT                   5
#define IDS_EQCAPTION                   6
#define IDS_PECAPTION                   7
#define IDS_OPENDIR                     8
#define IDS_OPENDIRMORE                 9
#define IDS_PLUGINERROR                 10
#define IDS_ERRORLOADINGPLUGIN          11
#define IDS_DYNAMICLINKS                12
#define IDS_DLINK_UPDATE                13
#define IDS_PREFS_BOOK                  13
#define IDS_DLINK_NOCONTENT             14
#define IDS_DLINK_GETTING               15
#define IDS_DLINK_SUCCESS               16
#define IDS_BASICINFO                   16
#define IDS_DLINK_ERROR                 17
#define IDS_UNREGSTRING                 18
#define IDS_ARTWORK                     18
#define IDS_STATS                       19
#define IDS_ADVANCED                    19
#define IDS_ONLYHTTP                    20
#define IDS_WINAMP_UPDATE_MSG           20
#define IDS_NOOUTPUT                    21
#define IDS_PLAYLISTSTRING              22
#define IDS_ALLTYPES                    23
#define IDS_RETRPL                      24
#define IDS_CONF_HELPSTR                25
#define IDS_P_IN_INPUTS                 26
#define IDS_P_IN_CONF                   27
#define IDS_P_IN_ABOUT                  28
#define IDS_P_O_DEFEXT                  29
#define IDS_P_SETUP_PROXY               30
#define IDS_P_OUT_CONF                  31
#define IDS_P_OUT_ABOUT                 32
#define IDS_P_OUT_OUTPUTS               33
#define IDS_P_O_PRIO                    34
#define IDS_P_SETUP_PRIO                34
#define IDS_P_DISP_SYSTRAY              35
#define IDS_P_DISP_TASKBAR              36
#define IDS_P_DISP_SYSTRAYICON          37
#define IDS_P_DISP_SYSTRAYTASK          38
#define IDS_P_DISP_FREESIZE             38
#define IDS_P_DISP_NONE                 39
#define IDS_P_CLASSICUI                 39
#define IDS_P_DISP_HILITE               40
#define IDS_P_DISP_SNAP                 41
#define IDS_P_DISP_CB                   42
#define IDS_P_DISP_TTIPS                43
#define IDS_P_O_SPLASH                  44
#define IDS_P_DISP_TNUMS                45
#define IDS_P_O_PLCHILD                 46
#define IDS_P_O_SPLB                    46
#define IDS_P_O_EQDS                    47
#define IDS_P_DISP_CURSORS              48
#define IDS_P_O_ONLOAD                  49
#define IDS_P_O_ONDEM                   50
#define IDS_P_O_RFL                     51
#define IDS_P_O_AMI                     52
#define IDS_P_SETUP_MINST               52
#define IDS_P_O_CONVERT1                53
#define IDS_P_O_CONVERT2                54
#define IDS_P_DISP_STITLE               55
#define IDS_P_DISP_PLFONT               56
#define IDS_P_O_LITESTEP                57
#define IDS_P_O_AOVD                    58
#define IDS_P_FT_EXTENSIONS             59
#define IDS_P_FT_ALL                    60
#define IDS_P_FT_NO                     61
#define IDS_P_FT_ENQUEUE                62
#define IDS_P_FT_ICON                   63
#define IDS_P_FT_ICON2                  64
#define IDS_P_SETUP_START               65
#define IDS_PREFSHLP_FT_DESK            66
#define IDS_P_VIS_LIB                   67
#define IDS_P_VIS_MOD                   68
#define IDS_P_PLUG_AUTO                 69
#define IDS_P_PLUG_DIS                  70
#define IDS_P_VIS_START                 71
#define IDS_P_VIS_STOP                  72
#define IDS_P_VIS_CONF                  73
#define IDS_P_PLUG_PRIO                 74
#define IDS_P_DSP_LIB                   75
#define IDS_P_DSP_MOD                   76
#define IDS_P_DSP_CONF                  77
#define IDS_P_GEN_LIB                   78
#define IDS_P_GEN_CONF                  79
#define IDS_TOOLTIPS                    81
#define IDS_P_SETUP_START2              82
#define IDS_P_SETUP_LANG                83
#define IDS_P_FT_DIRCONTEXT             84
#define IDS_P_DISP_SNAPW                85
#define IDS_P_PLUG_VISDIR               86
#define IDS_P_PLUG_DSPDIR               87
#define IDS_SELVISDIR                   88
#define IDS_SELDSPDIR                   89
#define IDS_PREFS_SETUP                 90
#define IDS_PREFS_FT                    91
#define IDS_PREFS_OPTIONS               92
#define IDS_PREFS_DISPLAY               93
#define IDS_PREFS_TITLES                93
#define IDS_PREFS_PLUG                  94
#define IDS_PREFS_PLUG_IN               95
#define IDS_PREFS_PLUG_OUT              96
#define IDS_PREFS_PLUG_VIS              97
#define IDS_PREFS_PLUG_DSP              98
#define IDS_PREFS_PLUG_GEN              99
#define IDS_P_FT_CD                     100
#define WINAMP_MAIN                     101
#define IDS_MBCAPTION                   101
#define ICON_XP                         102
#define IDS_INETLOC                     102
#define IDD_BUFFERS                     103
#define IDS_PERMDELALL                  103
#define IDD_OUTPUT                      104
#define IDS_LANGCHANGE                  104
#define IDS_SELLANGPACK                 105
#define IDS_DELETEAUTOLOAD1             106
#define IDS_DELETEAUTOLOAD2             107
#define IDS_DELETEPRE1                  108
#define IDB_SPLASH                      109
#define IDS_LOADAUTOLOAD                109
#define IDD_SPLASH                      110
#define IDS_SAVEAUTOLOAD                110
#define IDS_PLFONT                      111
#define IDS_PLFONT_CHARSET              112
#define IDS_P_FT_RSTART                 113
#define IDS_P_DISP_BIFONT               114
#define IDS_GETMORE                     115
#define IDD_PREFS                       116
#define IDS_INST_DONETITLE              116
#define IDS_INST_SETTITLE               117
#define IDS_INST_CLOSE                  117
#define IDS_INST_USERINFO               118
#define IDS_P_DISP_PLPOS                118
#define IDS_INST_LATER                  119
#define IDS_ART_SEARCH_FAILED           119
#define IDD_ABOUT1                      120
#define IDS_INST_SENDINGIN              120
#define IDD_NEWABOUT1                   120
#define IDS_INST_FINISH                 121
#define IDS_INST_INET1                  122
#define IDS_INST_INET2                  123
#define IDS_INST_INET3                  124
#define IDS_INET_CANCEL1                125
#define IDS_ART_SEARCH_FINISHED         125
#define IDB_MAINBITMAP                  126
#define IDS_P_SETUP_VER                 126
#define IDB_CBUTTONS                    127
#define IDS_P_SETUP_ADDQL               127
#define IDS_P_SETUP_INTERNET            127
#define IDB_MONOSTEREO                  128
#define IDS_P_SETUP_INET1               128
#define IDB_PLAYPAUSE                   129
#define IDS_P_SETUP_INET2               129
#define IDB_SHUFFLEREP                  130
#define IDS_P_SETUP_INET3               130
#define IDI_FILEICON                    131
#define IDS_DSP_NONE                    131
#define IDB_NUMBERS1                    132
#define IDS_CONFIG_PLAYSTR              132
#define IDB_VOLBAR                      133
#define IDS_CONFIG_ENQUEUESTR           133
#define IDB_FONT1                       134
#define IDS_PREFS_SKIN                  134
#define IDB_POSBAR                      135
#define IDS_P_O_MPA                     135
#define IDS_P_SK_SEL                    136
#define IDS_P_SK_RND                    137
#define IDS_P_SK_CHDR                   138
#define IDS_PREFS_VIS                   139
#define IDS_PREFS_CLASSICSKIN           139
#define IDS_PREFS_AG                    140
#define IDD_EQ                          141
#define IDS_P_SETUP_VER2                141
#define IDD_PLAYLISTEDITOR              142
#define IDS_P_A_ENABLE                  142
#define IDD_EQUALIZER_UI                142
#define IDS_P_A_TRAY                    143
#define IDD_FILETYPES                   144
#define IDS_P_FILEASSOCIATIONS          144
#define IDD_VIS                         145
#define IDS_CONFIG_BOOKMARKSTR          145
#define IDS_P_O_ONPLAY                  146
#define IDS_P_O_SMS                     147
#define IDR_ACCELERATOR1                148
#define IDS_PREFS_SHUFFLE               148
#define IDB_SPEC                        149
#define IDS_VIDEOCAPTION                149
#define IDB_TB                          150
#define IDS_PREFS_VIDEO                 150
#define IDS_P_O_VIDEO_VSYNC             151
#define IDD_ABOUT2                      152
#define IDS_P_O_VIDEO_ADJASP            152
#define IDB_NULLSOFT                    153
#define IDS_P_O_VIDEO_OVERLAYS          153
#define IDD_ABOUT3                      154
#define IDD_NEWABOUT2                   154
#define IDS_P_O_VIDEO_UPDSIZE           154
#define IDD_ABOUT4                      155
#define IDS_P_O_VIDEO_AUTOCLOSE         155
#define IDD_ABOUT5                      156
#define IDS_P_O_VIDEO_NOSS              156
#define IDD_ABOUT6                      157
#define IDS_P_O_VIDEO_OSD               157
#define IDR_ACCELERATOR2                158
#define IDS_P_O_VIDEO_YV12              158
#define IDS_P_O_VIDEO_STOPCLOSE         159
#define IDS_P_O_VIDEO_REMOVE_FS_ON_STOP 160
#define IDD_DISPLAY                     161
#define IDS_P_O_VIDEO_AUTOOPEN          161
#define IDD_M3U_DELETE                  161
#define IDI_FILEICON2                   162
#define IDS_P_CLASSICVIS                162
#define IDI_FILEICON3                   163
#define IDS_P_IN_UNINST                 163
#define IDI_FILEICON10                  164
#define IDS_P_VIS_UNINST                164
#define IDD_ID3EDIT                     165
#define IDS_P_OUT_UNINST                165
#define IDS_P_SKINS_DELETESKIN          166
#define IDI_FILEICON5                   167
#define IDS_P_SKINS_DELETESKIN_PROMPT   167
#define IDS_P_O_VIDEO_AGRESSIVENOSS     168
#define IDI_FILEICON6                   169
#define IDS_P_PLUG_DISSEHVIS            169
#define IDS_P_PLUG_DISSEHDSP            170
#define IDS_P_PLUG_DISSEHGEN            171
#define IDS_P_SKINS_RN_ERR              172
#define IDD_LOADPRESET                  173
#define IDS_P_SKINS_RN_ERR_CAP          173
#define IDD_SAVEPRESET                  174
#define IDS_P_EQ_FILE                   174
#define IDS_P_FILE_EQ                   174
#define IDR_ACCELERATOR3                175
#define IDS_P_EQ_FILE_READ              175
#define IDD_OPENLOC                     176
#define IDR_ACCELERATOR4                176
#define IDS_P_EQ_FILE_WRITE             176
#define IDD_HTTP                        177
#define IDS_P_FILE_ALL                  177
#define IDI_FILEICON7                   178
#define IDD_PLUGIN                      178
#define IDS_NO_BOOKMARKS                178
#define IDI_FILEICON8                   179
#define IDS_ART_SEARCH_PROGRESS         179
#define IDI_FILEICON9                   180
#define IDS_ART_SEARCH_STATUS           180
#define IDI_FILEICON4                   181
#define IDS_ART_SEARCH_NOT_FOUND_TITLE  181
#define IDI_FILEICON11                  182
#define IDS_ART_SEARCH_NOT_FOUND        182
#define IDI_FILEICON12                  183
#define IDS_NO_IMAGE                    183
#define IDD_JUMPDLG                     184
#define IDS_PLAYLISTSTRING_NEW          184
#define IDD_JUMPFILEDLG                 185
#define IDS_P_LANG_PACK_DELETEWLZ       185
#define IDS_P_LANG_PACK_DELETEWLZ_PROMPT 186
#define IDS_RENAME_WLZ                  187
#define IDD_ABOUT7                      188
#define IDD_SKINS                       189
#define IDD_PLUGIN2                     190
#define IDS_P_O_VIDEO_FLIPRGB           190
#define IDR_PLMENU                      191
#define IDC_REGDLG                      191
#define IDS_SELDOWNLOADDIR              191
#define IDD_EDITENTRY                   192
#define IDS_STRING192                   192
#define IDS_LANGUAGEPACKS_MENU          192
#define IDD_OPTIONS                     193
#define IDS_ONLINESERVICE_SELDOWNLOADDIR 193
#define IDB_EQMAIN                      194
#define IDB_PANBAR                      197
#define IDB_PLEDIT                      199
#define IDS_WHATSNEW_FAIL               200
#define IDS_WINAMP_CMDLINE              201
#define IDS_SKINS_INSTALL_PROMPT        202
#define IDS_SKINS_INSTALL_HEADER        203
#define IDS_HTTP_LOAD_ERROR             204
#define IDC_MOVEMAIN                    205
#define IDS_HTTP_INIT_SOCKET            205
#define IDC_LRSCROLL                    206
#define IDS_HTTP_INIT_SOCKET_ERROR      206
#define IDC_DANGER                      207
#define IDS_HTTP_SOCKET_CREATE          207
#define IDC_NORMALCURSOR                208
#define IDS_HTTP_SOCKET_ERROR           208
#define IDC_UDSCROLL                    209
#define IDS_HTTP_RESOLVE_PROXY          209
#define IDB_ME                          210
#define IDC_RESIZE                      210
#define IDS_HTTP_RESOLVE_HOST           210
#define IDS_HTTP_RESOLVE_PROXY_ERROR    211
#define IDB_CAT                         212
#define IDS_HTTP_RESOLVE_HOST_ERROR     212
#define IDS_HTTP_CONNECT_PROXY          213
#define IDD_NEWSETUP                    213
#define IDD_HTTPGET                     214
#define IDS_HTTP_CONNECT_HOST           214
#define IDD_NEWPREFS                    215
#define IDS_HTTP_CONNECT_PROXY_ERROR    215
#define IDS_HTTP_CONNECT_HOST_ERROR     216
#define IDD_NEWFTYPES                   217
#define IDS_HTTP_SEND_REQUEST           217
#define IDD_NEWOPTIONS                  218
#define IDS_HTTP_READ_REQUEST           218
#define IDD_NEWDISPLAY                  219
#define IDS_HTTP_CONNECTION_LOST        219
#define IDS_HTTP_CONNECTION_CLOSED      220
#define IDS_HTTP_ERROR_OPEN_FILE        221
#define IDD_NEWINPUT                    222
#define IDS_HTTP_RETRIEVE_FILE_LENGTH   222
#define IDD_NEWOUTPUT                   223
#define IDS_HTTP_RETRIEVE_FILE          223
#define IDD_NEWVIS                      224
#define IDS_HTTP_FILE_INCOMPLETE        224
#define IDD_NEWDSP                      225
#define IDS_HTTP_SUCCESS                225
#define IDD_NEWGEN                      226
#define IDS_HTTP_CLOSE                  226
#define IDS_CLOSE_COUNTDOWN             227
#define IDB_MB                          228
#define IDS_HTTP_WINAMP_UPDATE_SITE     228
#define IDS_HTTP_INIT                   229
#define IDD_METRIC1                     230
#define IDS_HTTP_ABORT                  230
#define IDD_FIRSTSETUP                  231
#define IDB_EQEX                        231
#define IDS_HTML_ERROR_WRITE            231
#define IDS_HTTP_RET_FILE               232
#define IDD_FS_FILES                    233
#define IDS_HTTP_RET_FILE_PERCENT       233
#define IDD_FS_REG                      234
#define IDD_FS_REG2                     235
#define IDD_NEWSKIN                     236
#define IDD_NEWVIS2                     237
#define IDD_CLASSIC_VIS                 237
#define IDD_ABOUT8                      238
#define IDD_NEWAGENT                    239
#define IDD_NEWBOOKMARKS                240
#define IDI_UNINST                      240
#define IDS_ML_NO_PLAYLISTS             240
#define IDD_EDITBOOKMARK                241
#define IDS_ML_OPEN_PLAYLIST            241
#define IDB_BITMAP1                     242
#define IDS_ML_OPEN_VIEW_RESULTS        242
#define IDD_NEWABOUT3                   243
#define IDB_BITMAP2                     243
#define IDs_PE_CLOSE                    243
#define IDS_PE_CLOSE                    243
#define IDD_NEWABOUT4                   244
#define IDS_PE_OPEN                     244
#define IDD_NEWABOUT                    245
#define IDS_ML_EXPORT_PLAYLIST          245
#define IDD_NEWSHUFFLEOPTS              246
#define IDS_ML_CLOSE_ML                 246
#define IDS_ML_OPEN_ML                  247
#define IDB_VIDEOLOGO                   248
#define IDS_ML_MANAGE_PLAYLISTS         248
#define IDB_VIDEO                       249
#define IDS_ML_SMART_VIEW_RESULTS       249
#define IDB_EMBEDWND                    250
#define IDS_OFD_OPEN_FILES              250
#define IDS_OFD_ADD_FILES_TO_PLAYLIST   251
#define IDB_GENEX                       252
#define IDS_OFD_ALL_FILES               252
#define IDS_STATIONINFOCAPTION          253
#define IDB_TEAM                        254
#define IDS_STATIONINFO_MENU            254
#define IDD_BURN                        255
#define IDS_WINAMP_UPDATE               255
#define IDD_EDITREG                     256
#define WINAMP5_MENUBAR                 256
#define IDS_SENDTO_STR                  256
#define IDD_PREFS_CLASSICSKIN           257
#define IDS_RATEITEM_STR                257
#define IDD_CLASSIC_UI                  258
#define IDS_ERROR_DELETING              258
#define IDD_NEWTITLE                    259
#define IDS_PREFS_PLAYBACK              259
#define IDD_RENAMESKIN                  260
#define IDS_P_CLASSIC_70FPS             260
#define IDD_BROWSE_RECDLG               261
#define IDS_P_CLASSIC_35FPS             261
#define ICON_TB1                        262
#define IDS_P_CLASSIC_18FPS             262
#define IDD_NEWABOUT1EGG                263
#define IDS_P_CLASSIC_9FPS              263
#define IDS_P_PLUGIN_UNINSTALL          264
#define IDB_SPLASH2                     265
#define IDS_P_PLUGIN_UNINSTALL_CONFIRM  265
#define IDS_LANGCHANGE_TITLE            266
#define IDB_PLATE                       267
#define IDD_STATIONINFO                 267
#define IDS_P_PLAYBACK_RG_SOURCE_TRACK  267
#define IDB_BITMAP3                     268
#define IDB_SURROUND                    268
#define IDD_PLAYBACK                    268
#define IDS_P_PLAYBACK_RG_SOURCE_ALBUM  268
#define IDS_P_PLAYBACK_RG_MODE_AG       269
#define IDD_CRASHDLG                    270
#define IDB_BITMAP4                     271
#define IDB_BETA                        271
#define IDD_CRASHDG                     272
#define IDS_P_PLAYBACK_RG_MODE_AG_PC    277
#define IDS_P_PLAYBACK_RG_MODE_N        278
#define IDS_P_PLAYBACK_RG_MODE_PC       279
#define IDS_P_24BIT_WARNING             280
#define IDS_P_24BIT_WARNING_TITLE       281
#define IDS_P_PLDIRECTION_AUTO          282
#define IDS_P_PLDIRECTION_L2R           283
#define IDS_P_PLDIRECTION_R2L           284
#define IDS_P_SELECT_SKINDIR            285
#define IDS_P_SKIN_NO_INFO_FOUND        286
#define IDD_EDIT_INFO                   286
#define IDD_ADDSTUFF                    287
#define IDS_P_SKIN_ERR_RENAME           287
#define IDS_P_SKIN_ERR_RENAME_TITLE     288
#define IDS_P_TAGZ_ERROR_TITLE          289
#define IDS_P_TAGZ_NOT_INSTALLED        290
#define IDS_WINAMP_MENUITEM             301
#define IDS_ML_MISSING_FOR_BOOKMARKS    302
#define IDS_PLAYLIST_SUPPORT_NOT_INSTALLED 303
#define IDS_PLAYLIST_LOAD_ERROR         304
#define IDS_OPEN_PLAYLIST               305
#define IDS_ADD_PLAYLIST                306
#define IDS_SAVE_PLAYLIST               307
#define IDS_PLAYLIST_FILTER_STRING      308
#define IDD_NEWLANG                     317
#define IDD_FILEINFO                    318
#define IDD_FILEINFO_METADATA           319
#define IDS_CONV_SRC_EQUALS_DEST        320
#define IDD_FILEINFO_ARTWORK            320
#define IDS_CONV_DECODER_MISSING        323
#define IDS_CONV_INPUT_PLUGIN_NOT_SUPPORTING 324
#define IDS_CONV_DRM_DECODE_FAIL        325
#define IDS_CONV_ERROR_OPEN_FILE        326
#define IDS_CONV_ERROR_OPEN_ENCODER     327
#define IDS_CONV_ERROR_OPEN_DEST        328
#define IDS_NOTPRESENT                  329
#define IDS_ARTDELETE                   330
#define IDS_AREYOUSURE                  331
#define IDD_ARTDOWNLOADER               332
#define IDD_ARTDOWNLOADER_SCROLLHOST    333
#define IDD_ARTDOWNLOADER_IMAGE         334
#define IDD_ARTDOWNLOADER_SCROLLCHILD   335
#define IDS_BURN_NULLSOFT_STR           336
#define IDS_BURN_LIBRARY_INIT_FAILED    337
#define IDS_BURN_INVALID_PLAYLIST_PATH  338
#define IDS_BURN_INVALID_TEMP_PATH      339
#define IDS_BURN_INVALID_CONFIG_PATH    340
#define IDS_BURN_INVALID_CMDLINE        341
#define IDS_BURN_BAD_DRIVE_LETTER       342
#define IDS_BURN_LOAD_FROM_PLAYLIST_FAIL 343
#define IDS_BURN_CREATE_DIALOG_FAIL     344
#define IDS_BURN_UNKNOWN_ERROR          345
#define IDS_BURN_INIT_ERROR_REASON      346
#define IDS_BURN_INIT_ERROR_UNKNOWN     347
#define IDD_AUTOTAGGING                 349
#define IDD_REPLAY_GAIN_UI              351
#define IDS_PREAMP                      352
#define IDD_NEWPLUG                     352
#define IDD_NEWVIDEOOPTS                353
#define IDS_OPTIONS_MENU                353
#define IDS_DISABLE_AOT                 354
#define IDS_ENABLE_AOT                  355
#define IDS_FILE_INFO_BOX               356
#define IDS_DISABLE_DOUBLESIZE_MODE     357
#define IDS_ENABLE_DOUBLESIZE_MODE      358
#define IDS_VISUALIZATION_MENU          359
#define IDS_SEEK_TO                     360
#define IDS_VOLUME                      361
#define IDS_BALANCE                     362
#define IDS_BALANCE_CENTRE              363
#define IDS_BALANCE_LEFT                364
#define IDS_BALANCE_RIGHT               365
#define IDS_TITLE_ON_STOP               366
#define IDS_TITLE_ON_PAUSE              367
#define IDS_LANG_INSTALL_PROMPT         368
#define IDS_LANG_INSTALL_HEADER         369
#define IDS_PLEDIT_NOFILE_WSHADE        370
#define IDS_AUDIO_CD_FORMAT             371
#define IDS_CLASSIC_SKIN_NAME           372
#define IDS_CLASSIC_BASE_SKIN_VERSION   373
#define IDS_OSD_PROGRESS_TEXT           374
#define IDS_OSD_VOLUME_TEXT             375
#define IDS_REFRESH_PLAYLIST_TITLES     376
#define IDS_ATF_HAS_CHANGED             377
#define IDS_P_SELECT_LANGDIR            384
#define IDS_P_LANG_ERR_RENAME           385
#define IDS_P_LANG_ERR_RENAME_TITLE     386
#define IDS_LOCALIZATION                387
#define IDS_NO_MATCHES_FOUND            388
#define IDS_GRACENOTE_TOOLS_NOT_INSTALLED 389
#define IDS_NO_MATCH_FOUND              390
#define IDS_FAILED                      391
#define IDS_SHUFFLE_MORPH_INFO          392
#define IDS_SHUFFLE_MORPH_RATE          393
#define IDS_ADD_FOLDER                  394
#define IDS_ADD_URL                     395
#define IDS_SHOW_ALL_HISTORY            396
#define IDS_P_LNG_CHDR                  397
#define IDS_P_DISP_SPLEDPOS             398
#define IDS_IMAGE_FILES                 399
#define IDS_P_EQUALIZER                 400
#define IDS_P_4FRONT_EQ                 401
#define IDS_P_CONSTANT_Q                402
#define IDS_P_WA_FREQ_BANDS             403
#define IDS_P_ISO_FREQ_BANDS            404
#define IDS_P_REPLAY_GAIN               405
#define IDS_TRACK_GAIN_AND_ALBUM_GAIN   406
#define IDS_EQ_HZ                       407
#define IDS_EQ_DB                       408
#define IDS_EQ_KHZ                      409
#define IDS_JPEG_FILE                   410
#define IDS_PNG_FILE                    411
#define IDS_GIF_FILE                    412
#define IDS_BMP_FILE                    413
#define IDS_P_EQ_TYPE_CHANGE            414
#define IDS_P_EQ_TYPE_CHANGE_MSG        415
#define IDS_CUR_WLZ_INFO                416
#define IDS_SEL_WLZ_INFO                417
#define IDS_WA_RESTART_FOR_WLZ_NEEDED   418
#define IDS_DOWNLOADING                 419
#define IDS_COVER                       420
#define IDS_KBPS                        421
#define IDS_METADATA_ERROR              422
#define IDS_METADATA_ERROR_TITLE        423
#define IDS_CLICKHERE                   424
#define IDS_WINAMP_MEDIA_FILE           425
#define IDS_WINAMP_PLAYLIST_FILE        426
#define IDS_WINAMP_EXTENSION_INSTALLATION_FILE 427
#define IDS_WINAMP_LANGUAGE_INSTALLATION_FILE 428
#define IDS_STRING429                   429
#define IDS_WINAMP_FILE_INSTALL         429
#define IDS_WIN7TOOLBAR_TOOLTIP_PREVIOUS 430
#define IDS_WIN7TOOLBAR_TOOLTIP_PLAY    431
#define IDS_WIN7TOOLBAR_TOOLTIP_PAUSE   432
#define IDS_WIN7TOOLBAR_TOOLTIP_STOP    433
#define IDS_WIN7TOOLBAR_TOOLTIP_NEXT    434
#define IDS_SECURITY_APPLICATION_LAUNCHURL 435
#define IDS_SECURITY_TRANSPORT_EVENTS   436
#define IDS_SECURITY_TRANSPORT_METADATA 437
#define IDS_SECURITY_TRANSPORT_CONTROLS 438
#define IDS_SECURITY_PLAYER_PLAYLIST    439
#define IDS_SECURITY_PLAYER_METADATA    440
#define IDS_SECURITY_DOWNLOADER_EVENTS  441
#define IDS_SECURITY_DOWNLOADER_DOWNLOADMEDIA 442
#define IDS_SECURITY_SECURITY_AUTH      443
#define IDS_SECURITY_BOOKMARKS_AUTH     444
#define IDS_SECURITY_SKIN_AUTH          445
#define IDS_SECURITY_MEDIACORE_METADATAHOOK 446
#define IDS_SECURITY_MEDIACORE_METADATA 447
#define IDS_SECURITY_MEDIACORE_EXTENSIONS 448
#define IDS_LANG_DIR_MOVE_MESSAGE       449
#define IDS_SKIN_DIR_MOVE_MESSAGE       450
#define IDS_DIR_MOVE_ERROR              451
#define IDS_LANG_DIR_MOVE               452
#define IDS_SKIN_DIR_MOVE               453
#define IDS_NOML_SAVE_RATING            454
#define IDS_STRING455                   455
#define IDS_NOML_SAVE_RATING_TITLE      455
#define IDS_RELEASED                    456
#define IDS_EQ_TOOLTIPS                 457
#define IDS_VID_TOOLTIPS                458
#define IDS_PL_TOOLTIPS                 459
#define IDS_P_FT_EXTENSIONS_WIN8        460
#define IDS_ARTWORK_DETAILS             461
#define IDS_ORIGIN_NONE                 462
#define IDS_ORIGIN_EMBEDDED             463
#define IDS_ORIGIN_ALBUM_MATCH          464
#define IDS_ORIGIN_NFO                  465
#define IDS_ORIGIN_COVER_MATCH          466
#define IDS_ORIGIN_FOLDER_MATCH         467
#define IDS_ORIGIN_FRONT_MATCH          468
#define IDS_ORIGIN_ARTWORK_MATCH        469
#define IDS_SKINS_INSTALL_ERROR         470
#define IDS_LANG_INSTALL_ERROR          471
#define IDS_PREFS_SAFE_MODE             472
#define IDS_START_SAFE_MODE             474
#define IDS_FAILED_SAFE_MODE            475
#define IDS_FAILED_SAFE_MODE_MSG        476
#define IDS_SAFE_MODE_ALL               477
#define IDS_SAFE_MODE_NORMAL            478
#define IDS_RESTART_NORMAL              479
#define IDS_STRING194                   480
#define IDS_P_PLUG_SAFEMODE             480
#define IDS_RESTART_SAFE                481
#define IDS_STRING482                   482
#define IDS_RESTART                     482
#define IDS_NO_MODERN_SKIN_SUPPORT      483
#define IDS_SKIN_LOAD_ERROR             484
#define IDS_AUDIO_CD                    485
#define IDS_EMPTY                       486
#define IDS_BYTES                       487
#define IDS_KIB                         488
#define IDS_MIB                         489
#define IDS_GIB                         490
#define IDS_TIB                         491
#define IDS_KB                          492
#define IDS_MB                          493
#define IDS_GB                          494
#define IDS_TB                          495
#define IDS_P_SILENCE_DETECT            496
#define IDS_SHUFFLE_ON                  497
#define IDS_SHUFFLE_OFF                 498
#define IDS_REPEAT_OFF                  499
#define IDS_REPEAT_PL                   500
#define IDS_REPEAT_TRACK                501
#define IDS_MAN_ADV_ON                  502
#define IDS_MAN_ADV_ON2                 503
#define IDS_MAN_ADV_OFF                 503
#define IDS_DEF_PROG_LOAD_ERROR         504
#define IDS_RESET_URLS                  505
#define IDS_RESET_URLS_TITLE            506
#define IDS_P_DISP_BIFONT_ALT           510
#define IDS_P_FILE_ASSOC                511
#define IDS_P_FILE_ASSOC_FAILURE        512
#define IDS_P_NO_MOUSEWHEEL             513
#define IDS_P_PLUG_SAFEMODEALWAYS       514
#define IDS_NOT_LOADED                  515
#define IDS_NO_RATING                   516
#define IDS_X_ITEM_SELECTED             517
#define IDS_X_ITEMS_SELECTED            518
#define IDS_UPDATING_FILES              519
#define IDS_UPDATING_X                  520
#define IDS_ERROR_UPDATING_FILE         521
#define IDS_INFO_UPDATING_ERROR         522
#define IDS_P_O_VIDEO_AUTO_FS_ON_START  526
#define IDS_P_O_VIDEO_ENABLE            527
#define IDS_P_VIDEO_CHANGE              528
#define IDS_P_VIDEO_CHANGE_MSG          529
#define IDS_P_O_VIDEO_HIDE_PREFS        530
#define IDS_STREAMINFO                  532
#define IDS_P_SK_PROMPT                 533
#define IDS_PREFS_ARTWORK               534
#define IDS_STRING80                    535
#define IDS_UNKNOWN_MIME                536
#define IDS_RC_CHANNEL_TITLE            540
#define IDS_RC_CHANNEL_MESSAGE          541
#define IDS_RC_CHANNEL_CHECKBOX         542
#define IDC_BUFFERS_NUMBUFS             1001
#define IDC_PREFS_VIDEO_FLIPRGB         1001
#define IDC_EDIT_ARTIST                 1002
#define IDC_CHECK_ARTIST                1003
#define IDC_8BIT                        1004
#define IDC_CHECK_TITLE                 1004
#define IDC_16BIT                       1005
#define IDC_RG_ASK                      1005
#define IDC_CHECK_ALBUM                 1005
#define IDC_PREFS_SPLASH                1006
#define IDC_RG_ALBUM                    1006
#define IDC_CHECK_TRACK                 1006
#define IDC_WA_CURSORS                  1007
#define IDC_RG_ALL                      1007
#define IDC_CHECK_GENRE                 1007
#define IDC_PREFS_SYSTRAY               1008
#define IDC_CHECK_YEAR                  1008
#define IDC_EDIT_TITLE                  1009
#define IDC_EDIT_ALBUM                  1010
#define IDC_PREBUFSLIDER                1011
#define IDC_EDIT_TRACK                  1011
#define IDC_EDIT_GENRE                  1012
#define IDC_ALLOWMI                     1013
#define IDC_EDIT_YEAR                   1013
#define IDC_FORMAT                      1014
#define IDC_CHECK_COMMENT               1014
#define IDC_RFL                         1015
#define IDC_USEID3                      1015
#define IDC_EDIT_COMMENT                1015
#define IDC_REGFILETYPES                1016
#define IDC_MINST                       1016
#define IDC_USEID6                      1016
#define IDC_CHECK_DISC                  1016
#define IDC_USEID4                      1017
#define IDC_EDIT_DISC                   1017
#define IDC_USEID5                      1018
#define IDC_SPIN1                       1018
#define IDC_CHECK_ALBUMARTIST           1018
#define IDC_EQ1                         1019
#define IDC_SPIN3                       1019
#define IDC_EDIT_ALBUMARTIST            1019
#define IDC_EQ2                         1020
#define IDC_SPIN2                       1020
#define IDC_CHECK_PUBLISHER             1020
#define IDC_EQ3                         1021
#define IDC_STATIC66                    1021
#define IDC_EDIT_PUBLISHER              1021
#define IDC_EQ4                         1022
#define IDC_CHECK_COMPOSER              1022
#define IDC_EQ5                         1023
#define IDC_EDIT_COMPOSER               1023
#define IDC_EQ6                         1024
#define IDC_CHECK_CATEGORY              1024
#define IDC_EQ7                         1025
#define IDC_EDIT_CATEGORY               1025
#define IDC_EQ8                         1026
#define IDC_CHECK_BPM                   1026
#define IDC_EQ9                         1027
#define IDC_EDIT_BPM                    1027
#define IDC_EQ10                        1028
#define IDC_CHECK_RATING                1028
#define IDC_EQ_ENABLED                  1029
#define IDC_EQ_CLOSE                    1030
#define IDC_PLAYLIST_LISTBOX            1031
#define IDC_EQ_RESET                    1031
#define IDC_EQ11                        1031
#define IDC_TAGZ_HELP                   1031
#define IDC_PLAYLIST_ADDMP3             1032
#define IDC_EQ_ZERO                     1032
#define IDC_PLAYLIST_ADDPLAYLIST        1033
#define IDC_PLAYLIST_REMOVEMP3          1034
#define IDC_PLAYLIST_CROP               1035
#define IDC_TAGZ_DEFAULT                1035
#define IDC_PLAYLIST_ADDDIR             1036
#define IDC_PLAYLIST_CLEAR              1037
#define IDC_PLAYLIST_EDITID3            1038
#define IDC_PLAYLIST_ADDLOC             1039
#define ID_PE_REMOVE                    1041
#define IDC_AUTOSCROLL                  1041
#define IDC_PLAYLIST_MOVEBAR            1042
#define IDC_SA                          1043
#define IDC_OSC                         1044
#define IDC_NOVIS                       1045
#define IDC_STEREO                      1046
#define IDC_MONO                        1047
#define IDC_REVSTEREO                   1048
#define IDC_FULLRATE                    1049
#define IDC_HALFRATE                    1050
#define IDC_AMP_README                  1054
#define IDC_OUTPUTDEV                   1056
#define IDC_EQVOL                       1058
#define IDC_PLAYLIST_SORT               1059
#define IDC_PLAYLIST_INVERT             1060
#define IDC_PLAYLIST_REVERSE            1061
#define IDC_PLAYLIST_LOADLIST           1062
#define IDC_PLAYLIST_SAVELIST           1063
#define IDC_ENC_CONFIG                  1063
#define IDC_SPECFALLOFF                 1064
#define IDC_PLAYLIST_RANDOMIZE          1064
#define IDC_SPECREFRESH                 1065
#define IDC_SPECSCALE                   1066
#define IDC_TASKBAR                     1067
#define IDC_SYSTRAY                     1068
#define IDC_SYSTRAYANDTASK              1069
#define IDC_OSCSCALE                    1070
#define IDC_NONE                        1070
#define IDC_FILETYPES_ICONSCROLL        1073
#define IDC_PREFS_PRIORITY_CLASS        1074
#define IDC_FILETYPES_ICONSCROLL2       1074
#define IDC_PREFS_PRIORITY_OUTPUT       1075
#define IDC_PREFS_PRIORITY_DECODE       1076
#define IDC_FILETYPES_ICON              1077
#define IDC_ID3_TITLE                   1078
#define IDC_FILETYPES_ICON2             1078
#define IDC_ID3_ARTIST                  1079
#define IDC_ID3_ALBUM                   1080
#define IDC_ID3_COMMENT                 1081
#define IDC_ID3_YEAR                    1082
#define IDC_ID3_GENRE                   1083
#define IDC_ID3_FN                      1084
#define IDC_FN                          1084
#define IDC_ARTIST                      1087
#define IDC_ALBUM                       1088
#define IDC_YEAR                        1089
#define IDC_EQ_SAVE                     1090
#define IDC_GENRE                       1090
#define IDC_EQ_SAVEMPX                  1091
#define IDC_COMMENT                     1091
#define IDC_STATION                     1091
#define IDC_EQ_DELETE                   1092
#define IDC_COMPOSER                    1092
#define IDC_EQ_LOAD                     1093
#define IDC_EQ_PRESET                   1094
#define IDC_EQ_AUTOLOAD                 1095
#define IDC_PE_TIME                     1096
#define IDC_TRACK                       1097
#define IDC_LOADEQLIST                  1099
#define IDC_ALBUM_ARTIST                1099
#define IDC_DISC                        1100
#define IDC_SAVEPRESET_EDIT             1101
#define IDC_PUBLISHER                   1101
#define IDC_NORMALANALYZER              1102
#define IDC_SPLASHIMG                   1103
#define IDC_FIREANALYZER                1103
#define IDC_BUFFER_ALL                  1104
#define IDC_LINEANALYZER                1104
#define IDC_BUF_SFAST                   1106
#define IDC_SNAP                        1108
#define IDC_ADDSTART                    1109
#define IDC_MAINPARENT                  1109
#define IDC_REMSTART                    1110
#define IDC_URL                         1110
#define IDC_HIGHLIGHT                   1110
#define IDC_ADDICON                     1110
#define IDC_SAVE                        1111
#define IDC_ADDDESKTOP                  1111
#define IDC_PLAY_URL                    1111
#define IDC_VOLUMEENABLED               1112
#define IDC_ADDQL                       1112
#define IDC_PANREV                      1113
#define IDC_VISLIB                      1113
#define IDC_VISMOD                      1114
#define IDC_ALTVOL                      1114
#define IDC_VISTEST                     1115
#define IDC_VISCONF                     1116
#define IDC_VISPRIO                     1117
#define IDC_SNDLIB                      1118
#define IDC_BLOCKSIZE                   1118
#define IDC_DSPLIB                      1118
#define IDC_VISSTOP                     1118
#define IDC_MPEGINFO                    1119
#define IDC_DSPMOD                      1119
#define IDC_MINUTES                     1120
#define IDC_DSPCONF                     1120
#define IDC_SECONDS                     1121
#define IDC_GENLIB                      1121
#define IDC_TRACKLEN                    1122
#define IDC_SELBOX                      1122
#define IDC_GENCONF                     1122
#define IDC_AUTOEXEC                    1123
#define IDC_OUTPUTINTERP                1124
#define IDC_HQ                          1125
#define IDC_DISVIS                      1126
#define IDC_ID3FORMAT                   1127
#define IDC_TIPS                        1128
#define IDC_PLAYLIST_BOX                1129
#define IDC_ADD_BOX                     1130
#define IDC_REMOVE_BOX                  1131
#define IDC_LENGTHTEXT                  1132
#define IDC_MISC_BOX                    1133
#define IDC_SYSTRAY_ICON                1134
#define IDC_SYSTRAY_SCROLLER            1135
#define IDC_BUFMAX                      1136
#define IDC_CLUTTERBAR                  1137
#define IDC_ADDFILES                    1138
#define IDC_DIRCONTEXT                  1139
#define IDC_SM                          1140
#define IDC_PLUGINLINK                  1141
#define IDC_SM2                         1141
#define IDC_WINAMPLINK                  1142
#define IDC_PLUGINLINK2                 1142
#define IDC_SM3                         1142
#define IDC_WINAMPLINK2                 1143
#define IDC_WINAMPLINK3                 1144
#define IDC_AFTERSEEK                   1144
#define IDC_WINAMPLINK4                 1145
#define IDC_RESIZETHINGY                1145
#define IDC_WINAMPLINK5                 1146
#define IDC_PE_ADD                      1146
#define IDC_WINAMPLINK6                 1147
#define IDC_WINAMPLINK7                 1148
#define IDC_NEWDLG                      1148
#define IDC_TTIPS                       1148
#define IDC_WINAMPLINK9                 1149
#define IDC_PROXYSTR                    1149
#define IDC_RANDOM                      1150
#define IDC_WINAMPLINK8                 1150
#define IDC_INPUTS                      1151
#define IDC_CONF                        1152
#define IDC_ABOUT                       1153
#define IDC_ABOUTTEXT                   1153
#define IDC_DEFEXT                      1154
#define IDC_ABOUT3                      1154
#define IDC_UNINSTDSP                   1154
#define IDC_LICINFO                     1155
#define IDC_OUTCONF                     1155
#define IDC_FTYPE_LIST                  1156
#define IDC_OUTABOUT                    1156
#define IDC_CONF2                       1156
#define IDC_USEINFO                     1156
#define IDC_SELALL                      1157
#define IDC_ABOUT2                      1157
#define IDC_SELNONE                     1158
#define IDC_ABOUTIMG                    1159
#define IDC_REFRESH                     1159
#define IDC_CHDIR                       1160
#define IDC_SELALL2                     1161
#define IDC_BUTTON1                     1162
#define IDC_SELALL3                     1162
#define IDC_NAME                        1163
#define IDC_BUTTON4                     1163
#define IDC_REG                         1164
#define IDC_OUTPLUG                     1164
#define IDC_BUTTON5                     1164
#define IDC_EDITBOOK                    1165
#define IDC_OLD                         1167
#define IDC_NEW                         1168
#define IDC_PLNUMS                      1168
#define IDC_PLCHILD                     1169
#define IDC_PLZEROPAD                   1169
#define IDC_EQDSIZE                     1170
#define IDC_OUTPUTS                     1171
#define IDC_CONVERT1                    1172
#define IDC_CONVERT2                    1173
#define IDC_TREE1                       1173
#define IDC_SCROLLTITLE                 1174
#define IDC_UPDATE                      1175
#define IDC_NIFTY                       1175
#define IDC_KEEPONSCREEN                1175
#define IDC_SHOWPLEDITPOS               1175
#define IDC_FLUSHCACHE                  1176
#define IDC_PLFONTSIZE                  1177
#define IDC_SAFEMODE                    1177
#define IDC_PLFONTSIZE_TEXT             1178
#define IDC_AOVD                        1179
#define IDC_SNAPW                       1180
#define IDC_STATUS                      1180
#define IDC_MANUALPLAYLISTADVANCE       1180
#define IDC_STATUS2                     1181
#define IDC_DROPAOTFS                   1181
#define IDC_POS_IN_SONGTICKER           1181
#define IDC_STATIC_NO_IPOD              1181
#define IDC_RADIO1                      1182
#define IDC_INET1                       1182
#define IDC_NO_MOUSEWHEEL               1182
#define IDC_INET2                       1183
#define IDC_CHLANG                      1184
#define IDC_INET3                       1185
#define IDC_RECT                        1186
#define IDC_DSPDIR                      1188
#define IDC_VISDIR                      1189
#define IDC_CD                          1193
#define IDC_RSTART                      1194
#define IDC_ALLTYPES                    1194
#define IDC_FIRSTNAME                   1195
#define IDC_LASTNAME                    1196
#define IDC_AGE                         1197
#define IDC_COUNTRY                     1198
#define IDC_GENDER                      1199
#define IDC_EMAIL                       1200
#define IDC_EMAILUSE                    1201
#define IDC_BIFONT                      1202
#define IDC_BIFONT_ALT                  1203
#define IDC_EDIT1                       1206
#define IDC_EDIT2                       1207
#define IDC_EXT                         1207
#define IDC_REGKEY                      1207
#define IDC_COMBO1                      1208
#define IDC_EDIT3                       1208
#define IDC_TONAME                      1208
#define IDC_COMBO2                      1209
#define IDC_EDIT5                       1209
#define IDC_REGSTATUS                   1209
#define IDC_BUTTON2                     1211
#define IDC_ALLOW                       1211
#define IDC_SET_DEF_PROGRAM             1211
#define IDC_NEWVERCHECK                 1212
#define IDC_BUTTON3                     1212
#define IDC_NEWVERCHK                   1213
#define IDC_NEWVERCHECK2                1213
#define IDC_BUTTON_COPY                 1213
#define IDC_CLEARLANG                   1214
#define IDC_BUTTON_PASTE                1214
#define IDC_NEWVERCHECK_RC              1214
#define IDC_RECENT                      1215
#define IDC_BUTTON6                     1215
#define IDC_BUTTON_SAVEAS               1215
#define IDC_URL_NEW                     1216
#define IDC_RADIO2                      1217
#define IDC_RADIO3                      1218
#define IDC_RADIO4                      1219
#define IDC_RADIO5                      1220
#define IDC_RADIO6                      1221
#define IDC_CHECK1                      1222
#define IDC_RADIO7                      1223
#define IDC_CHECK5                      1223
#define IDC_RADIO8                      1224
#define IDC_CHECK6                      1224
#define IDC_SLIDER1                     1225
#define IDC_SAFEMODEALWAYS              1225
#define IDC_SLIDER2                     1226
#define IDC_SLIDER3                     1227
#define IDC_RRATE                       1228
#define IDC_RADIO9                      1229
#define IDC_PLUGINVERS                  1229
#define IDC_RADIO10                     1230
#define IDC_SPLB                        1230
#define IDC_RADIO11                     1231
#define IDC_CHECK2                      1231
#define IDC_RADIO12                     1232
#define IDC_CHECK3                      1232
#define IDC_RADIO13                     1233
#define IDC_CHECK4                      1233
#define IDC_24BIT                       1233
#define IDC_LIST1                       1234
#define IDC_EDIT4                       1235
#define IDC_TITLE                       1237
#define IDC_FILE                        1238
#define IDC_ALLOWMETRICS                1246
#define IDC_TEXT                        1247
#define IDC_MYPLAY                      1248
#define IDC_NC                          1249
#define IDC_RUNWINAMP                   1249
#define IDC_REGTEXT                     1250
#define IDC_PREFS_SHUFFLE_MORPH_RATE    1251
#define IDC_UNINST                      1252
#define IDC_PREFS_VIDEO_VSYNC           1253
#define IDC_PREFS_VIDEO_ADJASP          1254
#define IDC_PREFS_VIDEO_OVERLAYS        1255
#define IDC_PREFS_VIDEO_UPDSIZE         1256
#define IDC_PREFS_VIDEO_AUTOCLOSE       1257
#define IDC_PREFS_VIDEO_NOSS            1258
#define IDC_PREFS_VIDEO_OSD             1259
#define IDC_SCREENSHAPE1                1260
#define IDC_SCREENSHAPE2                1261
#define IDC_PREFS_VIDEO_YV12            1262
#define IDC_USE_SCREENSHAPE             1263
#define IDC_PREFS_VIDEO_STOPCLOSE       1264
#define IDC_PREFS_VIDEO_REMOVE_FS_ON_STOP 1265
#define IDC_PREFS_VIDEO_AUTOOPEN        1266
#define IDC_RENAME_SKIN                 1267
#define IDC_PREFS_VIDEO_ENABLE          1267
#define IDC_DELETE_SKIN                 1268
#define IDC_PREFS_VIDEO_AUTO_FS_ON_START 1268
#define IDC_UNINSTVIS                   1269
#define IDC_PREFS_VIDEO_HIDE_PREFS      1269
#define IDC_UNINSTINPUT                 1270
#define IDC_UNINSTOUT                   1271
#define IDC_PROXY_ONLY_PORT_80          1272
#define IDC_WEBLINK                     1273
#define IDC_KEY                         1274
#define IDC_WEBLINK2                    1274
#define IDC_REGISTER                    1275
#define IDC_WEBLINK3                    1275
#define IDC_PROGRESS1                   1276
#define IDC_WEBLINK4                    1276
#define IDC_PROGRESS2                   1277
#define IDC_ABORT                       1278
#define IDC_TAB1                        1279
#define IDC_PLUGINLABEL                 1280
#define IDR_RESERVED_GENFF_1            1281
#define IDR_RESERVED_GENFF_2            1282
#define IDR_RESERVED_GENFF_3            1283
#define IDR_RESERVED_GENFF_4            1284
#define IDR_RESERVED_GENFF_5            1285
#define IDR_RESERVED_GENFF_6            1286
#define IDC_WATEXT1                     1287
#define IDC_WATEXT2                     1288
#define IDC_CUSTOMFONT                  1289
#define IDC_NOCUSTOMFONT                1290
#define IDC_STATIC_CUSTOMFONT           1291
#define IDC_FRAME1                      1292
#define IDC_PLDIRECTION                 1292
#define IDC_ITEXT1                      1293
#define IDC_ASCII                       1294
#define IDC_STATIC1                     1295
#define IDC_STATIC2                     1296
#define IDC_RECYCLE                     1297
#define IDC_STATIC3                     1297
#define IDC_PREFS_VIDEO_CONTRAST        1298
#define IDC_PREFS_VIDEO_BRIGHTNESS      1299
#define IDC_STATIC4                     1300
#define IDC_DELETEM3U                   1302
#define IDC_NODELETE                    1303
#define IDC_PREFS_STATIONINFO_AUTOSHOW  1304
#define IDC_PREFS_STATIONINFO_AUTOSIZE  1305
#define IDC_PREFS_STATIONINFO_AUTOSHOW2 1306
#define IDC_PREFS_STATIONINFO_AUTOHIDE  1306
#define IDC_TITLELBL                    1306
#define IDC_WORKLBL                     1307
#define IDC_SURROUND                    1308
#define IDC_DITHER                      1309
#define IDC_WORKLBL4                    1310
#define IDC_PROGRESS3                   1310
#define IDC_REPLAY_GROUP                1310
#define IDC_REPLAY_MODE                 1311
#define IDC_REPLAY_SOURCE               1312
#define IDC_REPLAY_PREFERRED            1313
#define IDC_STATIC_SOURCE               1314
#define IDC_STATIC_MODE                 1315
#define IDC_USE_REPLAY                  1316
#define IDC_NON_REPLAYGAIN              1317
#define IDC_NON_REPLAYGAIN_DB           1318
#define IDC_STATIC_ADJ                  1319
#define IDC_ATF_INFO                    1320
#define IDC_RENAME_LNG_PACK             1321
#define IDC_DELETE_LNG_PACK             1322
#define IDC_SELECT_LNG_PACK             1323
#define IDC_PRIORITY                    1324
#define IDC_VER_COMBO                   1325
#define IDC_ABOUT_SEARCH                1326
#define IDC_FORMATINFO                  1327
#define IDC_ARTLIST                     1328
#define IDC_BUTTON_DOWNLOAD             1330
#define IDC_REPLAYGAIN                  1331
#define IDC_COMBO_ARTTYPE               1332
#define IDC_BUTTON_LOAD                 1333
#define IDC_BUTTON_PASTENEW             1334
#define IDC_BUTTON_CHANGE               1335
#define IDC_BUTTON_DELETE               1336
#define IDC_STATIC_FRAME                1337
#define IDC_ARTHOLDER                   1338
#define IDC_BPM                         1339
#define IDC_STATIC_TRACK                1340
#define IDC_STATIC_DISC                 1341
#define IDC_STATIC_BPM                  1342
#define IDC_STATIC_TITLE                1343
#define IDC_CHECK_DIRECTOR              1343
#define IDC_STATIC_ARTIST               1344
#define IDC_EDIT_DIRECTOR               1344
#define IDC_STATIC_ALBUM                1345
#define IDC_CHECK_PRODUCER              1345
#define IDC_STATIC_ALBUM_ARTIST         1346
#define IDC_EDIT_PRODUCER               1346
#define IDC_STATIC_YEAR                 1347
#define IDC_CHECK_PODCAST               1347
#define IDC_STATIC_GENRE                1348
#define IDC_EDIT_PODCAST_CHANNEL        1348
#define IDC_STATIC_COMMENT              1349
#define IDC_STATIC_STATION              1349
#define IDC_CHECK_PODCAST_CHANNEL       1349
#define IDC_STATIC_COMPOSER             1350
#define IDC_STATIC_PUBLISHER            1351
#define IDC_IMAGE                       1354
#define IDC_COMBO_RATING                1354
#define IDC_IMGTEXT                     1355
#define IDC_PLACEHOLDER                 1356
#define IDC_SELECT                      1357
#define IDC_AUTOTAG                     1358
#define IDC_MOUSE_SCROLL_DOUBLE_LINES   1359
#define IDC_PLSCROLL                    1360
#define IDC_SHUFFLE_HELP                1361
#define IDC_LANG_ID_STR                 1362
#define IDC_GN_FILEID                   1363
#define IDC_GN_EXTDATA                  1364
#define IDC_EQ                          1365
#define IDC_FREQ_BANDS                  1366
#define IDC_STATIC_EQ                   1367
#define IDC_STATIC_FREQ                 1368
#define IDC_LIMITER                     1369
#define IDB_EQMAIN_ISO                  1370
#define IDC_EQ_RESTART_TEXT             1370
#define IDC_LANG_RESTART_TEXT           1371
#define IDR_ACCELERATOR_EQ              1371
#define IDC_SEARCHAGAIN                 1372
#define IDR_ACCELERATOR_PL              1372
#define IDC_SEARCHREFINE_ARTIST         1373
#define IDR_ACCELERATOR_MAIN            1373
#define IDC_SEARCHREFINE_ALBUM          1374
#define IDR_ACCELERATOR_GLOBAL          1374
#define IDC_LANG_INFO_STR               1374
#define IDC_SEARCHREFINE_YEAR           1375
#define IDC_SECURITY_DESCRIPTION        1375
#define IDC_ALLOW_ALWAYS                1376
#define IDD_JSAPI2_AUTHORIZATION2       1376
#define IDC_DENY                        1377
#define IDB_PNG1                        1377
#define IDB_OSD                         1377
#define IDC_TRUST_CHECK                 1378
#define IDD_DIALOG1                     1378
#define IDD_ABOUT_TRANSLATION           1378
#define IDC_JSAPI2_ALL                  1379
#define IDC_JSAPI2_THIS                 1380
#define IDC_JSAPI2_ONCE                 1381
#define IDC_HELPTEXT                    1383
#define IDC_BUTTON_ALLOW                1384
#define IDC_BUTTON_DENY                 1385
#define IDC_MESSAGEICON                 1386
#define IDC_MESSAGE                     1387
#define IDC_APPLYTOALL                  1388
#define IDI_TBICON1                     1388
#define IDC_SEPARATOR                   1389
#define IDI_TBICON2                     1389
#define IDC_REPLAYGAIN_PREAMP           1390
#define IDI_TBICON3                     1390
#define IDC_REPLAYGAIN_PREAMP_DB        1391
#define IDI_TBICON4                     1391
#define IDC_REPLAY_ADJ                  1392
#define IDI_ICON5                       1392
#define IDI_TBICON5                     1392
#define IDC_AUTHOR_HOMEPAGE             1393
#define IDD_WIN8_FTYPES                 1394
#define IDC_AUTHOR_HOMEPAGE2            1394
#define IDC_REGNAME                     1394
#define IDC_REGGROUP1                   1395
#define IDD_SILENCE_DETECT              1395
#define IDD_CMDLINE                     1396
#define IDC_STATIC8                     1396
#define IDC_STATIC7                     1397
#define IDD_PREFS_FAIL                  1397
#define IDC_STATIC5                     1398
#define IDR_ATF_HTML                    1398
#define IDC_REGGROUP2                   1399
#define IDD_FILEINFO_STREAMDATA         1399
#define IDC_STATIC10                    1400
#define IDC_STATIC9                     1401
#define IDC_RGAS                        1402
#define IDC_RGC                         1403
#define IDC_RELEASED                    1404
#define IDC_SHOW_LNG_PACK               1405
#define IDC_USE_SILENCE_DETECT          1406
#define IDC_CMDLINE                     1407
#define IDC_VIDEO_GROUP1                1412
#define IDC_VIDEO_GROUP2                1413
#define IDC_VIDEO_GROUP3                1414
#define IDC_VIDEO_RESTART               1415
#define IDC_STATIC_URL                  1417
#define IDC_EXTRA_METADATA              1418
#define IDC_STATIC_PLAY_URL             1419
#define IDC_PREFS_VIDEO_LOGO            1420
#define IDC_SKIN_INSTALL_PROMPT         1421
#define IDC_LANG_INSTALL_PROMPT         1422
#define IDS_P_O_RECYCLE                 32768
#define WINAMP_FILE_QUIT                40001
#define WINAMP_OPTIONS_PREFS            40012
#define WINAMP_OPTIONS_AOT              40019
#define WINAMP_FILE_REPEAT              40022
#define WINAMP_FILE_SHUFFLE             40023
#define WINAMP_HIGH_PRIORITY            40025
#define WINAMP_FILE_PLAY                40029
#define WINAMP_OPTIONS_EQ               40036
#define WINAMP_OPTIONS_ELAPSED          40037
#define WINAMP_OPTIONS_REMAINING        40038
#define WINAMP_OPTIONS_PLEDIT           40040
#define WINAMP_HELP_ABOUT               40041
#define WINAMP_MAINMENU                 40043
#define WINAMP_BUTTON1                  40044
#define WINAMP_BUTTON2                  40045
#define WINAMP_BUTTON3                  40046
#define WINAMP_BUTTON4                  40047
#define WINAMP_BUTTON5                  40048
#define WINAMP_VOLUMEUP                 40058
#define WINAMP_VOLUMEDOWN               40059
#define WINAMP_FFWD5S                   40060
#define WINAMP_REW5S                    40061
#define WINAMP_NEXT_WINDOW              40063
#define WINAMP_OPTIONS_WINDOWSHADE      40064
#define WINAMP_OPTIONS_WINDOWSHADE_GLOBAL 40065
#define WINAMP_BROWSER_ID               40113
#define WINAMP_BUTTON1_SHIFT            40144
#define WINAMP_BUTTON2_SHIFT            40145
#define WINAMP_BUTTON3_SHIFT            40146
#define WINAMP_BUTTON4_SHIFT            40147
#define WINAMP_BUTTON5_SHIFT            40148
#define WINAMP_BUTTON1_CTRL             40154
#define WINAMP_BUTTON2_CTRL             40155
#define WINAMP_BUTTON3_CTRL             40156
#define WINAMP_BUTTON4_CTRL             40157
#define WINAMP_BUTTON5_CTRL             40158
#define WINAMP_OPTIONS_DSIZE            40165
#define IDC_SORT_FILENAME               40166
#define IDC_SORT_FILETITLE              40167
#define IDC_SORT_ENTIREFILENAME         40168
#define IDC_SELECTALL                   40169
#define IDC_SELECTNONE                  40170
#define IDC_SELECTINV                   40171
#define IDM_EQ_LOADPRE                  40172
#define IDM_EQ_LOADMP3                  40173
#define IDM_EQ_LOADDEFAULT              40174
#define IDM_EQ_SAVEPRE                  40175
#define IDM_EQ_SAVEMP3                  40176
#define IDM_EQ_SAVEDEFAULT              40177
#define IDM_EQ_DELPRE                   40178
#define IDM_EQ_DELMP3                   40180
#define IDC_PLAYLIST_PLAY               40184
#define WINAMP_FILE_LOC                 40185
#define WINAMP_OPTIONS_EASYMOVE         40186
#define WINAMP_FILE_DIR                 40187
#define WINAMP_EDIT_ID3                 40188
#define WINAMP_TOGGLE_AUTOSCROLL        40189
#define WINAMP_VISSETUP                 40190
#define WINAMP_PLGSETUP                 40191
#define WINAMP_VISPLUGIN                40192
#define WINAMP_JUMP                     40193
#define WINAMP_JUMPFILE                 40194
#define WINAMP_JUMP10FWD                40195
#define WINAMP_JUMP10BACK               40197
#define WINAMP_PREVSONG                 40198
#define WINAMP_OPTIONS_EXTRAHQ          40200
#define ID_PE_NEW                       40201
#define ID_PE_OPEN                      40202
#define ID_PE_SAVE                      40203
#define ID_PE_SAVEAS                    40204
#define ID_PE_SELECTALL                 40205
#define ID_PE_INVERT                    40206
#define ID_PE_NONE                      40207
#define ID_PE_ID3                       40208
#define ID_PE_S_TITLE                   40209
#define ID_PE_S_FILENAME                40210
#define ID_PE_S_PATH                    40211
#define ID_PE_S_RANDOM                  40212
#define ID_PE_S_REV                     40213
#define ID_PE_CLEAR                     40214
#define ID_PE_MOVEUP                    40215
#define ID_PE_MOVEDOWN                  40216
#define WINAMP_SELSKIN                  40219
#define WINAMP_VISCONF                  40221
#define ID_PE_NONEXIST                  40222
#define ID_PE_DELETEFROMDISK            40223
#define ID_PE_CLOSE                     40224
#define WINAMP_VIS_SETOSC               40226
#define WINAMP_VIS_SETANA               40227
#define WINAMP_VIS_SETOFF               40228
#define WINAMP_VIS_DOTSCOPE             40229
#define WINAMP_VIS_LINESCOPE            40230
#define WINAMP_VIS_SOLIDSCOPE           40231
#define WINAMP_VIS_NORMANA              40233
#define WINAMP_VIS_FIREANA              40234
#define WINAMP_VIS_LINEANA              40235
#define WINAMP_VIS_NORMVU               40236
#define WINAMP_VIS_SMOOTHVU             40237
#define WINAMP_VIS_FULLREF              40238
#define WINAMP_VIS_FULLREF2             40239
#define WINAMP_VIS_FULLREF3             40240
#define WINAMP_VIS_FULLREF4             40241
#define WINAMP_OPTIONS_TOGTIME          40242
#define EQ_ENABLE                       40244
#define EQ_AUTO                         40245
#define EQ_PRESETS                      40246
#define WINAMP_VIS_FALLOFF0             40247
#define WINAMP_VIS_FALLOFF1             40248
#define WINAMP_VIS_FALLOFF2             40249
#define WINAMP_VIS_FALLOFF3             40250
#define WINAMP_VIS_FALLOFF4             40251
#define WINAMP_VIS_PEAKS                40252
#define ID_LOAD_EQF                     40253
#define ID_SAVE_EQF                     40254
#define ID_PE_ENTRY                     40255
#define ID_PE_SCROLLUP                  40256
#define ID_PE_SCROLLDOWN                40257
#define WINAMP_MAIN_WINDOW              40258
#define WINAMP_VIS_PFALLOFF0            40259
#define WINAMP_VIS_PFALLOFF1            40260
#define WINAMP_VIS_PFALLOFF2            40261
#define WINAMP_VIS_PFALLOFF3            40262
#define WINAMP_VIS_PFALLOFF4            40263
#define ID_PE_TOP                       40264
#define ID_PE_BOTTOM                    40265
#define WINAMP_OPTIONS_WINDOWSHADE_PL   40266
#define EQ_INC1                         40267
#define EQ_INC2                         40268
#define EQ_INC3                         40269
#define EQ_INC4                         40270
#define EQ_INC5                         40271
#define EQ_INC6                         40272
#define EQ_INC7                         40273
#define EQ_INC8                         40274
#define EQ_INC9                         40275
#define EQ_INC10                        40276
#define EQ_INCPRE                       40277
#define EQ_DECPRE                       40278
#define EQ_DEC1                         40279
#define EQ_DEC2                         40280
#define EQ_DEC3                         40281
#define EQ_DEC4                         40282
#define EQ_DEC5                         40283
#define EQ_DEC6                         40284
#define EQ_DEC7                         40285
#define EQ_DEC8                         40286
#define EQ_DEC9                         40287
#define EQ_DEC10                        40288
#define ID_PE_SCUP                      40289
#define ID_PE_SCDOWN                    40290
#define WINAMP_REFRESHSKIN              40291
#define ID_PE_PRINT                     40292
#define ID_PE_EXTINFO                   40293
#define WINAMP_PLAYLIST_ADVANCE         40294
#define WINAMP_VIS_LIN                  40295
#define WINAMP_VIS_BAR                  40296
#define WINAMP_OPTIONS_MINIBROWSER      40298
#define MB_FWD                          40299
#define MB_BACK                         40300
#define MB_RELOAD                       40301
#define MB_OPENMENU                     40302
#define MB_OPENLOC                      40303
#define WINAMP_NEW_INSTANCE             40305
#define MB_UPDATE                       40309
#define WINAMP_OPTIONS_WINDOWSHADE_EQ   40310
#define EQ_PANLEFT                      40313
#define EQ_PANRIGHT                     40314
#define WINAMP_GETMORESKINS             40316
#define WINAMP_VIS_OPTIONS              40317
#define WINAMP_PE_SEARCH                40318
#define ID_PE_BOOKMARK                  40319
#define WINAMP_EDIT_BOOKMARKS           40320
#define WINAMP_MAKECURBOOKMARK          40321
#define ID_MAIN_PLAY_BOOKMARK_NONE      40322
#define ID_MAIN_PLAY_AUDIOCD            40323
#define ID_MAIN_PLAY_AUDIOCD2           40324
#define ID_MAIN_PLAY_AUDIOCD3           40325
#define ID_MAIN_PLAY_AUDIOCD4           40326
#define ID_MAIN_PLAY_AUDIOCD_SEP        40327
#define WINAMP_OPTIONS_VIDEO            40328
#define ID_VIDEOWND_ZOOMFULLSCREEN      40329
#define ID_VIDEOWND_ZOOM100             40330
#define ID_VIDEOWND_ZOOM200             40331
#define ID_VIDEOWND_ZOOM50              40332
#define ID_VIDEOWND_VIDEOOPTIONS        40333
#define WINAMP_MINIMIZE                 40334
#define ID_PE_FONTBIGGER                40335
#define ID_PE_FONTSMALLER               40336
#define WINAMP_VIDEO_TOGGLE_FS          40337
#define WINAMP_VIDEO_TVBUTTON           40338
#define WINAMP_LIGHTNING_CLICK          40339
#define ID_FILE_ADDTOLIBRARY            40344
#define ID_HELP_HELPTOPICS              40347
#define ID_HELP_GETTINGSTARTED          40348
#define ID_HELP_WINAMPFORUMS            40349
#define ID_PLAY_VOLUMEUP                40351
#define ID_PLAY_VOLUMEDOWN              40352
#define ID_PEFILE_OPENPLAYLISTFROMLIBRARY_NOPLAYLISTSINLIBRARY 40355
#define ID_PEFILE_ADDFROMLIBRARY        40356
#define ID_PEFILE_CLOSEPLAYLISTEDITOR   40357
#define ID_PEPLAYLIST_PLAYLISTPREFERENCES 40358
#define ID_MLFILE_NEWPLAYLIST           40359
#define ID_MLFILE_LOADPLAYLIST          40360
#define ID_MLFILE_SAVEPLAYLIST          40361
#define ID_MLFILE_ADDMEDIATOLIBRARY     40362
#define ID_MLFILE_CLOSEMEDIALIBRARY     40363
#define ID_MLVIEW_NOWPLAYING            40364
#define ID_MLVIEW_LOCALMEDIA_ALLMEDIA   40366
#define ID_MLVIEW_LOCALMEDIA_AUDIO      40367
#define ID_MLVIEW_LOCALMEDIA_VIDEO      40368
#define ID_MLVIEW_PLAYLISTS_NOPLAYLISTINLIBRARY 40369
#define ID_MLVIEW_INTERNETRADIO         40370
#define ID_MLVIEW_INTERNETTV            40371
#define ID_MLVIEW_LIBRARYPREFERENCES    40372
#define ID_MLVIEW_DEVICES_NOAVAILABLEDEVICE 40373
#define ID_MLFILE_IMPORTCURRENTPLAYLIST 40374
#define ID_MLVIEW_MEDIA                 40376
#define ID_MLVIEW_PLAYLISTS             40377
#define ID_MLVIEW_MEDIA_ALLMEDIA        40377
#define ID_MLVIEW_DEVICES               40378
#define ID_FILE_SHOWLIBRARY             40379
#define ID_FILE_CLOSELIBRARY            40380
#define ID_POST_PLAY_PLAYLIST           40381
#define ID_VIS_NEXT                     40382
#define ID_VIS_PREV                     40383
#define ID_VIS_RANDOM                   40384
#define ID_MANAGEPLAYLISTS              40385
#define ID_PREFS_SKIN_SWITCHTOSKIN      40386
#define ID_PREFS_SKIN_DELETESKIN        40387
#define ID_PREFS_SKIN_RENAMESKIN        40388
#define ID_VIS_FS                       40389
#define ID_VIS_CFG                      40390
#define ID_VIS_MENU                     40391
#define ID_VIS_SET_FS_FLAG              40392
#define ID_PE_SHOWPLAYING               40393
#define WINAMP_FILE_MANUALPLADVANCE     40395
#define ID_RATING5                      40396
#define ID_RATING4                      40397
#define ID_RATING3                      40398
#define ID_RATING2                      40399
#define ID_RATING1                      40400
#define ID_RATING0                      40401
#define ID_PL_RATING5                   40402
#define ID_PL_RATING4                   40403
#define ID_PL_RATING3                   40404
#define ID_PL_RATING2                   40405
#define ID_ACCELERATOR40405             40405
#define ID_PL_RATING1                   40406
#define ID_PL_RATING0                   40407
#define ID_VID_AUDIO0                   40408
#define ID_VID_AUDIO1                   40409
#define ID_VID_AUDIO2                   40410
#define ID_VID_AUDIO3                   40411
#define ID_VID_AUDIO4                   40412
#define ID_VID_AUDIO5                   40413
#define ID_VID_AUDIO6                   40414
#define ID_VID_AUDIO7                   40415
#define ID_VID_AUDIO8                   40416
#define ID_VID_AUDIO9                   40417
#define ID_VID_AUDIO10                  40418
#define ID_VID_AUDIO11                  40419
#define ID_VID_AUDIO12                  40420
#define ID_VID_AUDIO13                  40421
#define ID_VID_AUDIO14                  40422
#define ID_VID_AUDIO15                  40423
#define ID_VID_VIDEO0                   40424
#define ID_VID_VIDEO1                   40425
#define ID_VID_VIDEO2                   40426
#define ID_VID_VIDEO3                   40427
#define ID_VID_VIDEO4                   40428
#define ID_VID_VIDEO5                   40429
#define ID_VID_VIDEO6                   40430
#define ID_VID_VIDEO7                   40431
#define ID_VID_VIDEO8                   40432
#define ID_VID_VIDEO9                   40433
#define ID_VID_VIDEO10                  40434
#define ID_VID_VIDEO11                  40435
#define ID_VID_VIDEO12                  40436
#define ID_VID_VIDEO13                  40437
#define ID_VID_VIDEO14                  40438
#define ID_VID_VIDEO15                  40439
#define ID_SONGTITLE_SEND               40446
#define WINAMP_TOGGLE_LIBRARY           40451
#define ID_Menu                         40454
#define ID_PREFS_LANG                   40457
#define ID_LANG_SWITCHTOLANGUAGEPACK    40458
#define ID_LANG_RENAMELANGUAGEPACK      40459
#define ID_LANG_DELETELANGUAGEPACK      40460
#define ID_HELP_FEEDBACK                40464
#define ID_VIDEOWND_VERTICALLYFLIP      40465
#define ID_FILE_ADDCURRENTPLAYLISTTOLIBRARY 40466
#define ID_PE_FFOD                      40468
#define ID_PE_FONTRESET                 40469
#define ID_PE_EDIT_SEL                  40470
#define IDS_LOCALIZED_HOMEPAGE          65531
#define IDS_AUTHOR_HOMEPAGE2            65532
#define IDS_AUTHOR_HOMEPAGE             65533

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        537
#define _APS_NEXT_COMMAND_VALUE         40471
#define _APS_NEXT_CONTROL_VALUE         1423
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
