//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by in_cdda.rc
//
#define IDS_NULLSOFT_CD_PLUGIN_OLD      1
#define IDS_QUERYING                    2
#define IDC_REMOVE                      3
#define IDS_NOT_FOUND                   3
#define IDC_GETCDDB                     4
#define IDS_PROCESSING                  4
#define IDS_CDDB_NOT_INSTALLED          5
#define IDS_SUCCESS                     6
#define IDS_CLOSE                       7
#define IDS_INITIALIZING                8
#define IDS_ABORTING                    9
#define IDS_UNLIMITED                   10
#define IDS_PURCHASE_WINAMP_PRO_PROMPT  11
#define IDS_WINAMP_PRO_FEATURE          12
#define IDS_ARTIST                      13
#define IDS_TITLE                       14
#define IDS_ALBUM_ARTIST                15
#define IDS_NULLSOFT_CD_PLUGIN2         16
#define IDS_ABOUT                       17
#define IDS_CD_CURRENTLY_IN_USE         18
#define IDS_DRIVE_IN_USE                19
#define IDS_DRIVE_NOT_FOUND             20
#define IDS_CD_NOT_PRESENT              21
#define IDS_CANNOT_PLAY_TRACK           22
#define IDS_STRING0                     23
#define IDS_CDDA_AUDIO_TRACKS           23
#define IDS_RIPPNG                      24
#define IDS_RIPPING                     24
#define IDS_TRACK_X                     25
#define IDS_UNKNOWN                     26
#define IDS_UNKNOWN_ARTIST              27
#define IDS_FAMILY_STRING               28
#define IDS_ABOUT_TEXT                  29
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     102
#define IDD_MULSEL                      103
#define IDD_SERVSEL                     104
#define IDS_ABORT                       109
#define IDS_CDDB_PROGRESS_CONNECTING    110
#define IDS_CDDB_PROGRESS_SENDING       111
#define IDS_CDDB_PROGRESS_RECEIVING     112
#define IDS_CDDB_PROGRESS_WAITING       113
#define IDS_CDDB_PROGRESS_CANCELLED     114
#define IDS_CDDB_PROGRESS_COMPLETED     115
#define IDS_CDDB_E_BUSY                 116
#define IDS_CDDB_E_FAIL                 117
#define IDS_CDDB_E_BADTOC               118
#define IDS_REASON                      119
#define IDS_FOUND_MULTIPLE              120
#define IDS_RESOLVING                   121
#define IDS_SUBMITTINGDISC              122
#define IDS_FOUND_EXACT                 123
#define IDS_SUBMITNEW                   124
#define IDS_SUBMITDISC_TITLE            125
#define IDS_SUBMITTING                  126
#define IDS_OPENING                     127
#define IDS_FUZZYDISC_TITLE             128
#define IDS_ACCEPT                      129
#define IDS_LOOKUPRESULT_TITLE          130
#define IDS_SUBMIT_OFFER                131
#define IDS_CDDB_E_ABORT                132
#define IDS_CDTEXT                      133
#define IDD_DIALOG3                     134
#define IDD_MUSICID                     134
#define IDS_TRACK                       135
#define IDS_COMPOSER                    136
#define IDD_PREFS_CDRIP                 232
#define IDD_CDDB_PROGRESS               233
#define IDD_CDTEXT                      234
#define IDC_SAMPLE                      1000
#define IDC_STATUS                      1001
#define ID_ABORTBABY                    1002
#define IDC_SERV                        1003
#define IDC_EMAIL                       1004
#define IDC_CDDB                        1005
#define IDC_EMAIL2                      1006
#define IDC_LIST1                       1006
#define IDC_RAS                         1006
#define IDC_TRACKLIST                   1006
#define IDC_LV_EXT                      1006
#define IDC_BUTTON1                     1007
#define IDC_CDTEXT                      1007
#define IDC_CDDBICON                    1008
#define IDC_CDDBICON2                   1009
#define IDC_TITLE                       1010
#define IDC_ARTIST                      1011
#define IDC_TRACKS                      1012
#define IDC_EDITTEXT                    1013
#define IDC_CDDBNOTE                    1014
#define IDC_PUBLISHER                   1014
#define IDC_DIGITAL                     1015
#define IDC_GENRE                       1015
#define IDC_YEAR                        1016
#define IDC_VERITAS                     1016
#define IDC_COMBO1                      1019
#define IDC_PROGRESS                    1020
#define IDC_STATUS_TEXT                 1021
#define IDC_EDITARTIST                  1022
#define IDC_CHECK1                      1024
#define IDC_COMPILATION                 1024
#define IDC_BUTTON2                     1025
#define IDC_EDIT                        1025
#define IDC_SUBMIT                      1025
#define IDC_CLOSE                       1027
#define IDC_DISC                        1030
#define IDC_DISCS                       1031
#define IDC_NOTES                       1032
#define IDC_LABEL                       1033
#define IDC_EDIT1                       1034
#define IDC_LBL_CAPTION                 1035
#define IDC_EDIT2                       1035
#define IDC_COMPOSER                    1035
#define IDC_ALBUM                       1036
#define IDC_LBL_STATUS                  1039
#define IDC_PRG_STATUS                  1040
#define IDC_LBL_REASON                  1041
#define IDC_EDIT_GRACENOTE              1042
#define IDC_LOOKUP                      1043
#define IDC_BUTTON4                     1044
#define IDC_USE                         1044
#define IDS_NULLSOFT_CD_PLUGIN          65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
