//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDS_AVS                         0
#define IDS_WINAMP_AVS_DISPLAY          1
#define IDS_AVS_EDITOR                  2
#define IDS_DOCK_IN_AVS_EDITOR          3
#define IDS_LEARNING                    5
#define IDS_GOT_IT                      6
#define IDS_NO_EFFECT_SETTING_SELECTED  7
#define IDS_SHIFT_X                     8
#define IDS_ALL                         9
#define IDS_SAME_AS_WINAMP              10
#define IDS_IDLE                        11
#define IDS_LOWEST                      12
#define IDS_NORMAL                      13
#define IDS_HIGHEST                     14
#define IDS_NO_SUITABLE_MODES_FOUND     15
#define IDS_CHOOSE_A_VIDEO_MODE         16
#define IDS_FULLSCREEN                  17
#define IDS_AVS_FILTER_STRING           18
#define IDS_SAVE_PRESET                 19
#define IDS_ERROR_SAVING_PRESET         20
#define IDS_PRESET_TOO_LARGE            21
#define IDS_OUT_OF_MEMORY               22
#define IDS_EVAL_CODE_STATS_ETC         23
#define IDS_MOVE_HERE                   24
#define IDS_ERROR_TREE_INCONSISTANCY    25
#define IDS_CRITICAL_ERROR_OCCURRED     26
#define IDS_DISPLAY                     27
#define IDS_FULLSCREEN_SETTINGS         28
#define IDS_PRESET_HOTKEYS              29
#define IDS_BEAT_DETECTION              30
#define IDS_TRANSITIONS                 31
#define IDS_EFFECT_LIST                 32
#define IDS_PRESETS                     33
#define IDS_LOAD_PRESET                 34
#define IDS_STILL_INITIALIZING_PREVIOUS_PRESET 35
#define IDS_MAIN                        36
#define IDS_ERROR_CREATING_DDRAW_OBJECT 37
#define IDS_ABOUT_STRING                38
#define IDS_ABOUT_AVS                   39
#define IDS_REQUIRES_2_9_PLUS           40
#define IDS_AVS_ERROR                   41
#define IDS_NO_MMX_SUPPORT              42
#define IDS_STRING43                    43
#define IDS_SHIFT_                      43
#define IDS_AVS_CRITICAL_ERROR          44
#define IDS_CHANNEL_SHIFT               45
#define IDS_COLOR_REDUCTION             46
#define IDS_MULTIPLIER                  47
#define IDS_HOLDEN04_VIDEO_DELAY        48
#define IDS_HOLDEN05_MULTI_DELAY        49
#define IDS_CURRENT_PRESET_EDITED_SAVE_BEFORE_LOAD 50
#define IDS_STRING51IDS_CURRENT_PRESET_EDITED_SAVE_BEFORE_NEW 51
#define IDS_CURRENT_PRESET_EDITED_SAVE_BEFORE_NEW 51
#define IDS_AVS_PRESET_MODIFIED         52
#define IDS_ERROR_CREATING_WINDOW       53
#define IDS_CANNOT_GO_FULLSCREEN_WHEN_VIDEO_PLAYING 54
#define IDS_AVS_FULLSCREEN              55
#define IDS_FULLSCREEN_FPS_ON           56
#define IDS_FULLSCREEN_FPS_OFF          57
#define IDS_RANDOM_PRESETS_ON           58
#define IDS_RANDOM_PRESETS_OFF          59
#define IDS_SAVED_TO                    60
#define IDS_LOADED_FROM                 61
#define IDS_ERROR_LOADING_FROM          62
#define IDS_X_BEATX                     63
#define IDS_BEAT                        63
#define IDS_CURRENT                     64
#define IDS_BUFFER_X                    65
#define IDS_BUMP_LIGHT_POSITION         66
#define IDS_4X_RED_BRIGHTNESS_2X_GREEN_1X_BLUE 67
#define IDS_SOLARIZATION                68
#define IDS_DOUBLE_SOLARIZATION         69
#define IDS_INVERSE_SOLARIZATION_SOFT   70
#define IDS_BIG_BRIGHTNESS_ON_BEAT      71
#define IDS_BIG_BRIGHTNESS_ON_BEAT_INTERPOLATIVE 72
#define IDS_PULSING_BRIGHTNESS_BEAT_INTERPOLATIVE 73
#define IDS_ROLLING_SOLARIZATION_BEAT_INTERPOLATIVE 74
#define IDS_ROLLING_TONE_BEAT_INTERPOLATIVE 75
#define IDS_RANDOM_INVERSE_TONE_SWITCH_ON_BEAT 76
#define IDS_COLOR_MODIFIER              77
#define IDS_DYNAMIC_DISTANCE_MODIFIER   78
#define IDS_RANDOM_ROTATE               79
#define IDS_RANDOM_DIRECTION            80
#define IDS_IN_AND_OUT                  81
#define IDS_UNSPUN_KALEIDA              82
#define IDS_ROLLING_GRIDLEY             83
#define IDS_6_WAY_OUTSWIRL              84
#define IDS_WAVY                        85
#define IDS_SMOOTH_ROTOBLITTER          86
#define IDS_DYNAMIC_MOVEMENT            87
#define IDS_REPLACE                     88
#define IDS_ADDITIVE                    89
#define IDS_MAXIMUM_BLEND               90
#define IDS_50_50_BLEND                 91
#define IDS_SUBTRACTIVE_BLEND_1         92
#define IDS_SUBTRACTIVE_BLEND_2         93
#define IDS_MULTIPLY_BLEND              94
#define IDS_ADJUSTABLE_BLEND            95
#define IDS_XOR                         96
#define IDS_MINIMUM_BLEND               97
#define IDS_DYNAMIC_SHIFT               98
#define IDS_SPIRAL                      99
#define IDS_3D_SCOPE_DISH               100
#define IDD_DIALOG1                     101
#define IDS_ROTATING_BOW_THING          101
#define IDB_TAB_NORMAL                  102
#define IDS_VERTICAL_BOUNCING_SCOPE     102
#define IDB_TAB_SELECTED                103
#define IDD_CFG_SIMPLE                  103
#define IDS_SPIRAL_GRAPH_FUN            103
#define IDB_TAB_HILITED                 104
#define IDD_CFG_FADE                    104
#define IDS_ALTERNATING_DIAGONAL_SCOPE  104
#define IDD_CFG_BLT                     105
#define IDS_VIBRATING_WORM              105
#define IDD_CFG_DOTPLANE                106
#define IDS_WANDERING_SIMPLE            106
#define IDD_CFG_OSCSTAR                 107
#define IDS_FLITTERBUG                  107
#define IDD_CFG_NFC                     108
#define IDS_SPIROSTAR                   108
#define IDD_CFG_BLUR                    109
#define IDS_EXPLODING_DAISY             109
#define IDD_CFG_BSPIN                   110
#define IDS_SWIRLIE_DOTS                110
#define IDD_GCFG_BEAT                   111
#define IDS_SWEEP                       111
#define IDD_GCFG_DISP                   112
#define IDS_WHIPLASH_SPIRAL             112
#define IDD_CFG_PARTS                   113
#define IDS_SUPERSCOPE                  113
#define IDD_GCFG_ABOUT                  114
#define IDS_DRAW_X_BANDS                114
#define IDD_CFG_FILTER                  115
#define IDS_NONE                        115
#define IDD_CFG_ROTBLT                  116
#define IDS_SLIGHT_FUZZIFY              116
#define IDC_CFG_SVP                     117
#define IDS_SHIFT_ROTATE_LEFT           117
#define IDD_CFG_COLORFADE               118
#define IDS_BIG_SWIRL_OUT               118
#define IDD_CFG_CONTRASTENHANCE         119
#define IDS_MEDIUM_SWIRL                119
#define IDD_CFG_ROTSTAR                 120
#define IDS_SUNBURSTER                  120
#define IDD_CFG_OSCRING                 121
#define IDS_SWIRL_TO_CENTER             121
#define IDD_CFG_TRANS                   122
#define IDB_BITMAP1                     122
#define IDS_BLOCKY_PARTIAL_OUT          122
#define IDD_GCFG_PRESET                 123
#define IDS_SWIRLING_AROUND_BOTH_WAYS   123
#define IDD_CFG_SCAT                    124
#define IDS_BUBBLING_OUTWARD            124
#define IDD_CFG_DOTGRID                 125
#define IDS_BUBBLING_OUTWARD_WITH_SWIRL 125
#define IDD_CFG_STACK                   126
#define IDS_5_POINTED_DISTRO            126
#define IDS_TUNNELING                   127
#define IDD_DIALOG2                     127
#define IDD_CFG_WATER                   128
#define IDS_BLEEDIN                     128
#define IDD_CFG_COMMENT                 129
#define IDS_SHIFTED_BIG_SWIRL_OUT       129
#define IDD_CFG_BRIGHTNESS              130
#define IDS_PSYCHOTIC_BEAMING_OUTWARD   130
#define IDD_CFG_INTERLEAVE              131
#define IDS_COSINE_RADIAL_3_WAY         131
#define IDD_CFG_GRAIN                   132
#define IDS_SPINNY_TUBE                 132
#define IDD_CFG_CLEAR                   133
#define IDS_RADIAL_SWIRLIES             133
#define IDD_CFG_BUMP                    134
#define IDS_SWILL                       134
#define IDD_CFG_MIRROR                  135
#define IDS_GRIDLEY                     135
#define IDD_CFG_STARFIELD               136
#define IDS_GRAPEVINE                   136
#define IDD_CFG_TEXT                    137
#define IDS_QUADRANT                    137
#define IDD_BUMP_HELP                   138
#define IDS_6_WAY_KALAEIDA              138
#define IDD_CFG_MOSAIC                  139
#define IDS_USER_DEFINED                139
#define IDD_CFG_WATERBUMP               140
#define IDR_MENU1                       140
#define IDS_MOVEMENT                    140
#define IDD_CFG_AVI                     141
#define IDS_IGNORE                      141
#define IDD_CFG_UNKN                    142
#define IDS_MAXIMUM                     142
#define IDD_GCFG_TRANS                  143
#define IDS_50_50                       143
#define IDD_CFG_BPM                     144
#define IDS_EVERY_OTHER_LINE            144
#define IDD_GCFG_BPM                    145
#define IDS_EVERY_OTHER_PIXEL           145
#define IDD_CFG_PICTURE                 146
#define IDS_ADJUSTABLE                  146
#define IDD_CFG_DDM                     147
#define IDS_MULTIPLY                    147
#define IDD_CFG_SSCOPE                  148
#define IDS_BUFFER                      148
#define IDD_CFG_INVERT                  149
#define IDS_MINIMUM                     149
#define IDD_CFG_ONETONE                 150
#define IDS_CROSS_DISSOLVE              150
#define IDD_CFG_TIMESCOPE               151
#define IDS_RANDOM                      151
#define IDD_CFG_LIST                    152
#define IDS_L_R_PUSH                    152
#define IDD_CFG_LISTROOT                153
#define IDS_R_L_PUSH                    153
#define IDD_CFG_LINEMODE                154
#define IDS_T_B_PUSH                    154
#define IDD_GCFG_TRANSITIONS            155
#define IDS_B_T_PUSH                    155
#define IDD_CFG_LASER_CONE              156
#define IDS_9_RANDOM_BLOCKS             156
#define IDD_CFG_LASER_BEATHOLD          157
#define IDS_SPLIT_L_R_PUSH              157
#define IDD_CFG_LASER_LINE              158
#define IDS_L_R_CENTER_PUSH             158
#define IDD_GCFG_FS                     159
#define IDS_L_R_CENTER_SQUEEZE          159
#define IDD_CFG_INTERF                  160
#define IDS_L_R_WIPE                    160
#define IDD_CFG_SHIFT                   161
#define IDS_R_L_WIPE                    161
#define IDD_CFG_LASER_TRANSFORM         162
#define IDS_T_B_WIPE                    162
#define IDD_CFG_DMOVE                   163
#define IDS_B_T_WIPE                    163
#define IDD_CFG_FASTBRIGHT              164
#define IDS_DOT_DISSOLVE                164
#define IDD_CFG_COLORMOD                165
#define IDS_LOADING_WAIT                165
#define IDD_EVAL_HELP                   166
#define IDS_LOADING                     166
#define IDD_DEBUG                       167
#define IDS_ERROR_LOADING_X             167
#define IDD_CFG_CHANSHIFT               168
#define IDS_BUILTIN_ID                  168
#define IDD_CFG_COLORREDUCTION          169
#define IDS_CONFIG_SIZE                 169
#define IDD_CFG_MULT                    170
#define IDS_GENERAL                     170
#define IDD_CFG_MULTIDELAY              171
#define IDS_OPERATORS                   171
#define IDD_CFG_VIDEODELAY              172
#define IDS_FUNCTIONS                   172
#define IDS_STRING173                   173
#define IDS_CONSTANTS                   173
#define IDR_BUMP_LIGHT_POSITION         174
#define IDS_BEAT2                       174
#define IDS_BEATS                       174
#define IDR_COLOR_MODIFIER              175
#define IDS_SUBTRACTIVE_1               175
#define IDR_DYNAMIC_DISTANCE_MODIFIER   176
#define IDS_SUBTRACTIVE_2               176
#define IDR_DYNAMIC_MOVEMENT            177
#define IDS_STRING177                   177
#define IDS_RENDER_AVI                  177
#define IDR_DYNAMIC_SHIFT               178
#define IDS_TRANS_BLITTER_FEEDBACK      178
#define IDR_SUPERSCOPE                  179
#define IDS_TRANS_BLUR                  179
#define IDR_MOVEMENT                    180
#define IDS_MISC_CUSTOM_BPM             180
#define IDR_EFFECT_LIST                 181
#define IDS_TRANS_BRIGHTNESS            181
#define IDR_HELP_1                      182
#define IDS_RENDER_BASS_SPIN            182
#define IDR_HELP_2                      183
#define IDS_TRANS_BUMP                  183
#define IDR_HELP_3                      184
#define IDS_TRANS_CHANNEL_SHIFT         184
#define IDR_HELP_4                      185
#define IDS_RENDER_CLEAR_SCREEN         185
#define IDS_TRANS_COLORFADE             186
#define IDS_TRANS_COLOR_REDUCTION       187
#define IDS_TRANS_COLOR_CLIP            188
#define IDS_MISC_COMMENT                189
#define IDS_TRANS_COLOR_MODIFIER        190
#define IDS_TRANS_DYNAMIC_DISTANCE_MODIFIER 191
#define IDS_TRANS_DYNAMIC_MOVEMENT      192
#define IDS_RENDER_DOT_FOUNTAIN         193
#define IDS_RENDER_DOT_GRID             194
#define IDS_RENDER_DOT_PLANE            195
#define IDS_TRANS_FADEOUT               196
#define IDS_TRANS_FAST_BRIGHTNESS       197
#define IDS_TRANS_GRAIN                 198
#define IDS_TRANS_INTERFERENCES         199
#define IDS_TRANS_INTERLEAVE            200
#define IDS_TRANS_INVERT                201
#define IDS_MISC_SET_RENDER_MODE        202
#define IDS_TRANS_MIRROR                203
#define IDS_TRANS_MOSAIC                204
#define IDS_TRANS_MULTI_DELAY           205
#define IDS_TRANS_MULTIPLIER            206
#define IDS_RENDER_ONBEAT_CLEAR         207
#define IDS_TRANS_UNIQUE_TONE           208
#define IDS_RENDER_RING                 209
#define IDS_RENDER_OSCILLOSCOPE_STAR    210
#define IDS_RENDER_MOVING_PARTICLE      211
#define IDS_RENDER_PICTURE              212
#define IDS_TRANS_ROTO_BLITTER          213
#define IDS_RENDER_ROTATING_STARS       214
#define IDS_TRANS_SCATTER               215
#define IDS_TRANS_DYNAMIC_SHIFT         216
#define IDS_RENDER_SIMPLE               217
#define IDS_RENDER_SUPERSCOPE           218
#define IDS_MISC_BUFFER_SAVE            219
#define IDS_RENDER_STARFIELD            220
#define IDS_RENDER_SVP_LOADER           221
#define IDS_RENDER_TEXT                 222
#define IDS_RENDER_TIMESCOPE            223
#define IDS_TRANS_MOVEMENT              224
#define IDS_UNKNOWN_RENDER_OBJECT       225
#define IDS_TRANS_VIDEO_DELAY           226
#define IDS_TRANS_WATER                 227
#define IDS_TRANS_WATER_BUMP            228
#define IDS_OVERLAY_MODE                229
#define IDC_EFFECTS                     1000
#define IDC_ENABLED                     1001
#define IDC_FBCLEAR                     1002
#define IDC_DISSOC                      1003
#define IDC_DAMP                        1004
#define OBJ_COMBO                       1005
#define IDC_EFFECTRECT                  1006
#define IDC_BIN                         1007
#define IDC_RRECT                       1007
#define IDC_ADDITIVE                    1008
#define IDC_RADIUS                      1009
#define IDC_REMSEL                      1010
#define IDC_5050                        1011
#define IDC_LIB                         1012
#define IDC_DEFRENDBLEND                1012
#define IDC_REPLACE                     1013
#define IDC_RANDOM_DROP                 1014
#define IDC_ADD                         1015
#define IDC_LEVELS                      1015
#define IDC_DROP_LEFT                   1016
#define IDC_LEVELTEXT                   1016
#define IDC_ADAPT                       1017
#define IDC_MOVEUP                      1018
#define IDC_GBR                         1018
#define IDC_X8                          1018
#define IDC_RED                         1019
#define IDC_BRG                         1019
#define IDC_X4                          1019
#define IDC_HORIZONTAL1                 1020
#define IDC_RBG                         1020
#define IDC_DROP_CENTER                 1021
#define IDC_BGR                         1021
#define IDC_X05                         1021
#define IDC_PERSIST                     1022
#define IDC_GRB                         1022
#define IDC_X025                        1022
#define IDC_MOVEDOWN                    1023
#define IDC_X0125                       1023
#define IDC_GREEN                       1024
#define IDC_XI                          1024
#define IDC_HORIZONTAL2                 1025
#define IDC_XS                          1025
#define IDC_DROP_RIGHT                  1026
#define IDC_PERSIST_TITLE               1027
#define IDC_LOAD                        1028
#define IDC_LEFT                        1029
#define IDC_BLUE                        1030
#define IDC_X                           1031
#define IDC_MAX                         1032
#define IDC_X2                          1032
#define IDC_VERTICAL1                   1033
#define IDC_X3                          1033
#define IDC_DROP_TOP                    1034
#define IDC_SAVE                        1035
#define IDC_RIGHT                       1036
#define IDC_BRED                        1037
#define IDC_Y                           1038
#define IDC_VERTICAL2                   1039
#define IDC_Y2                          1039
#define IDC_DROP_MIDDLE                 1040
#define IDC_CLEAR                       1041
#define IDC_LC                          1042
#define IDC_BGREEN                      1043
#define IDC_LC2                         1043
#define IDC_DROP_BOTTOM                 1044
#define IDC_RC                          1045
#define IDC_CLONESEL                    1046
#define IDC_BBLUE                       1047
#define IDC_SPEED                       1048
#define IDC_DOTS                        1049
#define IDC_SA                          1050
#define IDC_DISTANCE                    1051
#define IDC_METHOD_SLUDGE               1052
#define IDC_PERSIST_TEXT1               1053
#define IDC_LINES                       1054
#define IDC_SLIDER1                     1055
#define IDC_EXCLUDE                     1056
#define IDC_SLIDER7                     1056
#define IDC_STAT                        1057
#define IDC_PERSIST_TEXT2               1058
#define IDC_LINES2                      1059
#define IDC_BLEND                       1060
#define IDC_SLIDER3                     1061
#define IDC_SMOOTH                      1062
#define IDC_BUTTON1                     1063
#define IDC_LINES3                      1064
#define IDC_BUTTON4                     1064
#define IDC_SLIDER4                     1065
#define IDC_SOLID                       1066
#define IDC_SLOWER                      1067
#define IDC_ONBEAT2                     1068
#define IDC_RATIO                       1069
#define IDC_SLIDER2                     1070
#define IDC_RSTACK_BLEND1               1070
#define IDC_X_RATIO                     1071
#define IDC_RSTACK_BLEND2               1071
#define IDC_CHECK1                      1072
#define IDC_RSTACK_BLEND3               1072
#define IDC_RSTACK_BLEND4               1073
#define IDC_BUTTON3                     1073
#define IDC_CHECK8                      1073
#define IDC_Y_RATIO                     1074
#define IDC_NEWADAPT                    1074
#define IDC_RSTACK_BLEND5               1074
#define IDC_C1                          1075
#define IDC_RSTACK_BLEND6               1075
#define IDC_INVERTDEPTH                 1075
#define IDC_SLIDER5                     1076
#define IDC_C2                          1076
#define IDC_RSTACK_BLEND7               1076
#define IDC_OFF                         1076
#define IDC_C3                          1077
#define IDC_RSTACK_BLEND8               1077
#define IDC_BANDS                       1077
#define IDC_C4                          1078
#define IDC_FPS                         1078
#define IDC_BANDTXT                     1078
#define IDC_RSTACK_BLEND9               1078
#define IDC_C5                          1079
#define IDC_SLIDER6                     1079
#define IDC_TREE1                       1079
#define IDC_RSTACK_BLEND10              1079
#define IDC_INSLIDE                     1080
#define IDC_RSTACK_BLEND11              1080
#define IDC_TRI                         1081
#define IDC_OUTSLIDE                    1081
#define IDC_ALPHASLIDE                  1081
#define IDC_RSTACK_BLEND12              1081
#define IDC_HLEFT                       1082
#define IDC_CBBUF2                      1082
#define IDC_BLENDSLIDE                  1082
#define IDC_CHECK6                      1083
#define IDC_CBBUF1                      1083
#define IDC_CHECK7                      1084
#define IDC_INVERT2                     1084
#define IDC_EFNAME                      1085
#define IDC_DEFAULTBLEND                1085
#define IDC_HCENTER                     1086
#define IDC_BPP_CONV                    1086
#define IDC_TRANSITION                  1087
#define IDC_WRAP                        1087
#define IDC_HRIGHT                      1088
#define IDC_L_FRAME                     1088
#define IDC_EDIT1                       1089
#define IDC_L_TEXT1                     1089
#define IDC_VTOP                        1090
#define IDC_EDIT2                       1090
#define IDC_VCENTER                     1091
#define IDC_EDIT3                       1091
#define IDC_L_MASK                      1091
#define IDC_VBOTTOM                     1092
#define IDC_EDIT4                       1092
#define IDC_BKGND_RENDER                1092
#define IDC_COMBO1                      1093
#define IDC_SETDESKTOPCOLOR             1093
#define IDC_EDIT9                       1093
#define IDC_CHOOSEFONT                  1094
#define IDC_OVERLAYCOLOR                1094
#define IDC_EDIT66                      1094
#define IDC_T                           1095
#define IDC_COMBO2                      1095
#define IDC_DEFOVERLAYCOLOR             1095
#define IDC_EDIT7                       1095
#define IDC_EDIT                        1096
#define IDC_EDIT5                       1096
#define IDC_LEFTCH                      1097
#define IDC_EDIT6                       1097
#define IDC_BLANKS                      1098
#define IDC_NOMOVEMENT                  1098
#define IDC_EDIT10                      1098
#define IDC_RIGHTCH                     1099
#define IDC_USE_OVERLAY                 1099
#define IDC_EDIT11                      1099
#define IDC_RANDOMPOS                   1100
#define IDC_THREAD_PRIORITY             1100
#define IDC_EDIT12                      1100
#define IDC_MIDCH                       1101
#define IDC_L_PROJZONES                 1101
#define IDC_EDIT13                      1101
#define IDC_OUTLINE                     1102
#define IDC_L_SUPPRESS_DIALOGS          1102
#define IDC_EDIT14                      1102
#define IDC_TOP                         1103
#define IDC_L_ACTIVEOUTPUT              1103
#define IDC_EDIT15                      1103
#define IDC_HSHIFT                      1104
#define IDC_FR1                         1104
#define IDC_EDIT16                      1104
#define IDC_CENTER                      1105
#define IDC_FR2                         1105
#define IDC_VSHIFT                      1106
#define IDC_L_SUPPRESS_OUTPUT           1106
#define IDC_BOTTOM                      1107
#define IDC_L_SYNC                      1107
#define IDC_OUTLINESIZE                 1108
#define IDC_EDIT8                       1108
#define IDC_NUMCOL                      1109
#define IDC_RANDWORD                    1110
#define IDC_RADIO1                      1111
#define IDC_DEFOUTCOL                   1112
#define IDC_NEWRESET                    1112
#define IDC_BELOW                       1112
#define IDC_RADIO7                      1112
#define IDC_RADIO2                      1113
#define IDC_ABOVE                       1113
#define IDC_ANGLE                       1114
#define IDC_NEAR                        1114
#define IDC_HRESET                      1115
#define IDC_RADIO3                      1116
#define IDC_CHECK2                      1117
#define IDC_VRESET                      1118
#define IDC_CHECK9                      1118
#define IDC_RADIO4                      1119
#define IDC_PLAIN                       1120
#define IDC_RADIO5                      1121
#define IDC_SAVEFB                      1121
#define IDC_ROUNDDOWN                   1121
#define IDC_CHECK3                      1122
#define IDC_RESTFB                      1122
#define IDC_ROUNDUP                     1122
#define IDC_RADIO6                      1123
#define IDC_INVERT1                     1123
#define IDC_CHECK10                     1123
#define IDC_LIST1                       1124
#define IDC_CHECK11                     1124
#define IDC_CHECK5                      1125
#define IDC_CHECK4                      1126
#define IDC_SHADOW                      1127
#define IDC_CLEAR2                      1128
#define IDC_BUTTON2                     1129
#define IDC_VERSTR                      1130
#define IDC_OSC                         1131
#define IDC_SPEC                        1132
#define IDC_STATGRAIN                   1133
#define IDC_CLEARFIRSTFRAME             1134
#define IDC_DEPTH                       1135
#define IDC_SETTINGS                    1136
#define IDC_NUMSTARS                    1137
#define IDC_ONBEAT                      1138
#define IDC_SCROLLBAR1                  1139
#define IDC_SPDCHG                      1140
#define IDC_QUALITY2                    1141
#define IDC_TRANS_SLIDER                1142
#define IDC_DEPTH2                      1143
#define IDC_TRANS_CHECK                 1144
#define IDC_SPDDUR                      1145
#define IDC_AVS_VER                     1146
#define IDC_BEATDUR                     1147
#define IDC_DONT_MIN_AVS                1148
#define IDC_CODE1                       1149
#define IDC_BPMSTD                      1150
#define IDC_HELPBTN                     1151
#define IDC_BPMADV                      1152
#define IDC_CODE2                       1153
#define IDC_STICKY                      1154
#define IDC_CODE3                       1155
#define IDC_ONLYSTICKY                  1155
#define IDC_MOREADAPT                   1156
#define IDC_DOT                         1157
#define IDC_TEXT                        1158
#define IDC_WAVE                        1158
#define IDC_DEFCOL                      1159
#define IDC_QUALITY                     1160
#define IDC_BPM                         1161
#define IDC_CONFIDENCE                  1162
#define IDC_2X                          1163
#define IDC_DIV2                        1164
#define IDC_ARBVAL                      1165
#define IDC_RESET                       1166
#define IDC_SKIPVAL                     1167
#define IDC_STICK                       1167
#define IDC_INVERT                      1168
#define IDC_UNSTICK                     1168
#define IDC_ARBITRARY                   1169
#define IDC_ARBTXT                      1170
#define IDC_SKIPTXT                     1171
#define IDC_CURBPM                      1172
#define IDC_SKIPFIRST                   1172
#define IDC_CURCONF                     1173
#define IDC_SKIPFIRSTTXT                1173
#define IDC_SKIP                        1174
#define IDC_IN                          1175
#define IDC_OUT                         1176
#define IDC_NPOINTS                     1177
#define IDC_ROTATE                      1178
#define IDC_ALPHA                       1179
#define IDC_ROTATE2                     1180
#define IDC_DISTANCE2                   1181
#define IDC_ALPHA2                      1182
#define IDC_RGB                         1183
#define IDC_RGB2                        1184
#define IDC_INITROT                     1185
#define IDC_DEBUGREG_1                  1186
#define IDC_DEBUGREG_2                  1187
#define IDC_DEBUGREG_3                  1188
#define IDC_DEBUGREG_4                  1189
#define IDC_DEBUGREG_5                  1190
#define IDC_DEBUGREG_6                  1191
#define IDC_DEBUGREG_7                  1192
#define IDC_DEBUGREG_8                  1193
#define IDC_DEBUGREG_9                  1194
#define IDC_DEBUGREG_10                 1195
#define IDC_DEBUGREG_11                 1196
#define IDC_DEBUGREG_12                 1197
#define IDC_DEBUGREG_13                 1198
#define IDC_DEBUGREG_14                 1199
#define IDC_DEBUGREG_15                 1200
#define IDC_DEBUGREG_16                 1201
#define IDC_TAB1                        1203
#define IDC_LABEL1                      1204
#define IDC_STATIC_ALPHA                1205
#define IDC_STATIC_TRANS_TOTAL          1206
#define IDC_STATIC_TRANS_NONE           1207
#define IDC_THREADS                     1208
#define IDC_THREADSBORDER               1209
#define IDC_STATIC1                     1210
#define IDC_STATIC2                     1211
#define IDM_DISPLAY                     40001
#define IDM_PRESETS                     40002
#define IDM_TRANS                       40003
#define IDM_ABOUT                       40004
#define IDM_BPM                         40005
#define IDM_TRANSITIONS                 40006
#define IDM_FULLSCREEN                  40007
#define IDM_HELP_DEBUGWND               40008
#define IDM_UNDO                        40009
#define IDM_REDO                        40010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1212
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
