#ifndef NULLSOFT_WAC_DOWNLOAD_MANAGER_GLOBAL_H
#define NULLSOFT_WAC_DOWNLOAD_MANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(WAC_DOWNLOAD_MANAGER_LIB)
#  define WAC_DOWNLOAD_MANAGER_EXPORT Q_DECL_EXPORT
# else
#  define WAC_DOWNLOAD_MANAGER_EXPORT Q_DECL_IMPORT
# endif
#else
# define WAC_DOWNLOAD_MANAGER_EXPORT
#endif

#endif // !NULLSOFT_WAC_DOWNLOAD_MANAGER_GLOBAL_H