#include <precomp.h>
#include "api_makidebug.h"

#ifdef CBCLASS
#undef CBCLASS
#endif
#define CBCLASS api_makiDebuggerI
START_DISPATCH;
  VCB(API_MAKIDEBUGGER_DEBUGGER_TRACE, debugger_trace);
  CB(API_MAKIDEBUGGER_DEBUGGER_ISACTIVE, debugger_isActive);
  CB(API_MAKIDEBUGGER_DEBUGGER_GETVIP, debugger_getVIP);
  CB(API_MAKIDEBUGGER_DEBUGGER_GETVSD, debugger_getVSD);
  CB(API_MAKIDEBUGGER_DEBUGGER_GETVCC, debugger_getVCC);
  CB(API_MAKIDEBUGGER_DEBUGGER_GETVSP, debugger_getVSP);
  CB(API_MAKIDEBUGGER_DEBUGGER_FILTEREVENT, debugger_filterEvent);
  VCB(API_MAKIDEBUGGER_DEBUGGER_EVENTCOMPLETE, debugger_eventComplete);
  CB(API_MAKIDEBUGGER_DEBUGGER_CREATEJITD, debugger_createJITD);
  CB(API_MAKIDEBUGGER_DEBUGGER_READSTACK, debugger_readStack);
  CB(API_MAKIDEBUGGER_DEBUGGER_GETCODEBLOCK, debugger_getCodeBlock);
END_DISPATCH;
