//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by in_midi.rc
//
#define IDS_NULLSOFT_MIDI_PLAYER_OLD    0
#define STRING_FILES_OTHER              2
#define IDRESET                         3
#define IDS_TO_ENABLE_LYRICS_DISPLAY    3
#define IDS_INFORMATION                 4
#define STRING_INCOMPLETE               5
#define STRING_TRACKS_FMT               6
#define IDS_MIDIS_ARE_NOT_BURNABLE      7
#define IDS_ABOUT_TITLE                 9
#define IDS_NONE                        10
#define IDS_STREAMED                    11
#define IDS_IMMEDIATE                   12
#define IDS_CONFIGURATION               13
#define IDS_TYPE                        14
#define IDS_PREFS_DEVICE                15
#define IDS_PREFS_DISPLAY               16
#define IDS_PREFS_SAMPLING              17
#define IDS_PREFS_DIRECTMUSIC           18
#define IDS_PREFS_MISC                  19
#define IDS_PREFS_FILE_TYPES            20
#define IDS_PREFS_FILES                 21
#define IDS_PREFS_HARDWARE_SETUP        22
#define IDS_UNABLE_TO_LOAD_FILE         23
#define STRING_RETRIEVING_FILE          24
#define STRING_URL_ERROR                25
#define STRING_UNKNOWN_MMSYSTEM         26
#define STRING_MIDI_INFO_FMT2           27
#define STRING_MIDI_INFO_FMT1           28
#define STRING_BYTES_FMT                29
#define STRING_WRITE_ERROR_FMT          30
#define STRING_INFO_FORMAT_FMT          31
#define STRING_RMI_INFO_FMT             32
#define STRING_CONFIG_RESET             33
#define STRING_STEREO                   34
#define STRING_MONO                     35
#define STRING_VOLUME_AUTO              36
#define STRING_VOLUME_DRIVER_SPECIFIC   37
#define STRING_VOLUME_NONE              38
#define STRING_SAMP_SRC_DEFAULT         39
#define STRING_LOOP1                    40
#define STRING_LOOP2                    41
#define STRING_LOOP3                    42
#define STRING_UNKNOWN                  43
#define STRING_DIRECT_MIDISTREAM        44
#define STRING_MOCAPS_WAVETABLE         45
#define STRING_MOCAPS_SYNTH             46
#define STRING_MOCAPS_SQUARE            47
#define STRING_MOCAPS_MAPPER            48
#define STRING_MOCAPS_HWPORT            49
#define STRING_MOCAPS_FM                50
#define STRING_EFFECTS                  51
#define STRING_DEVICE_TYPE              52
#define STRING_DMCAPS_WDM               53
#define STRING_DMCAPS_USERMODE          54
#define STRING_DMCAPS_WINMM             55
#define STRING_CHORUS                   56
#define STRING_REVERB                   57
#define STRING_DMCAPS_SHARE             58
#define STRING_DMCAPS_DSOUND            59
#define STRING_DMCAPS_XG                60
#define STRING_DMCAPS_GS                61
#define STRING_DMCAPS_GM                62
#define STRING_DMCAPS_SOFTSYNTH         63
#define STRING_DMCAPS_DLS2              64
#define STRING_DMCAPS_DLS1              65
#define STRING_FILES_SMF                66
#define STRING_FILES_CLONE              67
#define STRING_FILES_COMPRESSED         68
#define IDS_SYSEX_DATA                  69
#define IDS_MIDI_HARDWARE_PRESETS       70
#define IDS_DLS_FILES                   71
#define IDS_MIDI_FILES                  72
#define IDS_COMPRESSED_MIDI_FILES       73
#define IDS_RMI_FILES                   74
#define IDS_COMPRESSED_RMI_FILES        75
#define IDS_WITH_OUTPUT                 76
#define IDS_STRING105                   77
#define IDS_USES_WINAMPS_OUTPUT_PLUGINS 77
#define STRING_MS_FMT                   78
#define STRING_BIT_FMT                  79
#define IDS_FAMILY_STRING_MIDI          80
#define IDS_FAMILY_STRING_KARAOKE_MIDI  81
#define IDS_FAMILY_STRING_HMI_MIDI      82
#define IDS_FAMILY_STRING_EXTENDED_MIDI 83
#define IDS_FAMILY_STRING_MSS_MIDI      84
#define IDS_FAMILY_STRING_FINALE_MIDI   85
#define IDS_FAMILY_STRING_CREATIVE_MIDI 86
#define IDS_FAMILY_STRING_GENERAL_MIDI_DUMP 87
#define IDS_FAMILY_STRING_COMPRESSED_MIDI 88
#define IDS_FAMILY_STRING_COMPRESSED_HMI_MIDI 89
#define IDS_ABOUT                       90
#define IDS_ABOUT_TEXT                  90
#define IDD_CONFIG                      101
#define IDD_INFO                        102
#define IDD_CONFIG1                     117
#define IDD_CONFIG2                     118
#define IDD_CONFIG3                     119
#define IDD_CONFIG4                     120
#define IDD_CONFIG5                     121
#define IDD_CONFIG6                     122
#define IDD_SYSEX                       123
#define IDD_EXT_IMM                     124
#define IDD_CONFIG7                     125
#define IDD_RMI_SHIZ                    127
#define IDD_CONFIG8                     128
#define IDD_LYRICS                      129
#define IDC_PORT                        1001
#define IDC_MS                          1011
#define IDC_TIX                         1012
#define IDC_FORMAT                      1013
#define IDC_NTRAX                       1014
#define IDC_TRAX                        1017
#define IDC_COPYRIGHT                   1018
#define IDC_COMMENT                     1019
#define IDC_SUBJECT                     1020
#define IDC_FREQ                        1030
#define IDC_REVERB                      1031
#define IDC_DLS_CB                      1032
#define IDC_DLS                         1033
#define IDC_DLS_B                       1034
#define IDC_CHORUS                      1036
#define IDC_SAVE                        1040
#define IDC_RMI_CRAP                    1041
#define IDC_SAMPLING_ENABLED            1041
#define IDC_RTFM                        1050
#define IDC_EDIT1                       1052
#define IDC_ARTIST                      1054
#define IDC_LOOP                        1055
#define IDC_DATE                        1055
#define IDC_ALBUM                       1056
#define IDC_LOOP_S                      1057
#define IDC_SOFTWARE                    1057
#define IDC_LOOP_S2                     1058
#define IDC_TRACK                       1058
#define IDC_FSIZE                       1059
#define IDC_ENGINEER                    1059
#define IDC_COMPOSER                    1060
#define IDC_NAME                        1071
#define IDC_SAMPLING_DSP                1072
#define IDC_SAMPLING_OUTPUT             1073
#define IDC_STATIC1                     1075
#define IDC_STATIC2                     1077
#define IDC_STATIC3                     1079
#define IDC_DEV_INFO                    1081
#define IDC_INFINITE                    1084
#define IDC_LOOP_T                      1086
#define IDC_LOOP_SP                     1088
#define IDC_LOOP_S3                     1089
#define IDC_WAVEIN                      1090
#define IDC_WAVEIN_SRC                  1094
#define IDC_HACK_NO_SYSEX               1096
#define IDC_PLAYBACK_METHOD             1107
#define IDC_TAB                         1108
#define IDC_STATIC_CLN                  1124
#define IDC_STATIC_MOS                  1126
#define IDC_IMP_F                       1127
#define IDC_EXP_F                       1128
#define IDC_IMP_PR                      1129
#define IDC_EXP_PR                      1130
#define IDC_SYSEX_EDIT                  1131
#define IDC_SYSEX_DELETE                1132
#define IDC_SYSEX_ADD                   1133
#define IDC_SYSEX_LIST                  1134
#define IDC_DELAY                       1135
#define IDC_SYSEX_UP                    1136
#define IDC_SPIN1                       1137
#define IDC_SYSEX_DOWN                  1138
#define IDC_STATIC_MOS1                 1139
#define IDC_NOVOL                       1140
#define IDC_DM_IMM                      1141
#define IDC_HACK_DM_RESETS              1142
#define IDC_TEMPO                       1145
#define IDC_SHOW_PANEL                  1146
#define IDC_TDISP                       1147
#define IDC_ALL_ON                      1180
#define IDC_ALL_OFF                     1181
#define IDC_GMRESET                     1182
#define IDC_GSRESET                     1183
#define IDC_DM_KEEP_PORT                1184
#define IDC_XGRESET                     1185
#define IDC_EXTS_LIST                   1207
#define IDC_EXTS_ED                     1208
#define IDC_SYSEX1                      1215
#define IDC_SYSEX1_SEND                 1216
#define IDC_VOLMODE                     1217
#define IDC_HARDWARE_RESET              1218
#define IDC_SYSEX2                      1221
#define IDC_SYSEX2_SEND                 1222
#define IDC_NOINS                       1223
#define IDC_HACKTRACK                   1225
#define IDC_HACK_DLS_DRUMS              1226
#define IDC_HACK_XG_DRUMS               1228
#define IDC_HACK_DLS_INSTRUMENTS        1229
#define IDC_WAVEIN_SR                   1234
#define IDC_WAVEIN_CH                   1235
#define IDC_WAVEIN_BPS                  1236
#define IDC_WAVEIN_S2                   1237
#define IDC_DISP                        1238
#define IDC_GENRE                       1241
#define IDC_EOF_DELAY                   1242
#define IDC_EOF_DELAY_SPIN              1243
#define IDC_LOGVOL                      1244
#define IDC_BLAH                        1245
#define IDC_BMPVIEW                     1251
#define IDC_SAMP_REVERT                 1261
#define IDC_RMI_DEF                     2000
#define IDC_RMI_FMT                     2002
#define IDC_LYRICS_ENABLED              2003
#define IDS_NULLSOFT_MIDI_PLAYER        65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
