// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:55:56 2003]
// 
// File        : api_applicationx.cpp
// Class       : api_application
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------
#include <precomp.h>

#include "api_applicationx.h"

#ifdef CBCLASS
#undef CBCLASS
#endif

#define CBCLASS api_applicationX
START_DISPATCH;
  CB(API_APPLICATION_MAIN_GETAPPNAME, main_getAppName);
  CB(API_APPLICATION_MAIN_GETVERSIONSTRING, main_getVersionString);
  CB(API_APPLICATION_MAIN_GETBUILDNUMBER, main_getBuildNumber);
  CB(API_APPLICATION_MAIN_GETGUID, main_getGUID);
  CB(API_APPLICATION_MAIN_GETMAINTHREADHANDLE, main_getMainThreadHandle);
  CB(API_APPLICATION_MAIN_GETHINSTANCE, main_gethInstance);
  CB(API_APPLICATION_MAIN_GETCOMMANDLINE, main_getCommandLine);
  VCB(API_APPLICATION_MAIN_SHUTDOWN, main_shutdown);
  VCB(API_APPLICATION_MAIN_CANCELSHUTDOWN, main_cancelShutdown);
  CB(API_APPLICATION_MAIN_ISSHUTTINGDOWN, main_isShuttingDown);
  CB(API_APPLICATION_PATH_GETAPPPATH, path_getAppPath);
  CB(API_APPLICATION_PATH_GETUSERSETTINGSPATH, path_getUserSettingsPath);
  CB(API_APPLICATION_APP_GETINITCOUNT, app_getInitCount);
  CB(API_APPLICATION_APP_MESSAGELOOPSTEP, app_messageLoopStep);
END_DISPATCH;
#undef CBCLASS
