// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:55:56 2003]
// 
// File        : api_application.cpp
// Class       : api_application
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include <precomp.h>
#include "api_application.h"


