// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Wed May 07 00:55:56 2003]
// 
// File        : api_applicationx.h
// Class       : api_application
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#ifndef __API_APPLICATIONX_H
#define __API_APPLICATIONX_H

#include "api_application.h"




// ----------------------------------------------------------------------------

class api_applicationX : public api_application {
  protected:
    api_applicationX() {}
  public:
    virtual const wchar_t *main_getAppName()=0;
    virtual const wchar_t *main_getVersionString()=0;
    virtual unsigned int main_getBuildNumber()=0;
    virtual GUID main_getGUID()=0;
    virtual HANDLE main_getMainThreadHandle()=0;
    virtual HINSTANCE main_gethInstance()=0;
    virtual const wchar_t *main_getCommandLine()=0;
    virtual void main_shutdown(int deferred = TRUE)=0;
    virtual void main_cancelShutdown()=0;
    virtual int main_isShuttingDown()=0;
    virtual const wchar_t *path_getAppPath()=0;
    virtual const wchar_t *path_getUserSettingsPath()=0;
    virtual int app_getInitCount()=0;
    virtual int app_messageLoopStep()=0;
  
  protected:
    RECVS_DISPATCH;
};

#endif // __API_APPLICATIONX_H
