//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winampa.rc
//
#define IDS_WINAMP_AGENT                0
#define IDS_OPEN_WINAMP                 1
#define IDS_DISABLE_WINAMP_AGENT        2
#define IDS_CLOSE_WINAMP_AGENT          3
#define IDS_AUDIO_CD                    4
#define IDS_EMPTY                       5
#define IDS_BOOKMARKS                   6
#define IDS_NO_BOOKMARKS_FOUND          7
#define IDS_WINAMP_AGENT_ERROR          8
#define IDS_CANNOT_REGISTER_WINDOW_CLASS 9
#define IDS_STRING10                    10
#define IDS_CANNOT_CREATE_WINDOW        10
#define IDI_ICON1                       101
#define IDS_STRING105                   65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
