// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri Oct 17 16:03:31 2003]
// 
// File        : api_locales.cpp
// Class       : api_locales
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#include <precomp.h>
#include "api_locales.h"


