// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Fri Oct 17 16:03:31 2003]
// 
// File        : api_localesx.h
// Class       : api_locales
// class layer : Dispatchable Receiver
// ----------------------------------------------------------------------------

#ifndef __API_LOCALESX_H
#define __API_LOCALESX_H

#include "api_locales.h"

// ----------------------------------------------------------------------------

class api_localesX : public api_locales {
  protected:
    api_localesX() {}
  public:
	virtual const wchar_t *locales_getTranslation(const wchar_t *str)=0;
    virtual void locales_addTranslation(const wchar_t *from, const wchar_t *to)=0;
    virtual const wchar_t *locales_getBindFromAction(int action)=0;
    //virtual int locales_getNumEntries()=0;
    //virtual const wchar_t  *locales_enumEntry(int n)=0;
    virtual void locales_registerAcceleratorSection(const wchar_t *name, ifc_window *wnd, int global = 0)=0;
  
  protected:
    RECVS_DISPATCH;
};

#endif // __API_LOCALESX_H