//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by omBrowser.rc
//
#define IDS_ENCRYPTION_MIXED            102
#define IDS_ENCRYPTION_40BIT            103
#define IDS_ENCRYPTION_56BIT            104
#define IDR_CONTEXTMENU                 104
#define IDS_ENCRYPTION_FORTEZZA         105
#define IDD_BROWSER_OPTIONS             105
#define IDS_ENCRYPTION_128BIT           106
#define IDD_OPTIONS_UI                  106
#define IDS_CONNECTION_UNSECURE         107
#define IDD_OPTIONS_DEBUG               107
#define IDS_CONNECTION_ENCRYPTED        108
#define IDD_OPTIONS_INFO                108
#define IDS_CURRENT_PAGE                109
#define IDS_OMBROWSER_TITLE             110
#define IDS_RATING_0                    111
#define IDS_RATING_1                    112
#define IDS_RATING_2                    113
#define IDS_RATING_3                    114
#define IDS_RATING_4                    115
#define IDS_RATING_5                    116
#define IDS_RATING_CHANGETO             117
#define IDS_RATING_CURRENT              118
#define IDS_MORE                        119
#define IDS_HOME                        120
#define IDS_HOME_DESCRIPTION            121
#define IDS_BACK                        122
#define IDS_BACK_DESCRIPTION            123
#define IDS_FORWARD                     124
#define IDS_FORWARD_DESCRIPTION         125
#define IDS_REFRESH                     126
#define IDS_REFRESH_DESCRIPTION         127
#define IDS_STOP                        128
#define IDS_STOP_DESCRIPTION            129
#define IDS_SEPARATOR                   130
#define IDS_SPACE                       131
#define IDS_FLEXSPACE                   132
#define IDS_MORE_DESCRIPTION            133
#define IDS_RATED                       134
#define IDS_PLEASE_WAIT                 135
#define IDS_SERVICE_VERSIONCHECK        136
#define IDS_SERVICE_GETINFO             137
#define IDS_SERVICE_GETINFO_DESCRIPTION 138
#define IDS_SERVICE_REPORT              139
#define IDS_SERVICE_REPORT_DESCRIPTION  140
#define IDS_SERVICE_UNSUBSCRIBE         141
#define IDS_SERVICE_UNSUBSCRIBE_DESCRIPTION 142
#define IDS_SECURE_CONNECTION           143
#define IDS_SCRIPT_ERROR                144
#define IDS_SCRIPT_ERROR_DESCRIPTION    145
#define IDS_HISTORY                     146
#define IDS_HISTORY_DESCRIPTION         147
#define IDS_NAVIGATING                  148
#define IDS_OPTIONS_UI                  149
#define IDS_OPTIONS_DEBUG               150
#define IDS_OPTIONS_INFO                151
#define IDS_TOOLBAR_TOPDOCK             152
#define IDS_TOOLBAR_BOTTOMDOCK          153
#define IDS_UNKNOWN                     154
#define IDS_STORAGE_INI                 155
#define IDS_STORAGE_XML                 156
#define IDR_BROWSERPOPUPACCEL           156
#define IDS_STORAGE_URL                 157
#define IDR_BROWSERACCEL                237
#define IDC_TABFRAME                    1001
#define IDC_TOOLBAR_LOCATION            1002
#define IDC_CHECK1                      1003
#define IDC_FILTERMENU                  1003
#define IDC_CHECK2                      1004
#define IDC_SHOWERROR                   1004
#define IDC_CHECK3                      1005
#define IDC_SHOWDEBUGGER                1005
#define IDC_TOOLBAR_AUTOHIDE            1006
#define IDC_TOOLBAR_TABSTOP             1007
#define IDC_STATUSBAR_ENABLED           1008
#define IDC_TITLE                       1009
#define IDC_TOOLBAR_FORCEADDRESS        1009
#define IDC_TOOLBAR_TABSTOP3            1010
#define IDC_TOOLBAR_FANCYADDRESS        1010
#define IDC_VERSION                     1013
#define IDC_MSIEVERSION                 1014
#define IDC_CLASS                       1015
#define IDC_CONFIGPATH                  1016
#define IDC_SESSIONID                   1017
#define IDC_SESSIONID2                  1018
#define IDC_CLIENTID                    1018
#define IDR_CURTAINPROGRESS_IMAGE       20000
#define IDR_TOOLBARLARGE_IMAGE          20001
#define IDR_TOOLBARPROGRESS_IMAGE       20002
#define IDR_MENUARROW_IMAGE             20003
#define IDR_SERVICEICON_IMAGE           20004
#define IDR_TOOLBARADDRESS_IMAGE        20005
#define ID_ADDRESSBAR_COPY              40016
#define ID_ADDRESSBAR_COPYADDRESS       40017
#define ID_ADDRESSBAR_EDITADDRESS       40018
#define ID_ADDRESSBAR_ACTIVATE          40019
#define ID_RATING_VALUE_5               40100
#define ID_RATING_VALUE_4               40101
#define ID_RATING_VALUE_3               40102
#define ID_RATING_VALUE_2               40103
#define ID_RATING_VALUE_1               40104
#define ID_SERVICE_REPORT               40105
#define ID_SERVICE_UNSUBSCRIBE          40106
#define ID_SERVICE_GETINFO              40107
#define ID_NAVIGATION_HOME              40108
#define ID_NAVIGATION_BACK              40109
#define ID_NAVIGATION_FORWARD           40110
#define ID_NAVIGATION_STOP              40111
#define ID_NAVIGATION_REFRESH           40112
#define ID_NAVIGATION_REFRESH_COMPLETELY 40113
#define ID_NAVIGATION_HISTORY           40114
#define ID_TOOLBAR_DOCKTOP              40115
#define ID_TOOLBAR_DOCKBOTTOM           40116
#define ID_TOOLBAR_AUTOHIDE             40117
#define ID_TOOLBAR_TABSTOP              40118
#define ID_BROWSER_SECURECONNECTION     40119
#define ID_BROWSER_SCRIPTERROR          40120
#define ID_WINDOW_FULLSCREEN            40121
#define ID_WINDOW_CLOSE                 40122
#define ID_ADDRESSBAR_CHANGED           40123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
