//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by script1.rc
//
#define IDS_NULLSOFT_MODULE_DECODER_OLD 0
#define IDS_PROTRACKER_AND_CLONES       1
#define IDS_OLD_SKOOL_AMIGA_MODULES     2
#define IDS_SCREAM_TRACKER_2XX          3
#define IDS_SCREAM_TRACKER_3XX          4
#define IDS_IMPULSE_TRACKER             5
#define IDS_FASTTRACKER_2XX             6
#define IDS_MULTITRACKER                7
#define IDS_ULTRA_TRACKER               8
#define IDS_COMPOSER_669                9
#define IDS_FARANDOLE_COMPOSER          10
#define IDS_DIGITAL_SOUND_AND_MUSIC_INTERFACE 11
#define IDS_AMIGA_OKTALYZER             12
#define IDS_POLYTRACKER                 13
#define IDS_MULTIPLE_ITEMS_SELECTED     14
#define IDS_MUSIC_MODULES               15
#define IDS_MIXER                       16
#define IDS_PLAYER                      17
#define IDS_LOADERS                     18
#define IDS_DEFAULT                     19
#define IDS_SELECT_ANY_LOADER           20
#define IDS_DO_NOT_LOOP                 21
#define IDS_LOOP_FOREVER                22
#define IDS_LOOP_X_TIMES                23
#define IDS_PREFERENCES_TITLE           24
#define IDS_SAMPLES                     26
#define IDS_INSTRUMENTS                 27
#define IDS_COMMENT                     28
#define IDS_YES                         29
#define IDS_NO                          30
#define IDS_SUSTAIN                     31
#define IDS_FINETUNE                    32
#define IDS_HZ_SIGNED                   33
#define IDS_HZ_UNSIGNED                 34
#define IDS_PING_PONG                   35
#define IDS_REVERSE                     36
#define IDS_FORWARD                     37
#define IDS_SUSTAIN_PING_PONG           38
#define IDS_NONE                        39
#define IDS_X_X_X_OF_X_NOT_PLAYING      40
#define IDS_X_X_X_OF_X_X_OF_X_X_OF_X    41
#define IDS_X_BTYES_X_OF_X_MINUTES      42
#define IDS_URLS_ONLY_SUPPORTED_IN_2_10_PLUS 43
#define IDS_MOD_PLUGIN_ERROR            44
#define IDS_SAVE_MODULE                 45
#define IDS_ALL_FILES                   46
#define IDS_RETRIEVING_MODULE           47
#define IDS_ERROR_KILLING_DECODING_THREAD 48
#define IDS_LOOP                        49
#define IDS_ON                          50
#define IDS_OFF                         51
#define IDS_BYTES                       52
#define IDS_BYTES2                      53
#define IDS_BITS                        53
#define IDS_FAMILY_STRING_COMPOSER_669  54
#define IDS_FAMILY_STRING_DSMI_AMF      55
#define IDS_FAMILY_STRING_FARANDOLE_COMPOSER 56
#define IDS_FAMILY_STRING_IMPULSETRACKER 57
#define IDS_FAMILY_STRING_SOUNDTRACKER  58
#define IDS_FAMILY_STRING_PROTRACKER    59
#define IDS_FAMILY_STRING_MULTITRACKER  60
#define IDS_FAMILY_STRING_AMIGA_OKTALYZER 61
#define IDS_FAMILY_STRING_POLYTRACKER   62
#define IDS_FAMILY_STRING_SCREAMTRACKER3 63
#define IDS_FAMILY_STRING_SCREAMTRACKER2 64
#define IDS_FAMILY_STRING_ULTRATRACKER  65
#define IDS_FAMILY_STRING_FASTRACKER2   66
#define IDS_FAMILY_STRING_NOISETRACKER  67
#define IDS_X_MODULE                    68
#define IDS_X_COMPRESSED_MODULE         69
#define IDS_ABOUT_TEXT                  70
#define IDS_CORRUPT_UNSUPPORTED_TYPE    71
#define IDS_NULLSOFT_DS_OUTPUT          72
#define IDD_ID3EDIT                     101
#define IDD_SAMPLES                     108
#define IDD_COMMENT                     109
#define IDD_INSTRUMENTS                 111
#define IDD_PREFS                       116
#define IDD_PREFTAB_DECODER             118
#define IDD_PREFTAB_MIXER               119
#define IDD_PREFTAB_LOADER              123
#define IDC_PREFS_PRIORITY_DECODE       1076
#define IDC_TYPE                        1078
#define IDC_TITLE                       1079
#define IDC_ID3_FN                      1090
#define OQ_INTERP                       1100
#define IDLDR_EFFOPT1                   1102
#define OQ_NOCLICK                      1103
#define IDC_SAVESTR                     1105
#define IDC_VOICES                      1106
#define IDC_INSTLIST                    1108
#define TB_SAMPLELIST                   1109
#define IDC_SAMPLIST                    1110
#define IDC_INFORIGHT                   1111
#define IDC_INFOLEFT                    1112
#define IDC_TAB                         1113
#define IDC_SAMPINFO                    1115
#define CEMENT_BOX                      1116
#define IDC_INSTENV                     1118
#define IDC_INSTHEAD                    1120
#define IDC_ID3FORMAT                   1127
#define MM_PREFTAB                      1132
#define IDC_PANSEP                      1132
#define IDC_DEFPAN                      1137
#define OQ_QUALITY                      1139
#define IDLDR_LIST                      1140
#define IDLDR_PANPOS                    1141
#define IDLDR_ENABLED                   1142
#define IDLDR_EFFOPT2                   1144
#define IDLDR_DESCRIPTION               1145
#define IDC_LOOPALL                     1146
#define IDC_CONT_LOOP                   1147
#define IDC_FADEOUT                     1148
#define IDC_FADESPIN                    1149
#define IDC_PLAYALL                     1150
#define IDC_RESONANCE                   1151
#define IDC_FADECHECK                   1152
#define IDC_FADESEC                     1153
#define IDC_STRIPSILENCE                1154
#define IDC_SEEKBYORDERS                1155
#define IDC_TITLE_FORMAT                1156
#define IDC_TAGZ_HELP                   1157
#define OQ_CUBIC                        1158
#define IDC_TAGZ_DEF                    1158
#define IDC_SAMPLESIZE                  1159
#define IDC_TITLE_FORMAT2               1159
#define IDC_LOOPTEXT                    1160
#define IDC_LOOPS                       1161
#define IDC_TRACK                       1162
#define IDC_ADV_TEXT_INFO               1163
#define OUTMODE_STEREO                  1201
#define OUTMODE_SURROUND                1202
#define OUTMODE_REVERSE                 1203
#define IDS_NULLSOFT_MODULE_DECODER     65534

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
