SET INSTALL_NAME=winamp512_0224_beta

SET INSTALL_FILE_NAME=%INSTALL_NAME%
if %TARGET_ARCH%==x86 goto skip64
SET INSTALL_FILE_NAME=%INSTALL_NAME%_x64
:skip64

if NOT %BRANDING%==NULLSOFT goto branded_names
SET INSTALL_FULL=%INSTALL_FILE_NAME%_full
SET INSTALL_STD=%INSTALL_FILE_NAME%_std
SET INSTALL_LITE=%INSTALL_FILE_NAME%_lite
SET INSTALL_PRO=%INSTALL_FILE_NAME%_pro
SET INSTALL_EMUSIC=%INSTALL_FILE_NAME%_full_emusic-7plus
SET INSTALL_BUNDLE=%INSTALL_FILE_NAME%_full_bundle_emusic-7plus
SET INSTALL_DEVICES=%INSTALL_FILE_NAME%_full_devices
goto end

:branded_names
SET INSTALL_FULL=%INSTALL_FILE_NAME%_%BRANDING%
SET INSTALL_STD=junk
SET INSTALL_LITE=junk
SET INSTALL_PRO=junk
SET INSTALL_EMUSIC=junk
SET INSTALL_BUNDLE=junk
SET INSTALL_DEVICES=junk

:end









