// ----------------------------------------------------------------------------
// Generated by InterfaceFactory [Thu May 15 21:07:09 2003]
// 
// File        : xmlparams.h
// Class       : skin_xmlreaderparams
// class layer : Dispatchable Interface
// ----------------------------------------------------------------------------

#ifndef __XMLREADERPARAMS_H
#define __XMLREADERPARAMS_H

#include <bfc/dispatch.h>
//#include <bfc/common.h>
#include "../xml/ifc_xmlreaderparams.h"

// ----------------------------------------------------------------------------

class NOVTABLE skin_xmlreaderparams : public ifc_xmlreaderparams 
{
  protected:
    skin_xmlreaderparams() {}
    ~skin_xmlreaderparams() {}
  public:
		/*
    const wchar_t *getItemName(int i);
    const wchar_t *getItemValue(int i);
    const wchar_t *getItemValue(const wchar_t *name);
    const wchar_t *enumItemValues(const wchar_t *name, int nb);
    int getItemValueInt(const wchar_t *name, int def = 0);
    int getNbItems();
		*/
    void addItem(const wchar_t *parm, const wchar_t *value);
    void removeItem(const wchar_t *parm);
    void replaceItem(const wchar_t *parm, const wchar_t *value);
    int findItem(const wchar_t *parm);
  
  protected:
    enum {
      /*XMLREADERPARAMS_GETITEMNAME = 100,
      XMLREADERPARAMS_GETITEMVALUE = 200,
      XMLREADERPARAMS_GETITEMVALUE2 = 201,
      XMLREADERPARAMS_ENUMITEMVALUES = 202,
      XMLREADERPARAMS_GETITEMVALUEINT = 300,
      XMLREADERPARAMS_GETNBITEMS = 400,*/
      XMLREADERPARAMS_ADDITEM = 500,
      XMLREADERPARAMS_REMOVEITEM = 600,
      XMLREADERPARAMS_REPLACEITEM = 700,
      XMLREADERPARAMS_FINDITEM = 800,
    };
};

// ----------------------------------------------------------------------------
/*
inline const wchar_t *skin_xmlreaderparams::getItemName(int i) {
  const wchar_t *__retval = _call(XMLREADERPARAMS_GETITEMNAME, (const wchar_t *)0, i);
  return __retval;
}

inline const wchar_t *skin_xmlreaderparams::getItemValue(int i) {
  const wchar_t *__retval = _call(XMLREADERPARAMS_GETITEMVALUE, (const wchar_t *)0, i);
  return __retval;
}

inline const wchar_t *skin_xmlreaderparams::getItemValue(const wchar_t *name) {
  const wchar_t *__retval = _call(XMLREADERPARAMS_GETITEMVALUE2, (const wchar_t *)0, name);
  return __retval;
}

inline const wchar_t *skin_xmlreaderparams::enumItemValues(const wchar_t *name, int nb) {
  const wchar_t *__retval = _call(XMLREADERPARAMS_ENUMITEMVALUES, (const wchar_t *)0, name, nb);
  return __retval;
}

inline int skin_xmlreaderparams::getItemValueInt(const wchar_t *name, int def) {
  int __retval = _call(XMLREADERPARAMS_GETITEMVALUEINT, (int)0, name, def);
  return __retval;
}

inline int skin_xmlreaderparams::getNbItems() {
  int __retval = _call(XMLREADERPARAMS_GETNBITEMS, (int)0);
  return __retval;
}
*/
inline void skin_xmlreaderparams::addItem(const wchar_t *parm, const wchar_t *value) {
  _voidcall(XMLREADERPARAMS_ADDITEM, parm, value);
}

inline void skin_xmlreaderparams::removeItem(const wchar_t *parm) {
  _voidcall(XMLREADERPARAMS_REMOVEITEM, parm);
}

inline void skin_xmlreaderparams::replaceItem(const wchar_t *parm, const wchar_t *value) {
  _voidcall(XMLREADERPARAMS_REPLACEITEM, parm, value);
}

inline int skin_xmlreaderparams::findItem(const wchar_t *parm) {
  int __retval = _call(XMLREADERPARAMS_FINDITEM, (int)0, parm);
  return __retval;
}

// ----------------------------------------------------------------------------

#endif // __XMLREADERPARAMS_H
